{
  "name": "YTD_source", 
  "compatibilityLevel": 1567,
  "model": {
    "culture": "nl-BE",
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true,
      "fastCombine": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "discourageImplicitMeasures": true,
    "sourceQueryCulture": "nl-BE",
    "tables": [
      {
        "name": "Key Measures",
        "lineageTag": "7ffad234-ff9b-45f1-b589-6376d9a669bd",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Column",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Column]",
            "formatString": "0",
            "displayFolder": "Varia",
            "lineageTag": "bdf9ce3b-5cf6-4e9d-9879-09f14f1f76e2",
            "summarizeBy": "sum",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Key Measures-ad0f8a3d-924f-4754-85f3-d046e43fad03",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": "Row(\"Column\", BLANK())"
            }
          }
        ],
        "measures": [
          {
            "name": "Besteed",
            "description": [
              "// Het tweede argument is nodig omdat sommige boekingen nog niet volledig afgesloten zijn",
              "// Periode YTD bevat enkel de actuals die zeker afgesloten zijn",
              "// ref https://www.sqlbi.com/articles/hiding-future-dates-for-calculations-in-dax/",
              "",
              "VAR filterytd = SELECTEDVALUE( switch_ytd[value], 1 )",
              "VAR ShowRow =",
              "    OR(",
              "        [BrowseDepth] <= [RowDepth],",
              "        ISINSCOPE( soort[soort_omschrijving] )",
              "    )",
              "VAR actualsytd =",
              "    CALCULATE(",
              "        IF( ShowRow, SUM( actuals[actual] ) ),",
              "        CALCULATETABLE( 'date', 'date'[ytd?] <= filterytd )",
              "    )",
              "RETURN",
              "    actualsytd"
            ],
            "expression": "[Actuals] + [obligo]",
            "formatString": "#,0",
            "isHidden": true,
            "displayFolder": "!YTD\\Besteed",
            "lineageTag": "210b52b2-1cb9-40ba-8db0-916b7c8c568f",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ]
          },
          {
            "name": "Besteed YTD",
            "description": [
              "// Omdat er gewerkt wordt met een datumtabel om granualiteit YYYYMM kan je helaas niet met de standaard time intel functies werken",
              "// Dit zijn de uitgeschreven versies, dus zonder de \"syntax sugar\" dateytd",
              "VAR filterytd = SELECTEDVALUE( switch_ytd[value], 1 )",
              "VAR LastMonthAvailable = MAX( 'date'[Year Month Number] )",
              "VAR LastYearAvailable = MAX( 'date'[Year] )",
              "VAR Result =",
              "    CALCULATE(",
              "        [Actuals],",
              "        REMOVEFILTERS( 'date' ),",
              "        'date'[Year Month Number] <= LastMonthAvailable,",
              "        'date'[Year] = LastYearAvailable",
              "    )",
              "VAR iflogic =",
              "    IF( SELECTEDVALUE( 'date'[ytd?] ) <= filterytd, Result )",
              "RETURN",
              "    iflogic"
            ],
            "expression": [
              "VAR filterytd = SELECTEDVALUE( switch_ytd[value], 1 )",
              "VAR LastMonthAvailable = MAX( 'date'[Year Month Number] )",
              "VAR LastYearAvailable = MAX( 'date'[Year] )",
              "VAR Result =",
              "    CALCULATE(",
              "        [Besteed],",
              "        REMOVEFILTERS( 'date' ),",
              "        'date'[Year Month Number] <= LastMonthAvailable,",
              "        'date'[Year] = LastYearAvailable",
              "    )",
              "VAR iflogic =",
              "    IF( SELECTEDVALUE( 'date'[ytd?] ) <= filterytd, Result )",
              "RETURN",
              "    iflogic"
            ],
            "formatString": "#,##0",
            "isHidden": true,
            "displayFolder": "!YTD\\Besteed",
            "lineageTag": "664a2692-9b15-4241-955b-7fe57a833d2b",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ]
          },
          {
            "name": "Besteed PY",
            "description": [
              "// Omwille van de structuur tijdstabel niet mogelijk om met dateadd te werken",
              "VAR CurrentYearNumber = SELECTEDVALUE( 'date'[Year] )",
              "VAR PreviousYearNumber = CurrentYearNumber - 1",
              "VAR Result =",
              "    CALCULATE(",
              "        [Actuals],",
              "        REMOVEFILTERS( 'date' ),",
              "        'date'[Year] = PreviousYearNumber",
              "    )",
              "RETURN",
              "    Result"
            ],
            "expression": [
              "// Omwille van de structuur tijdstabel niet mogelijk om met dateadd te werken",
              "VAR CurrentYearNumber = SELECTEDVALUE( 'date'[Year] )",
              "VAR PreviousYearNumber = CurrentYearNumber - 1",
              "VAR Result =",
              "    CALCULATE(",
              "        [Besteed],",
              "        REMOVEFILTERS( 'date' ),",
              "        VALUES( 'date'[Month] ),",
              "        'date'[Year] = PreviousYearNumber",
              "    )",
              "RETURN",
              "    Result"
            ],
            "formatString": "#,0",
            "isHidden": true,
            "displayFolder": "!YTD\\Besteed",
            "lineageTag": "5cc69c31-807d-4707-ae26-7472b6d770fe",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ]
          },
          {
            "name": "|",
            "description": "BLANK( ) //UNICHAR(127)",
            "expression": [
              "BLANK( )",
              "//UNICHAR(127)"
            ],
            "formatString": "0",
            "isHidden": true,
            "displayFolder": "Varia",
            "lineageTag": "edc951dc-a4cb-4d64-93af-334fc78074c8",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ]
          },
          {
            "name": "Besteed ALLyear",
            "description": "CALCULATE( [Actuals], ALLEXCEPT( 'date', 'date'[Year] ) )",
            "expression": "CALCULATE( [Besteed], ALLEXCEPT( 'date', 'date'[Year] ) )",
            "isHidden": true,
            "displayFolder": "!YTD\\Besteed",
            "lineageTag": "2860c83d-af58-4fed-8728-98818a299a70",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "B rest maxyear",
            "description": [
              "CALCULATE(",
              "    [B allyear] - [A ALLyear],",
              "    FILTER( ALL( 'date' ), 'date'[jaarindex] = 0 )",
              ")"
            ],
            "expression": [
              "CALCULATE(",
              "    [B allyear] - [Besteed ALLyear],",
              "    FILTER( ALL( 'date' ), 'date'[jaarindex] = 0 )",
              ")"
            ],
            "formatString": "#,0",
            "isHidden": true,
            "displayFolder": "!YTD\\Budget\\Budget angepast aan de actuals (complex)",
            "lineageTag": "76ffd02b-9047-4e3b-a2b0-fd3433c1e46f",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ]
          },
          {
            "name": "Budget basic",
            "description": [
              "// Dit is na de A YTG de meest complexe measure",
              "// Reden: versie budget",
              "// Als je niets selecteerd, wil je automatisch de meest recente versie. Als je wel iets selecteerd, dan pak je de selectie.",
              "VAR maxversion = [B versie max]",
              "// Samen te bekijken",
              "VAR budget_standaard = [budget_hierarchy]",
              "VAR budget_calc =",
              "    CALCULATE( [budget_hierarchy], budget[versie] = maxversion )",
              "VAR if_versie =",
              "    IF(",
              "        NOT ISBLANK( SELECTEDVALUE( 'budget versie'[versie] ) ),",
              "        [budget_hierarchy],",
              "        budget_calc",
              "    )",
              "RETURN",
              "    if_versie"
            ],
            "expression": [
              "// Dit is na de A YTG de meest complexe measure",
              "// Reden: versie budget",
              "// Als je niets selecteerd, wil je automatisch de meest recente versie. Als je wel iets selecteerd, dan pak je de selectie.",
              "VAR maxversion = [B versie max] // Samen te bekijken",
              "VAR budget_standaard = [budget_hierarchy]",
              "VAR budget_calc =",
              "    CALCULATE(",
              "        [budget_hierarchy],",
              "        'fct budget'[versie] = maxversion",
              "    )",
              "VAR if_versie =",
              "    IF(",
              "        NOT ISBLANK( SELECTEDVALUE( 'budget versie'[versie] ) ),",
              "        [budget_hierarchy],",
              "        budget_calc",
              "    )",
              "RETURN",
              "    if_versie"
            ],
            "formatString": "#,##0",
            "isHidden": true,
            "displayFolder": "!YTD\\Budget\\Budget rechtstreeks uit SAP (basis)",
            "lineageTag": "c1565458-3387-4b26-afd6-4b5eb5fbd762",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "D MTD blank",
            "description": [
              "VAR filterytd = SELECTEDVALUE( switch_ytd[value], 1 )",
              "RETURN",
              "    CALCULATE(",
              "        ( [Budget] - [Actuals] ),",
              "        CALCULATETABLE( 'date', 'date'[ytd?] <= filterytd )",
              "    )"
            ],
            "expression": [
              "VAR filterytd = SELECTEDVALUE( switch_ytd[value], 1 )",
              "VAR multipl =",
              "    IF( SELECTEDVALUE( object[objecttype] ) = \"OP\", -1, 1 )",
              "VAR calc =",
              "    CALCULATE(",
              "        ( [B MTD] - [Besteed] ),",
              "        CALCULATETABLE( 'date', 'date'[ytd?] <= filterytd )",
              "    )",
              "        * multipl",
              "VAR blanco = IF( ABS( calc ) < 0.001, BLANK( ), calc )",
              "RETURN",
              "    blanco"
            ],
            "formatString": "#,##0",
            "isHidden": true,
            "displayFolder": "!YTD\\Delta",
            "lineageTag": "b3ae68f9-3d2b-4307-854f-82491cbf1e25",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "blank_column",
            "description": "BLANK( )",
            "expression": "BLANK( )",
            "formatString": "0",
            "isHidden": true,
            "displayFolder": "Varia",
            "lineageTag": "f83996a5-eb43-4017-8745-95ddf107b435",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ]
          },
          {
            "name": "Besteed ABS",
            "description": "ABS( [Actuals] )",
            "expression": "ABS( [Besteed] )",
            "isHidden": true,
            "displayFolder": "!YTD\\Besteed",
            "lineageTag": "8d1c43b7-9aa8-4c4f-ac59-e5aeea32d73c",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "0",
            "description": "0",
            "expression": "0",
            "isHidden": true,
            "displayFolder": "Varia",
            "lineageTag": "ae48a343-411f-41e4-9b1e-02c4e5788396"
          },
          {
            "name": "B YTD reset",
            "description": [
              "// de standaard YTD reset elk jaar, deze measure reset bij overgang YTD/YTG",
              "VAR LastMonthAvailable = MAX( 'date'[Year Month Number] )",
              "VAR LastYearAvailable = MAX( 'date'[Year] )",
              "VAR act = SELECTEDVALUE( 'date'[ytd?] )",
              "VAR Result =",
              "    CALCULATE(",
              "        [Budget],",
              "        REMOVEFILTERS( 'date' ),",
              "        'date'[Year Month Number] <= LastMonthAvailable,",
              "        'date'[Year] = LastYearAvailable,",
              "        'date'[ytd?] = act",
              "    )",
              "RETURN",
              "    Result"
            ],
            "expression": [
              "// de standaard YTD reset elk jaar, deze measure reset bij overgang YTD/YTG",
              "VAR LastMonthAvailable = MAX( 'date'[Year Month Number] )",
              "VAR LastYearAvailable = MAX( 'date'[Year] )",
              "VAR act = SELECTEDVALUE( 'date'[ytd?] )",
              "VAR Result =",
              "    CALCULATE(",
              "        [Budget basic],",
              "        REMOVEFILTERS( 'date' ),",
              "        'date'[Year Month Number] <= LastMonthAvailable,",
              "        'date'[Year] = LastYearAvailable,",
              "        'date'[ytd?] = act",
              "    )",
              "RETURN",
              "    Result"
            ],
            "formatString": "#,##0",
            "isHidden": true,
            "displayFolder": "!YTD\\Budget\\basic",
            "lineageTag": "fbf428c3-aaaf-45a2-bfb9-97c78435bfb7",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "B YTD og",
            "description": [
              "// Omdat er gewerkt wordt met een datumtabel om granualiteit YYYYMM kan je helaas niet met de standaard time intel functies werken",
              "// Dit zijn de uitgeschreven versies, dus zonder de \"syntax sugar\" dateytd",
              "VAR LastMonthAvailable = MAX( 'date'[Year Month Number] )",
              "VAR LastYearAvailable = MAX( 'date'[Year] )",
              "VAR Result =",
              "    CALCULATE(",
              "        [Budget],",
              "        REMOVEFILTERS( 'date' ),",
              "        'date'[Year Month Number] <= LastMonthAvailable,",
              "        'date'[Year] = LastYearAvailable",
              "    )",
              "RETURN",
              "    Result"
            ],
            "expression": [
              "// Omdat er gewerkt wordt met een datumtabel om granualiteit YYYYMM kan je helaas niet met de standaard time intel functies werken",
              "// Dit zijn de uitgeschreven versies, dus zonder de \"syntax sugar\" dateytd",
              "VAR LastMonthAvailable = MAX( 'date'[Year Month Number] )",
              "VAR LastYearAvailable = MAX( 'date'[Year] )",
              "VAR Result =",
              "    CALCULATE(",
              "        [Budget basic],",
              "        REMOVEFILTERS( 'date' ),",
              "        'date'[Year Month Number] <= LastMonthAvailable,",
              "        'date'[Year] = LastYearAvailable",
              "    )",
              "RETURN",
              "    Result"
            ],
            "formatString": "#,##0",
            "isHidden": true,
            "displayFolder": "!YTD\\Budget\\Budget angepast aan de actuals (complex)",
            "lineageTag": "61c73663-b42e-4379-a717-ce0dc2061f9e",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "B allyear",
            "description": [
              "CALCULATE(",
              "    [Budget],",
              "    REMOVEFILTERS( 'date' ),",
              "    VALUES( 'date'[Year] )",
              ")"
            ],
            "expression": [
              "CALCULATE(",
              "    SUM( 'precalc table AB'[b_dyn] ),",
              "    REMOVEFILTERS( 'date' ),",
              "    VALUES( 'date'[Year] )",
              ")"
            ],
            "formatString": "#,##0",
            "isHidden": true,
            "displayFolder": "!YTD\\Budget\\Budget angepast aan de actuals (complex)",
            "lineageTag": "0a02c5b2-5982-4005-acfe-6931bea20443",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "B YTD last",
            "description": [
              "// De maximum date van de B YTD. Komt voor in de key metrics.",
              "// Dit zijn de budget YTD tot nu toe (tot en met de afgesloten periode dus)",
              "VAR filterytd = MIN( switch_ytd[value] )",
              "RETURN",
              "    CALCULATE(",
              "        [B YTD],",
              "        FILTER( ALL( 'date' ), 'date'[ytd?] = filterytd )",
              "    )"
            ],
            "expression": [
              "// De maximum date van de B YTD. Komt voor in de key metrics.",
              "// Dit zijn de budget YTD tot nu toe (tot en met de afgesloten periode dus)",
              "VAR filterytd = MIN( switch_ytd[value] )",
              "RETURN",
              "    CALCULATE(",
              "        [B YTD og],",
              "        FILTER( ALL( 'date' ), 'date'[ytd?] = filterytd )",
              "    )"
            ],
            "formatString": "#,##0",
            "isHidden": true,
            "displayFolder": "!YTD\\Budget\\Budget angepast aan de actuals (complex)",
            "lineageTag": "5de01156-39ef-4275-b030-ef4c1bef397d",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "0nu",
            "description": [
              "VAR ytdmonth = [closing period ytd]",
              "RETURN",
              "    IF( MAX( 'date'[yyyy-mm] ) = ytdmonth, 0 )"
            ],
            "expression": [
              "VAR ytdmonth = [closing period ytd]",
              "RETURN",
              "    IF( MAX( 'date'[yyyy-mm] ) = ytdmonth, 0 )"
            ],
            "formatString": "0",
            "isHidden": true,
            "displayFolder": "Varia",
            "lineageTag": "a875cfbc-e196-43fe-ae2a-3e8286592672"
          },
          {
            "name": "yearselected",
            "description": "SELECTEDVALUE( 'date'[Year] )",
            "expression": "SELECTEDVALUE( 'date'[Year] )",
            "formatString": "0",
            "isHidden": true,
            "displayFolder": "Varia",
            "lineageTag": "a6d7fefc-00c3-4c0e-9758-7a4d9098836c"
          },
          {
            "name": "versieselected",
            "description": "SELECTEDVALUE( 'budget versie'[versie] )",
            "expression": [
              "--SELECTEDVALUE( 'budget versie'[versie] )",
              "RIGHT( MIN( 'precalc table AB'[Versie] ), 3 )"
            ],
            "isHidden": true,
            "displayFolder": "Varia",
            "lineageTag": "9691ddd3-8a9d-42df-90c9-ce8376f906a3"
          },
          {
            "name": "objecttypeselected",
            "description": "SELECTEDVALUE( object[objecttype] )",
            "expression": "SELECTEDVALUE( object[objecttype] )",
            "formatString": "0",
            "isHidden": true,
            "displayFolder": "Varia",
            "lineageTag": "67b6bba8-399b-45de-a030-e4346ce52de4"
          },
          {
            "name": "max datum report",
            "description": [
              "FORMAT(",
              "    CALCULATE( MAX( actuals[boekdatum] ), REMOVEFILTERS( ) ),",
              "    \"dd/mm/yyyy\"",
              ")"
            ],
            "expression": [
              "FORMAT(",
              "    CALCULATE(",
              "        MAX( 'fct besteed'[import_date] ),",
              "        REMOVEFILTERS( )",
              "    ),",
              "    \"dd/mm/yyyy\"",
              ")"
            ],
            "isHidden": true,
            "displayFolder": "Varia",
            "lineageTag": "8d513f0c-dbe2-4568-ad46-0f0fbd66048b",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "closing period ytd",
            "description": "MAX( importdate[yyyymm_ytd_min1] )",
            "expression": "MAX( importdate[yyyymm_ytd_min1] )",
            "isHidden": true,
            "displayFolder": "Varia",
            "lineageTag": "a93832bc-3874-4b9d-bc8c-3e57ddd740e2"
          },
          {
            "name": "closed period CF",
            "description": [
              "VAR maxperiod = MAX( importdate[yyyymm_ytd_min1] )",
              "VAR calc =",
              "    IF( SELECTEDVALUE( 'date'[yyyy-mm] ) = maxperiod, 1 )",
              "RETURN",
              "    calc"
            ],
            "expression": [
              "VAR maxperiod = MAX( importdate[yyyymm_ytd_min1] )",
              "VAR calc =",
              "    IF( SELECTEDVALUE( 'date'[yyyy-mm] ) = maxperiod, 1 )",
              "RETURN",
              "    calc"
            ],
            "formatString": "0",
            "isHidden": true,
            "displayFolder": "Varia",
            "lineageTag": "e0af8572-76f4-406c-a02c-09c8a373a6e8"
          },
          {
            "name": "bar charts CF",
            "description": "IF( ISINSCOPE( 'date'[Month] ), \"RGBA(0,0,0,0)\" )",
            "expression": "IF( ISINSCOPE( 'date'[Month] ), \"RGBA(0,0,0,0)\" )",
            "isHidden": true,
            "displayFolder": "Varia",
            "lineageTag": "a83b20e4-b61d-48ca-a987-6f7a3b9aefc5"
          },
          {
            "name": "B versie max",
            "description": [
              "// zet eerst alle filters af, vervolgens herstel je enkel de filters op een bepaald niveau, dit niveau is per jaar en per objecttype",
              "// stel dat je gewoon de max versie neemt, dan krijg je de max van alle budget records",
              "// indien er dan in het vorige jaar op een hogere versie is geïndigd dan in het huidige jaar krijg je problemen (0 values voor huidige jaar)",
              "// idem voor objecttype, want PO's werken met andere versie budget (caplan) dan KPOP (000, 001, 002, ...) en je wil dus geen PO filteren op 007 of een KPOP filteren op caplan",
              "",
              "VAR objectvar = VALUES( object[objecttype] )",
              "VAR Jaar = VALUES( 'date'[Year] )",
              "VAR MaxVersieAtGrain =",
              "    CALCULATE(",
              "        MAX( budget[versie] ),",
              "        REMOVEFILTERS( object ),",
              "        REMOVEFILTERS( soort ),",
              "        REMOVEFILTERS( 'date' ),",
              "        objectvar,",
              "        Jaar",
              "    )",
              "RETURN",
              "    MaxVersieAtGrain"
            ],
            "expression": [
              "// zet eerst alle filters af, vervolgens herstel je enkel de filters op een bepaald niveau, dit niveau is per jaar en per objecttype",
              "// stel dat je gewoon de max versie neemt, dan krijg je de max van alle budget records",
              "// indien er dan in het vorige jaar op een hogere versie is geïndigd dan in het huidige jaar krijg je problemen (0 values voor huidige jaar)",
              "// idem voor objecttype, want PO's werken met andere versie budget (caplan) dan KPOP (000, 001, 002, ...) en je wil dus geen PO filteren op 007 of een KPOP filteren op caplan",
              "VAR objectvar = VALUES( object[objecttype] )",
              "VAR Jaar = VALUES( 'date'[Year] )",
              "VAR MaxVersieAtGrain =",
              "    CALCULATE(",
              "        MAX( 'fct budget'[versie] ),",
              "        'fct budget'[versie] <> \"caplan\",",
              "        REMOVEFILTERS( object ),",
              "        REMOVEFILTERS( soort ),",
              "        REMOVEFILTERS( 'date' ),",
              "        objectvar,",
              "        Jaar",
              "    )",
              "RETURN",
              "    MaxVersieAtGrain"
            ],
            "isHidden": true,
            "displayFolder": "!YTD\\Budget\\Budget angepast aan de actuals (complex)",
            "lineageTag": "534ab0d9-f5b5-401e-bc92-a87b47a98d08",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "B #records",
            "description": "COUNTROWS( budget )",
            "expression": "COUNTROWS( 'fct budget' )",
            "formatString": "#,##0",
            "isHidden": true,
            "displayFolder": "!YTD\\Budget\\Budget angepast aan de actuals (complex)",
            "lineageTag": "c2e5ecd2-18f9-40e0-b4f2-d20bdc04f704",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "#transacties",
            "description": "COUNTROWS( actuals )",
            "expression": "COUNTROWS( 'fct besteed' )",
            "formatString": "#,0",
            "isHidden": true,
            "displayFolder": "!YTD\\Besteed",
            "lineageTag": "cf82b1f6-c2e6-44ba-891b-d7a7e4b21dfb",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "D YTD blank",
            "description": [
              "VAR filterytd = SELECTEDVALUE( switch_ytd[value], 1 )",
              "RETURN",
              "    CALCULATE(",
              "        [B YTD] - [A YTD],",
              "        CALCULATETABLE( 'date', 'date'[ytd?] <= filterytd )",
              "    )"
            ],
            "expression": [
              "VAR filterytd = SELECTEDVALUE( switch_ytd[value], 1 )",
              "VAR LastMonthAvailable = MAX( 'date'[Year Month Number] )",
              "VAR LastYearAvailable = MAX( 'date'[Year] )",
              "VAR Result =",
              "    CALCULATE(",
              "        [D MTD blank],",
              "        REMOVEFILTERS( 'date' ),",
              "        'date'[Year Month Number] <= LastMonthAvailable,",
              "        'date'[Year] = LastYearAvailable",
              "    )",
              "VAR iflogic =",
              "    IF( SELECTEDVALUE( 'date'[ytd?] ) <= filterytd, Result )",
              "RETURN",
              "    iflogic"
            ],
            "formatString": "#,0",
            "isHidden": true,
            "displayFolder": "!YTD\\Delta",
            "lineageTag": "ad0cd746-2846-4425-b117-148c563ae04b",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ]
          },
          {
            "name": "Header",
            "description": [
              "\"Year to date \" & [closing period ytd] & \", \"",
              "    & IF(",
              "        SELECTEDVALUE( switch_ytd[value] ) = 2,",
              "        \"ALL actuals\",",
              "        \"closed actuals\"",
              "    )",
              "    & \": \"",
              "    & [path min]"
            ],
            "expression": [
              "\"Year to date \" & [closing period ytd] & \", \"",
              "    & IF(",
              "        SELECTEDVALUE( switch_ytd[value] ) = 2,",
              "        \"ALL actuals\",",
              "        \"closed actuals\"",
              "    )",
              "    & \": \"",
              "    & [path min]"
            ],
            "isHidden": true,
            "displayFolder": "Varia",
            "lineageTag": "f7c2d7b9-f3fa-417e-850c-e31616502877"
          },
          {
            "name": "KPI uitleg",
            "description": [
              "\"Volgens de huidige selectie (rechtsboven) geeft kolom KPI een rode markering voor de lijnen met een BvA groter dan \"",
              "    & FORMAT( [BvA KPI value], \"#,0\" )",
              "    & \", in combinatie met een BvA% groter dan \"",
              "    & FORMAT( [BvA% KPI Value], \"Percent\" )",
              "    & \". De orangje markering komt overeen met de helft van de aangegeven waarden, dus BvA >\"",
              "    & FORMAT( [BvA KPI value] / 2, \"#,0\" )",
              "    & \" én BvA% > \"",
              "    & FORMAT( [BvA% KPI Value] / 2, \"Percent\" )",
              "    & \". Lijnen zonder symbool voldoen aan geen van beide voorwaarden en hebben een BVA <=\"",
              "    & FORMAT( [BvA KPI value] / 2, \"#,0\" )",
              "    & \" en BvA% <= \"",
              "    & FORMAT( [BvA% KPI Value] / 2, \"Percent\" )",
              "    & \". Je hebt ook de keuze om enkel de relatieve of enkel de absolute KPI te gebruiken.\""
            ],
            "expression": [
              "\"Volgens de huidige selectie (rechtsboven) geeft kolom KPI een rode markering voor de lijnen met een delta groter dan \"",
              "    & FORMAT( [BvA KPI value], \"#,0\" )",
              "    & \", in combinatie met een delta% groter dan \"",
              "    & FORMAT( [BvA% KPI Value], \"Percent\" )",
              "    & \". De orangje markering komt overeen met de helft van de aangegeven waarden, dus delta >\"",
              "    & FORMAT( [BvA KPI value] / 2, \"#,0\" )",
              "    & \" én delta% > \"",
              "    & FORMAT( [BvA% KPI Value] / 2, \"Percent\" )",
              "    & \". Lijnen zonder symbool voldoen aan geen van beide voorwaarden en hebben een delta <=\"",
              "    & FORMAT( [BvA KPI value] / 2, \"#,0\" )",
              "    & \" en delta% <= \"",
              "    & FORMAT( [BvA% KPI Value] / 2, \"Percent\" )",
              "    & \". Je hebt ook de keuze om enkel de relatieve of enkel de absolute KPI te gebruiken.\""
            ],
            "isHidden": true,
            "displayFolder": "Varia",
            "lineageTag": "e7c6de20-afaa-46b4-9827-019a63155a8d"
          },
          {
            "name": "max transaction yyyymm",
            "description": "FORMAT( MAX( actuals[boekdatum] ), \"yyyy-mm\" )",
            "expression": [
              "VAR calc =",
              "    CALCULATE(",
              "        MAX( 'fct besteed'[boekdatum] ),",
              "        'fct besteed'[a_o] = \"A\"",
              "    )",
              "VAR formatting = FORMAT( calc, \"yyyy-mm\" )",
              "RETURN",
              "    formatting"
            ],
            "isHidden": true,
            "displayFolder": "Varia",
            "lineageTag": "e75ab7c9-f862-4e19-97fe-8a91891d27a9"
          },
          {
            "name": "budget_hierarchy",
            "description": [
              "VAR budget_standaard = SUM( budget[budget] )",
              "VAR ShowRow = [BrowseDepth] <= [RowDepth]",
              "VAR parentchildhierarchy = IF( ShowRow, budget_standaard )",
              "RETURN",
              "    parentchildhierarchy"
            ],
            "expression": [
              "VAR budget_standaard = SUM( 'fct budget'[budget] )",
              "VAR ShowRow = [BrowseDepth] <= [RowDepth]",
              "VAR parentchildhierarchy = IF( ShowRow, budget_standaard )",
              "RETURN",
              "    parentchildhierarchy"
            ],
            "isHidden": true,
            "displayFolder": "!YTD\\Budget\\Budget angepast aan de actuals (complex)",
            "lineageTag": "2e408c95-96a1-4386-bd79-b5ad0b934fc4",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "max transaction today",
            "description": "FORMAT( TODAY( ), \"yyyy-mm\" )",
            "expression": "FORMAT( TODAY( ), \"yyyy-mm\" )",
            "isHidden": true,
            "displayFolder": "Varia",
            "lineageTag": "61aad77b-9094-4491-8e0f-8101d773e996"
          },
          {
            "name": "Actuals basic",
            "description": "SUM( actuals[actual] )",
            "expression": "SUM( 'fct besteed'[actual] )",
            "formatString": "#,0",
            "isHidden": true,
            "displayFolder": "!YTD\\Besteed",
            "lineageTag": "33dd4722-dd6f-4272-aaa1-78b7e8def1ef",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ]
          },
          {
            "name": "Header main",
            "description": "\"Year to date \" & [closing period ytd]",
            "expression": "\"Year to date \" & [closing period ytd]",
            "isHidden": true,
            "displayFolder": "Varia",
            "lineageTag": "d8e2295b-89a4-4435-9995-30d37e760feb"
          },
          {
            "name": "Besteed YTD doorlopend",
            "description": [
              "// Omdat er gewerkt wordt met een datumtabel om granualiteit YYYYMM kan je helaas niet met de standaard time intel functies werken",
              "// Dit zijn de uitgeschreven versies, dus zonder de \"syntax sugar\" dateytd",
              "VAR filterytd = SELECTEDVALUE( switch_ytd[value] )",
              "VAR LastMonthAvailable = MAX( 'date'[Year Month Number] )",
              "VAR LastYearAvailable = MAX( 'date'[Year] )",
              "VAR Result =",
              "    CALCULATE(",
              "        [Actuals],",
              "        REMOVEFILTERS( 'date' ),",
              "        'date'[Year Month Number] <= LastMonthAvailable,",
              "        'date'[Year] = LastYearAvailable",
              "    )",
              "VAR iflogic =",
              "    IF( SELECTEDVALUE( 'date'[ytd?] ) <= filterytd, Result )",
              "RETURN",
              "    Result"
            ],
            "expression": [
              "// Omdat er gewerkt wordt met een datumtabel om granualiteit YYYYMM kan je helaas niet met de standaard time intel functies werken",
              "// Dit zijn de uitgeschreven versies, dus zonder de \"syntax sugar\" dateytd",
              "VAR filterytd = SELECTEDVALUE( switch_ytd[value] )",
              "VAR LastMonthAvailable = MAX( 'date'[Year Month Number] )",
              "VAR LastYearAvailable = MAX( 'date'[Year] )",
              "VAR Result =",
              "    CALCULATE(",
              "        [Besteed],",
              "        REMOVEFILTERS( 'date' ),",
              "        'date'[Year Month Number] <= LastMonthAvailable,",
              "        'date'[Year] = LastYearAvailable",
              "    )",
              "VAR iflogic =",
              "    IF( SELECTEDVALUE( 'date'[ytd?] ) <= filterytd, Result )",
              "RETURN",
              "    Result"
            ],
            "formatString": "#,##0",
            "isHidden": true,
            "displayFolder": "!YTD\\Besteed",
            "lineageTag": "e77fbcbb-8faa-44ec-86f4-e10d5a23c3d0",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ]
          },
          {
            "name": "CF selectie 1m",
            "description": [
              "IF(",
              "    SELECTEDVALUE( 'date'[Month Number] )",
              "        = SELECTEDVALUE( par1_12[Parameter] ) - 1,",
              "    0",
              ")"
            ],
            "expression": [
              "IF(",
              "    SELECTEDVALUE( 'date'[Month Number] )",
              "        = SELECTEDVALUE( par1_12[Parameter] ) - 1,",
              "    0",
              ")"
            ],
            "formatString": "0",
            "isHidden": true,
            "displayFolder": "Varia",
            "lineageTag": "3f40d516-3920-4774-9dfa-e01ab139db41"
          },
          {
            "name": "A YTD kp",
            "description": [
              "// dit is een kopie, enige doel is om de bookmarks te manipuleren",
              "// je wil vanuit KP niet de optie hebben om een kostenplaats te onderzoeken op lvl3_OP",
              "// die optie kan je enkel afzetten door met afzonderlijke kopies te werken",
              "[A YTD]"
            ],
            "expression": [
              "// dit is een kopie, enige doel is om de bookmarks te manipuleren",
              "// je wil vanuit KP niet de optie hebben om een kostenplaats te onderzoeken op lvl3_OP",
              "// die optie kan je enkel afzetten door met afzonderlijke kopies te werken",
              "[Besteed YTD]"
            ],
            "formatString": "#,0",
            "isHidden": true,
            "displayFolder": "Varia",
            "lineageTag": "12ad7156-9b70-4b10-8bdd-37e6695ffc97",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ]
          },
          {
            "name": "A YTD op",
            "description": [
              "// dit is een kopie, enige doel is om de bookmarks te manipuleren",
              "// je wil vanuit KP niet de optie hebben om een kostenplaats te onderzoeken op lvl3_OP",
              "// die optie kan je enkel afzetten door met afzonderlijke kopies te werken",
              "[A YTD]"
            ],
            "expression": [
              "// dit is een kopie, enige doel is om de bookmarks te manipuleren",
              "// je wil vanuit KP niet de optie hebben om een kostenplaats te onderzoeken op lvl3_OP",
              "// die optie kan je enkel afzetten door met afzonderlijke kopies te werken",
              "[Besteed YTD]"
            ],
            "formatString": "#,0",
            "isHidden": true,
            "displayFolder": "Varia",
            "lineageTag": "81717e32-b0be-4ac7-8c69-3cefbe072458",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ]
          },
          {
            "name": "A YTD po",
            "description": [
              "// dit is een kopie, enige doel is om de bookmarks te manipuleren",
              "// je wil vanuit KP niet de optie hebben om een kostenplaats te onderzoeken op lvl3_OP",
              "// die optie kan je enkel afzetten door met afzonderlijke kopies te werken",
              "[A YTD]"
            ],
            "expression": [
              "// dit is een kopie, enige doel is om de bookmarks te manipuleren",
              "// je wil vanuit KP niet de optie hebben om een kostenplaats te onderzoeken op lvl3_OP",
              "// die optie kan je enkel afzetten door met afzonderlijke kopies te werken",
              "[Besteed YTD]"
            ],
            "formatString": "#,0",
            "isHidden": true,
            "displayFolder": "Varia",
            "lineageTag": "e1ebcf3a-7838-43b1-bfc9-d4128ad2b1da",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ]
          },
          {
            "name": "B YTG",
            "expression": "[B allyear] - [Besteed YTD]",
            "formatString": "#,0",
            "isHidden": true,
            "displayFolder": "!YTD\\Budget\\Budget angepast aan de actuals (complex)",
            "lineageTag": "24c1a54c-d783-4dea-8add-8ef0dc0a5901",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ]
          },
          {
            "name": "A left to spend parameter",
            "description": [
              "// Dit is de moeilijkste measure in het model, al is eigenljk enkel de VAR allocation factor geavanceerd",
              "// Hier wordt berekend hoeveel actuals er nog gaan uitgegeven worden, in de veronderstelling dat het volledige budget wordt opgebruikt.",
              "// De A YTG = B YTG, maar dan aangepast met een factor",
              "// Indien de actuals achterlopen, dan is deze factor > 1; lopen de actuals voor, dan is deze factor < 1",
              "// Deze factor blijft constant voor elke toekomstige maand",
              "",
              "VAR filterytd = SELECTEDVALUE( switch_ytd[value] )",
              "VAR LastAvailableDate =",
              "    CALCULATE(",
              "        MAX( actuals[yyyymm] ),",
              "        REMOVEFILTERS( 'date' ),",
              "        'date'[ytd?] = filterytd",
              "    )",
              "VAR CurrentYear = SELECTEDVALUE( 'date'[Year] )",
              "VAR CurrentActuals =",
              "    CALCULATE(",
              "        [A YTD],",
              "        FILTER( ALL( 'date' ), 'date'[ytd?] = filterytd )",
              "    )",
              "VAR CurrentBudget =",
              "    CALCULATE(",
              "        [B YTD],",
              "        FILTER( ALL( 'date' ), 'date'[ytd?] = filterytd )",
              "    )",
              "VAR BudgetMax = [B allyear]",
              "VAR AdjustmentFactor =",
              "    CALCULATE(",
              "        DIVIDE(",
              "            BudgetMax - CurrentActuals,",
              "            BudgetMax - CurrentBudget",
              "        ),",
              "        'date'[yyyy-mm] <= LastAvailableDate,",
              "        'date'[Year] = CurrentYear",
              "    )",
              "VAR Act = [A YTD]",
              "VAR ForecastedAmount =",
              "    CALCULATE(",
              "        [Budget] * AdjustmentFactor,",
              "        KEEPFILTERS( 'date'[yyyy-mm] > LastAvailableDate )",
              "    )",
              "VAR Result = Act + ForecastedAmount",
              "// wordt hier niet gebruikt, dit is voornamelijk voor de grafieken",
              "RETURN",
              "    ForecastedAmount"
            ],
            "expression": [
              "// Dit is de moeilijkste measure in het model, al is eigenljk enkel de VAR allocation factor geavanceerd",
              "// Hier wordt berekend hoeveel actuals er nog gaan uitgegeven worden, in de veronderstelling dat het volledige budget wordt opgebruikt.",
              "// De A YTG = B YTG, maar dan aangepast met een factor",
              "// Indien de actuals achterlopen, dan is deze factor > 1; lopen de actuals voor, dan is deze factor < 1",
              "// Deze factor blijft constant voor elke toekomstige maand",
              "VAR CurrentYear = SELECTEDVALUE( 'date'[Year] )",
              "VAR SelectMonth = [Parameter Value] --VAR FilterYYYYMM = CALCULATE(MAX('date'[yyyy-mm]), 'date'[Year] = CurrentYear, 'date'[Month Number] = SelectMonth)",
              "VAR SelectYYYYMM =",
              "    CALCULATE(",
              "        MAX( 'fct besteed'[yyyymm] ),",
              "        REMOVEFILTERS( 'date' ),",
              "        'date'[Year] = CurrentYear,",
              "        'date'[Month Number] = SelectMonth",
              "    ) -- VAR CurrentYear = SELECTEDVALUE( 'date'[Year] )",
              "VAR CurrentActuals =",
              "    CALCULATE(",
              "        [Besteed YTD],",
              "        REMOVEFILTERS( 'date' ),",
              "        'date'[yyyy-mm] = SelectYYYYMM",
              "    )",
              "VAR CurrentBudget =",
              "    CALCULATE(",
              "        [B YTD og],",
              "        REMOVEFILTERS( 'date' ),",
              "        'date'[yyyy-mm] = SelectYYYYMM",
              "    )",
              "VAR BudgetMax = [B allyear]",
              "VAR AdjustmentFactor =",
              "    DIVIDE(",
              "        BudgetMax - CurrentActuals,",
              "        BudgetMax - CurrentBudget",
              "    )",
              "VAR Act = [Besteed YTD]",
              "VAR ForecastedAmount =",
              "    CALCULATE(",
              "        [Budget basic] * AdjustmentFactor,",
              "        KEEPFILTERS( 'date'[yyyy-mm] > SelectYYYYMM )",
              "    )",
              "VAR Result = Act + ForecastedAmount // wordt hier niet gebruikt, dit is voornamelijk voor de grafieken",
              "RETURN",
              "    ForecastedAmount"
            ],
            "isHidden": true,
            "displayFolder": "!YTD\\Budget\\Budget angepast aan de actuals (complex)",
            "lineageTag": "7ece7706-c43a-460f-9d0d-5c8ead43d0f5",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Budget",
            "expression": "SUM( 'fct budget'[budget] )",
            "formatString": "#,0",
            "isHidden": true,
            "displayFolder": "!YTD\\Budget\\Budget rechtstreeks uit SAP (basis)",
            "lineageTag": "234c4772-a5da-4f3c-9ded-7758c05f649a",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "Budget dynamisch YTD",
            "expression": [
              "// Omdat er gewerkt wordt met een datumtabel om granualiteit YYYYMM kan je helaas niet met de standaard time intel functies werken",
              "// Dit zijn de uitgeschreven versies, dus zonder de \"syntax sugar\" dateytd",
              "VAR LastMonthAvailable = MAX( 'date'[Year Month Number] )",
              "VAR LastYearAvailable = MAX( 'date'[Year] )",
              "VAR Result =",
              "    CALCULATE(",
              "        [Budget],",
              "        REMOVEFILTERS( 'date' ),",
              "        'date'[Year Month Number] <= LastMonthAvailable,",
              "        'date'[Year] = LastYearAvailable",
              "    )",
              "RETURN",
              "    Result"
            ],
            "formatString": "#,0",
            "isHidden": true,
            "displayFolder": "!YTD\\Budget\\Budget angepast aan de actuals (complex)",
            "lineageTag": "ace945c5-87d2-46f0-8374-23a791c9be38",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ]
          },
          {
            "name": "Budget dynamisch last",
            "expression": [
              "// De maximum date van de B YTD. Komt voor in de key metrics.",
              "// Dit zijn de budget YTD tot nu toe (tot en met de afgesloten periode dus)",
              "VAR filterytd = MIN( switch_ytd[value] )",
              "RETURN",
              "    CALCULATE(",
              "        [Budget dynamisch YTD],",
              "        FILTER( ALL( 'date' ), 'date'[ytd?] = filterytd )",
              "    )"
            ],
            "isHidden": true,
            "displayFolder": "!YTD\\Budget\\Budget angepast aan de actuals (complex)",
            "lineageTag": "2bcb32d8-e8b1-4586-b488-458b633c9f04",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "obligo",
            "expression": [
              "",
              "-- keuzeknop: enkel closed actuals of alle actuals + obligo's",
              "VAR filterytd = SELECTEDVALUE( switch_ytd[value], 1 )",
              "-- parent child hierarchy van dim object, je wil geen lege rijen tonen in de matrix",
              "VAR ShowRow =",
              "    OR(",
              "        [BrowseDepth] <= [RowDepth],",
              "        ISINSCOPE( 'dim resultatenrekening'[soort+beschrijving] )",
              "    )",
              "VAR actualsytd =",
              "    CALCULATE(",
              "        IF( ShowRow, SUM( 'fct besteed'[obligo] ) ),",
              "        CALCULATETABLE( 'date', 'date'[ytd?] <= filterytd )",
              "    )",
              "RETURN",
              "    actualsytd"
            ],
            "formatString": "#,0",
            "isHidden": true,
            "displayFolder": "!YTD\\Besteed",
            "lineageTag": "c8241f33-c347-4e49-95ae-c62204eed415",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ]
          },
          {
            "name": "laatste update",
            "expression": "SELECTEDVALUE( 'Tab now'[Datum] )",
            "formatString": "Short Date",
            "isHidden": true,
            "displayFolder": "Varia",
            "lineageTag": "9ca74184-10b4-4cb4-b985-705e0feb1cb5"
          },
          {
            "name": "gew. budget",
            "expression": "[B allyear]",
            "formatString": "#,0",
            "isHidden": true,
            "displayFolder": "!YTD\\Budget",
            "lineageTag": "812f183a-9ff6-42f1-8a6a-ecda6db121b7",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ]
          },
          {
            "name": "werkelijk",
            "expression": "[Actuals]",
            "formatString": "#,0",
            "isHidden": true,
            "displayFolder": "!YTD\\Besteed",
            "lineageTag": "055600e2-f2dc-414f-bc14-7c434b20dbb2",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ]
          },
          {
            "name": "B allyear ss",
            "expression": [
              "-- opgelet je gebruikt hier niet budget Dyn maar het oorspronkelijke budget",
              "-- reden: budget dyn neemt toe in het geval er actuals zijn zonder budget (het budget past zich aan aan deze actuals)",
              "CALCULATE(",
              "    SUM( 'precalc table AB'[b_og] ),",
              "    REMOVEFILTERS( 'date' ),",
              "    VALUES( 'date'[Year] )",
              ")"
            ],
            "formatString": "#,##0",
            "isHidden": true,
            "displayFolder": "!YTD\\Budget\\Budget angepast aan de actuals (complex)",
            "lineageTag": "d01b2d98-d084-46e1-8777-abbebde93d0c",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "B MTD",
            "expression": [
              "VAR par = SELECTEDVALUE( par1_12[Parameter], 1 )",
              "VAR incpar =",
              "    CALCULATE(",
              "        SUM( 'precalc table AB'[b_dyn] ),",
              "        par1_12[Parameter] = par",
              "    )",
              "RETURN",
              "    incpar"
            ],
            "formatString": "#,##0",
            "isHidden": true,
            "displayFolder": "!YTD\\Budget\\Budget angepast aan de actuals (complex)",
            "lineageTag": "af853bdd-adf8-42e1-87e0-6c80cbbdbf71",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "B YTD",
            "expression": [
              "VAR filterytd = SELECTEDVALUE( switch_ytd[value], 1 )",
              "VAR LastMonthAvailable = MAX( 'date'[Year Month Number] )",
              "VAR LastYearAvailable = MAX( 'date'[Year] )",
              "VAR Result =",
              "    CALCULATE(",
              "        [B MTD],",
              "        REMOVEFILTERS( 'date' ),",
              "        'date'[Year Month Number] <= LastMonthAvailable,",
              "        'date'[Year] = LastYearAvailable",
              "    )",
              "VAR iflogic =",
              "    IF( SELECTEDVALUE( 'date'[ytd?] ) <= filterytd, Result )",
              "RETURN",
              "    Result"
            ],
            "formatString": "#,##0",
            "isHidden": true,
            "displayFolder": "!YTD\\Budget\\Budget angepast aan de actuals (complex)",
            "lineageTag": "54f597ce-d19a-4f62-b3e4-a02484b1a17b",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "B YTD ss",
            "expression": [
              "",
              "VAR ShowRow =",
              "    OR(",
              "        [BrowseDepth] <= [RowDepth],",
              "        ISINSCOPE( 'dim resultatenrekening'[soort+beschrijving] )",
              "    )",
              "VAR filterytd = MIN( switch_ytd[value] )",
              "VAR calc =",
              "    IF(",
              "        ShowRow,",
              "        IF(",
              "            ISFILTERED( 'date'[yyyy-mm] ) || ISFILTERED( 'date'[Month] )",
              "                || ISFILTERED( 'date'[Month Number] ),",
              "            [B MTD],",
              "            CALCULATE(",
              "                [B YTD],",
              "                FILTER(",
              "                    ALLEXCEPT( 'date', 'date'[Year] ),",
              "                    'date'[ytd?] <= filterytd",
              "                )",
              "            )",
              "        -- CALCULATE ( [B YTD], FILTER ( ALL ( 'date' ), 'date'[ytd?] = filterytd ) )",
              "        )",
              "    )",
              "RETURN",
              "    calc"
            ],
            "formatString": "#,##0",
            "isHidden": true,
            "displayFolder": "!YTD\\Budget\\Budget angepast aan de actuals (complex)",
            "lineageTag": "a2e0ba14-5418-4be7-badd-b4f9fe7a0318",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "D MTD y",
            "description": [
              "VAR filterytd = SELECTEDVALUE( switch_ytd[value], 1 )",
              "RETURN",
              "    CALCULATE(",
              "        ( [Budget] - [Actuals] ),",
              "        CALCULATETABLE( 'date', 'date'[ytd?] <= filterytd )",
              "    )"
            ],
            "expression": [
              "",
              "VAR filterytd = SELECTEDVALUE( switch_ytd[value], 1 )",
              "VAR multipl =",
              "    IF( SELECTEDVALUE( object[objecttype] ) = \"OP\", -1, 1 )",
              "VAR ShowRow =",
              "    OR(",
              "        [BrowseDepth] <= [RowDepth],",
              "        ISINSCOPE( 'dim resultatenrekening'[soort+beschrijving] )",
              "    )",
              "VAR calc = ( [B MTD] - [Besteed] ) * multipl",
              "VAR blanco = IF( ABS( calc ) < 0.001, BLANK( ), calc )",
              "RETURN",
              "    blanco"
            ],
            "formatString": "#,##0",
            "isHidden": true,
            "displayFolder": "!YTD\\Delta",
            "lineageTag": "36ec9eca-31be-40f9-a748-890aefaa53f5",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "D YTD y",
            "description": [
              "VAR filterytd = SELECTEDVALUE( switch_ytd[value], 1 )",
              "RETURN",
              "    CALCULATE(",
              "        ( [Budget] - [Actuals] ),",
              "        CALCULATETABLE( 'date', 'date'[ytd?] <= filterytd )",
              "    )"
            ],
            "expression": [
              "VAR filterytd = SELECTEDVALUE( switch_ytd[value], 1 )",
              "VAR LastMonthAvailable = MAX( 'date'[Year Month Number] )",
              "VAR LastYearAvailable = MAX( 'date'[Year] )",
              "VAR Result =",
              "    CALCULATE(",
              "        [D MTD y],",
              "        REMOVEFILTERS( 'date' ),",
              "        'date'[Year Month Number] <= LastMonthAvailable,",
              "        'date'[Year] = LastYearAvailable",
              "    )",
              "VAR iflogic =",
              "    IF( SELECTEDVALUE( 'date'[ytd?] ) <= filterytd, Result )",
              "RETURN",
              "    Result"
            ],
            "formatString": "#,##0",
            "isHidden": true,
            "displayFolder": "!YTD\\Delta",
            "lineageTag": "2dcaa71c-85d6-4af3-a185-e6d6b5712ce6",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Besteed YTG ss",
            "expression": [
              "VAR _iflogica =",
              "    IF(",
              "        MAX( 'date'[Year] ) = YEAR( MAX( importdate[yyyymm_ytd] ) ),",
              "        1",
              "    )",
              "VAR _calc = [B allyear] - [Besteed YTD ss]",
              "VAR _result =",
              "    IF(",
              "        MAX( 'date'[Year] ) = YEAR( MAX( importdate[yyyymm_ytd] ) ),",
              "        _calc",
              "    )",
              "RETURN",
              "    _result"
            ],
            "formatString": "#,##0",
            "isHidden": true,
            "displayFolder": "!YTD\\Besteed",
            "lineageTag": "ab52a22c-feb4-43cc-ae9a-6a77a8181ed6",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Budget+eindejaarscorrectie",
            "expression": [
              "VAR multipl =",
              "    IF( SELECTEDVALUE( object[objecttype] ) = \"OP\", -1, 1 )",
              "VAR filterytd = MIN( switch_ytd[value] )",
              "VAR delta =",
              "    CALCULATE(",
              "        [D YTD blank],",
              "        FILTER( ALL( 'date' ), 'date'[ytd?] = filterytd )",
              "    )",
              "RETURN",
              "    IF(",
              "        MAX( 'date'[Fiscal Month Number] ) = 12,",
              "        [B MTD 0] + delta * multipl",
              "    )"
            ],
            "formatString": "#,##0",
            "isHidden": true,
            "displayFolder": "!YTD\\Budget\\Budget angepast aan de actuals (complex)",
            "lineageTag": "50c41971-ddd5-4e11-825e-39dceddb0baf",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Besteed YTD noblank",
            "description": [
              "// Omdat er gewerkt wordt met een datumtabel om granualiteit YYYYMM kan je helaas niet met de standaard time intel functies werken",
              "// Dit zijn de uitgeschreven versies, dus zonder de \"syntax sugar\" dateytd",
              "VAR filterytd = SELECTEDVALUE( switch_ytd[value], 1 )",
              "VAR LastMonthAvailable = MAX( 'date'[Year Month Number] )",
              "VAR LastYearAvailable = MAX( 'date'[Year] )",
              "VAR Result =",
              "    CALCULATE(",
              "        [Actuals],",
              "        REMOVEFILTERS( 'date' ),",
              "        'date'[Year Month Number] <= LastMonthAvailable,",
              "        'date'[Year] = LastYearAvailable",
              "    )",
              "VAR iflogic =",
              "    IF( SELECTEDVALUE( 'date'[ytd?] ) <= filterytd, Result )",
              "RETURN",
              "    iflogic"
            ],
            "expression": [
              "// Omdat er gewerkt wordt met een datumtabel om granualiteit YYYYMM kan je helaas niet met de standaard time intel functies werken",
              "// Dit zijn de uitgeschreven versies, dus zonder de \"syntax sugar\" dateytd",
              "VAR filterytd = SELECTEDVALUE( switch_ytd[value], 1 )",
              "VAR LastMonthAvailable = MAX( 'date'[Year Month Number] )",
              "VAR LastYearAvailable = MAX( 'date'[Year] )",
              "VAR Result =",
              "    CALCULATE(",
              "        [Besteed],",
              "        REMOVEFILTERS( 'date' ),",
              "        'date'[Year Month Number] <= LastMonthAvailable,",
              "        'date'[Year] = LastYearAvailable",
              "    )",
              "VAR iflogic =",
              "    IF( SELECTEDVALUE( 'date'[ytd?] ) <= filterytd, Result )",
              "RETURN",
              "    Result"
            ],
            "formatString": "#,##0",
            "isHidden": true,
            "displayFolder": "!YTD\\Besteed",
            "lineageTag": "eb1598ca-8905-4c1b-a847-33fc9d1f33b6",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ]
          },
          {
            "name": "Besteed YTD ss",
            "expression": [
              "VAR filterytd = MIN( switch_ytd[value] )",
              "RETURN",
              "    IF(",
              "        ISFILTERED( 'date'[yyyy-mm] ) || ISFILTERED( 'date'[Month] )",
              "            || ISFILTERED( 'date'[Month Number] ),",
              "        [Besteed],",
              "        CALCULATE(",
              "            [Besteed YTD],",
              "            -- FILTER( ALL( 'date' ), 'date'[ytd?] = filterytd )",
              "            FILTER(",
              "                ALLEXCEPT( 'date', 'date'[Year] ),",
              "                'date'[ytd?] <= filterytd",
              "            )",
              "        )",
              "    )"
            ],
            "formatString": "#,##0",
            "isHidden": true,
            "displayFolder": "!YTD\\Besteed",
            "lineageTag": "c550f3ba-9007-40b7-81cf-4d026f68a854",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "D YTD ss",
            "expression": [
              "",
              "VAR ShowRow =",
              "    OR(",
              "        [BrowseDepth] <= [RowDepth],",
              "        ISINSCOPE( 'dim resultatenrekening'[soort+beschrijving] )",
              "    )",
              "VAR filterytd = MIN( switch_ytd[value] )",
              "VAR calc =",
              "    IF(",
              "        ShowRow,",
              "        IF(",
              "            ISFILTERED( 'date'[yyyy-mm] ) || ISFILTERED( 'date'[Month] )",
              "                || ISFILTERED( 'date'[Month Number] ),",
              "            [D MTD blank],",
              "            CALCULATE(",
              "                [D YTD blank],",
              "                FILTER(",
              "                    ALLEXCEPT( 'date', 'date'[Year] ),",
              "                    'date'[ytd?] <= filterytd",
              "                )",
              "            )",
              "        )",
              "    )",
              "RETURN",
              "    calc"
            ],
            "formatString": "#,##0",
            "isHidden": true,
            "displayFolder": "!YTD\\Delta",
            "lineageTag": "6648b9bd-f306-4105-94c1-d4e9c0420b03",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "D% YTD ss",
            "expression": [
              "VAR filterytd = MIN( switch_ytd[value] )",
              "VAR calc =",
              "    IF(",
              "        ISFILTERED( 'date'[yyyy-mm] ) || ISFILTERED( 'date'[Month] )",
              "            || ISFILTERED( 'date'[Month Number] ),",
              "        DIVIDE( [D MTD blank], [B MTD] ),",
              "        CALCULATE(",
              "            DIVIDE( [D YTD ss], [B YTD ss] ),",
              "            FILTER( ALL( 'date' ), 'date'[ytd?] = filterytd )",
              "        )",
              "    )",
              "RETURN",
              "    DIVIDE( [D YTD ss], [B YTD ss] )"
            ],
            "formatString": "#,##0.00 %",
            "isHidden": true,
            "displayFolder": "!YTD\\Delta",
            "lineageTag": "18a7e95e-3972-4cd2-8b13-065d59f54b4c",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "B MTD 0",
            "expression": [
              "",
              "-- always return 0 instead of blank, for purpose in graphs: error bars only apply to a value, not blanks",
              "VAR budgetb = SUM( 'precalc table AB'[b_dyn] )",
              "VAR maxversion = [B versie max]",
              "VAR budget_calc =",
              "    CALCULATE(",
              "        SUM( 'precalc table AB'[b_dyn] ),",
              "        'budget versie'[versie] = maxversion",
              "    )",
              "VAR if_versie =",
              "    IF(",
              "        NOT ISBLANK( SELECTEDVALUE( 'budget versie'[versie] ) ),",
              "        budgetb,",
              "        budget_calc",
              "    )",
              "VAR ShowRow =",
              "    OR(",
              "        [BrowseDepth] <= [RowDepth],",
              "        ISINSCOPE( 'dim resultatenrekening'[soort+beschrijving] )",
              "    )",
              "VAR actualsytd = IF( ShowRow, if_versie )",
              "VAR blancos = IF( ISBLANK( actualsytd ), 0, actualsytd )",
              "RETURN",
              "    blancos"
            ],
            "isHidden": true,
            "displayFolder": "!YTD\\Budget\\Budget angepast aan de actuals (complex)",
            "lineageTag": "2d121e52-f8fc-4e21-8135-53e18a1f004f",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "B YTD blank",
            "expression": [
              "-- if you want to use it in a graph",
              "VAR filterytd = SELECTEDVALUE( switch_ytd[value], 1 )",
              "VAR LastMonthAvailable = MAX( 'date'[Year Month Number] )",
              "VAR LastYearAvailable = MAX( 'date'[Year] )",
              "VAR Result =",
              "    CALCULATE(",
              "        [B MTD],",
              "        REMOVEFILTERS( 'date' ),",
              "        'date'[Year Month Number] <= LastMonthAvailable,",
              "        'date'[Year] = LastYearAvailable",
              "    )",
              "VAR iflogic =",
              "    IF( SELECTEDVALUE( 'date'[ytd?] ) <= filterytd, Result )",
              "RETURN",
              "    iflogic"
            ],
            "isHidden": true,
            "displayFolder": "!YTD\\Budget\\Budget angepast aan de actuals (complex)",
            "lineageTag": "286723eb-b1b1-474c-9032-1c7cf9a57247",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "test herverdeling budget",
            "expression": [
              "VAR filterytd = SELECTEDVALUE( switch_ytd[value], 1 )",
              "VAR restmaand =",
              "    CALCULATE(",
              "        CALCULATE(",
              "            COUNT( 'date'[yyyy-mm] ),",
              "            'date'[ytd?] > filterytd,",
              "            'date'[Year] = 2022",
              "        ),",
              "        REMOVEFILTERS( )",
              "    )",
              "VAR budgetprop = DIVIDE( [D YTD ss all], restmaand )",
              "VAR calc =",
              "    IF(",
              "        SELECTEDVALUE( 'date'[ytd?] ) > filterytd,",
              "        budgetprop + [B MTD 0]",
              "    )",
              "RETURN",
              "    calc"
            ],
            "isHidden": true,
            "displayFolder": "Varia",
            "lineageTag": "31c1f8f8-0bb0-4c39-b952-3867038fd4d4",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "D YTD ss all",
            "expression": [
              "VAR filterytd = MIN( switch_ytd[value] )",
              "RETURN",
              "    CALCULATE(",
              "        [D YTD blank],",
              "        FILTER( ALL( 'date' ), 'date'[ytd?] = filterytd )",
              "    )"
            ],
            "isHidden": true,
            "displayFolder": "!YTD\\Delta",
            "lineageTag": "a13c3105-b848-490c-b468-24d3b6156735",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "%obligo cf",
            "expression": "DIVIDE( [obligo], [Besteed], 0 )",
            "isHidden": true,
            "displayFolder": "!YTD\\Budget",
            "lineageTag": "7970bd81-787f-4de5-b931-35cf2e2dc558",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "%obligo",
            "expression": [
              "VAR deling = DIVIDE( [obligo], [Besteed] ) -- [obligo]/[A MTD]",
              "VAR iflogic = IF( ISBLANK( deling ), 0, deling )",
              "RETURN",
              "    iflogic"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "displayFolder": "!YTD\\Besteed",
            "lineageTag": "4adef6da-d783-4610-8ef9-4d7f9e6b1ca0"
          },
          {
            "name": "Actuals",
            "expression": [
              "",
              "VAR filterytd = SELECTEDVALUE( switch_ytd[value], 1 )",
              "VAR ShowRow =",
              "    OR(",
              "        [BrowseDepth] <= [RowDepth],",
              "        ISINSCOPE( 'dim resultatenrekening'[soort+beschrijving] )",
              "    )",
              "VAR actualsytd =",
              "    CALCULATE(",
              "        IF( ShowRow, [Actuals basic] ),",
              "        CALCULATETABLE( 'date', 'date'[ytd?] <= filterytd )",
              "    )",
              "RETURN",
              "    actualsytd"
            ],
            "formatString": "#,0",
            "isHidden": true,
            "displayFolder": "!YTD\\Besteed",
            "lineageTag": "cec18ad3-19b6-4ff0-8511-67b701a43d23",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ]
          },
          {
            "name": "B YTD ss all",
            "expression": [
              "VAR filterytd = MIN( switch_ytd[value] )",
              "RETURN",
              "    CALCULATE(",
              "        [B YTD],",
              "        FILTER( ALL( 'date' ), 'date'[ytd?] = filterytd )",
              "    )"
            ],
            "formatString": "#,##0",
            "isHidden": true,
            "displayFolder": "!YTD\\Budget\\Budget angepast aan de actuals (complex)",
            "lineageTag": "a624717e-f9f1-487d-93df-6779a0ef3d95",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "D MTD blank 0",
            "description": [
              "VAR filterytd = SELECTEDVALUE( switch_ytd[value], 1 )",
              "RETURN",
              "    CALCULATE(",
              "        ( [Budget] - [Actuals] ),",
              "        CALCULATETABLE( 'date', 'date'[ytd?] <= filterytd )",
              "    )"
            ],
            "expression": [
              "VAR filterytd = SELECTEDVALUE( switch_ytd[value], 1 )",
              "VAR multipl =",
              "    IF( SELECTEDVALUE( object[objecttype] ) = \"OP\", -1, 1 )",
              "VAR calc =",
              "    CALCULATE(",
              "        ( [B MTD] - [Besteed] ),",
              "        CALCULATETABLE( 'date', 'date'[ytd?] <= filterytd )",
              "    )",
              "        * multipl",
              "VAR blanco = IF( ABS( calc ) < 0.001, 0, calc )",
              "RETURN",
              "    calc"
            ],
            "formatString": "#,##0",
            "isHidden": true,
            "displayFolder": "!YTD\\Delta",
            "lineageTag": "9dcd6bfa-6dcf-4db1-bf60-790b86532707",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "D YTD blank 0",
            "description": [
              "VAR filterytd = SELECTEDVALUE( switch_ytd[value], 1 )",
              "RETURN",
              "    CALCULATE(",
              "        [B YTD] - [A YTD],",
              "        CALCULATETABLE( 'date', 'date'[ytd?] <= filterytd )",
              "    )"
            ],
            "expression": [
              "VAR filterytd = SELECTEDVALUE( switch_ytd[value], 1 )",
              "VAR LastMonthAvailable = MAX( 'date'[Year Month Number] )",
              "VAR LastYearAvailable = MAX( 'date'[Year] )",
              "VAR Result =",
              "    CALCULATE(",
              "        [D MTD blank 0],",
              "        REMOVEFILTERS( 'date' ),",
              "        'date'[Year Month Number] <= LastMonthAvailable,",
              "        'date'[Year] = LastYearAvailable",
              "    )",
              "VAR iflogic =",
              "    IF( SELECTEDVALUE( 'date'[ytd?] ) <= filterytd, Result )",
              "RETURN",
              "    iflogic"
            ],
            "formatString": "#,0",
            "isHidden": true,
            "displayFolder": "!YTD\\Delta",
            "lineageTag": "de6649f4-943d-40ff-b531-071badb4951c",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ]
          },
          {
            "name": "Y as schaal",
            "description": [
              "// dit is een kopie, enige doel is om de bookmarks te manipuleren",
              "// je wil vanuit KP niet de optie hebben om een kostenplaats te onderzoeken op lvl3_OP",
              "// die optie kan je enkel afzetten door met afzonderlijke kopies te werken",
              "[A YTD]"
            ],
            "expression": [
              "VAR B = [B allyear]",
              "VAR A = ABS( [D YTD ss all] ) + [obligo] + [Actuals basic]",
              "VAR iflogic = IF( B > A, B, A ) * 1.1",
              "RETURN",
              "    iflogic"
            ],
            "formatString": "#,0",
            "isHidden": true,
            "displayFolder": "Varia",
            "lineageTag": "2debe576-98d5-4072-8c2c-7870f551fc29",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ]
          },
          {
            "name": "test schaal",
            "expression": [
              "--([B allyear]+abs([D YTD ss all])+[obligo])",
              "VAR B = [B allyear]",
              "VAR A = ABS( [D YTD ss all] ) + [obligo] + [Actuals basic]",
              "VAR iflogic = IF( B > A, B, A ) * 1.1",
              "RETURN",
              "    iflogic"
            ],
            "isHidden": true,
            "displayFolder": "Varia",
            "lineageTag": "01461943-1cc2-4a10-b7d6-dc38856ba892",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "obligo YTD",
            "expression": [
              "VAR filterytd = SELECTEDVALUE( switch_ytd[value], 1 )",
              "VAR LastMonthAvailable = MAX( 'date'[Year Month Number] )",
              "VAR LastYearAvailable = MAX( 'date'[Year] )",
              "VAR Result =",
              "    CALCULATE(",
              "        [obligo],",
              "        REMOVEFILTERS( 'date' ),",
              "        'date'[Year Month Number] <= LastMonthAvailable,",
              "        'date'[Year] = LastYearAvailable",
              "    )",
              "VAR iflogic =",
              "    IF( SELECTEDVALUE( 'date'[ytd?] ) <= filterytd, Result )",
              "RETURN",
              "    iflogic"
            ],
            "formatString": "#,0",
            "isHidden": true,
            "displayFolder": "!YTD\\Besteed",
            "lineageTag": "a610e80b-4df6-48b9-8d5a-dddf30a5e468",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ]
          },
          {
            "name": "Actuals YTD",
            "expression": [
              "VAR filterytd = SELECTEDVALUE( switch_ytd[value], 1 )",
              "VAR LastMonthAvailable = MAX( 'date'[Year Month Number] )",
              "VAR LastYearAvailable = MAX( 'date'[Year] )",
              "VAR Result =",
              "    CALCULATE(",
              "        [Actuals],",
              "        REMOVEFILTERS( 'date' ),",
              "        'date'[Year Month Number] <= LastMonthAvailable,",
              "        'date'[Year] = LastYearAvailable",
              "    )",
              "VAR iflogic =",
              "    IF( SELECTEDVALUE( 'date'[ytd?] ) <= filterytd, Result )",
              "RETURN",
              "    iflogic"
            ],
            "formatString": "#,0",
            "isHidden": true,
            "displayFolder": "!YTD\\Besteed",
            "lineageTag": "e4d587e5-c60a-4ad3-8b67-b409ce26504e",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ]
          },
          {
            "name": "blank obligo graph",
            "expression": "IF( [Besteed YTD] > [Actuals YTD], [Besteed YTD] )",
            "isHidden": true,
            "displayFolder": "!YTD\\Besteed",
            "lineageTag": "62869ac2-850a-4784-8862-7d749ae7aec7",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "D YTD ss all ytd graph",
            "expression": [
              "VAR filterytd = MIN( switch_ytd[value] )",
              "VAR closed =",
              "    IF(",
              "        SELECTEDVALUE( 'date'[yyyy-mm] ) = [closing period ytd],",
              "        CALCULATE(",
              "            [D YTD ss all og],",
              "            FILTER( ALL( 'date' ), 'date'[ytd?] = filterytd )",
              "        )",
              "    )",
              "VAR allperiod =",
              "    IF(",
              "        SELECTEDVALUE( 'date'[Month Number] ) = 12,",
              "        CALCULATE(",
              "            [D YTD ss all og],",
              "            FILTER( ALL( 'date' ), 'date'[ytd?] = filterytd )",
              "        )",
              "    )",
              "VAR switcheroo = IF( filterytd = 1, closed, allperiod )",
              "RETURN",
              "    switcheroo"
            ],
            "formatString": "#,##0",
            "isHidden": true,
            "displayFolder": "!YTD\\Delta",
            "lineageTag": "3c631a24-6699-45d4-897e-375e8f774106",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "D% YTD ss yearb",
            "expression": "DIVIDE( [D YTD ss], [B YTD ss] )",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "displayFolder": "!YTD\\Delta",
            "lineageTag": "cbb2f98c-6a46-465e-a42a-9ad693164cc0"
          },
          {
            "name": "D MTD blank og",
            "expression": [
              "VAR filterytd = SELECTEDVALUE( switch_ytd[value], 1 )",
              "VAR calc =",
              "    CALCULATE(",
              "        ( [B MTD] - [Besteed] ),",
              "        CALCULATETABLE( 'date', 'date'[ytd?] <= filterytd )",
              "    )",
              "VAR blanco = IF( ABS( calc ) < 0.001, BLANK( ), calc )",
              "RETURN",
              "    blanco"
            ],
            "isHidden": true,
            "displayFolder": "!YTD\\Delta",
            "lineageTag": "0684c2ca-565e-4b59-a95c-4b0f70f4de4f",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "D YTD blank og",
            "expression": [
              "VAR filterytd = SELECTEDVALUE( switch_ytd[value], 1 )",
              "VAR LastMonthAvailable = MAX( 'date'[Year Month Number] )",
              "VAR LastYearAvailable = MAX( 'date'[Year] )",
              "VAR Result =",
              "    CALCULATE(",
              "        [D MTD blank og],",
              "        REMOVEFILTERS( 'date' ),",
              "        'date'[Year Month Number] <= LastMonthAvailable,",
              "        'date'[Year] = LastYearAvailable",
              "    )",
              "VAR iflogic =",
              "    IF( SELECTEDVALUE( 'date'[ytd?] ) <= filterytd, Result )",
              "RETURN",
              "    iflogic"
            ],
            "isHidden": true,
            "displayFolder": "!YTD\\Delta",
            "lineageTag": "de86efb6-f446-448e-8d00-830a2263008a",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "D YTD ss all og",
            "expression": [
              "VAR filterytd = MIN( switch_ytd[value] )",
              "RETURN",
              "    CALCULATE(",
              "        [D YTD blank og],",
              "        FILTER( ALL( 'date' ), 'date'[ytd?] = filterytd )",
              "    )"
            ],
            "isHidden": true,
            "displayFolder": "!YTD\\Delta",
            "lineageTag": "2b06a6cf-813d-4cdd-bb91-c6f05bd5faca",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "obligo basic",
            "expression": "SUM( 'fct besteed'[obligo] )",
            "formatString": "#,0",
            "isHidden": true,
            "displayFolder": "!YTD\\Besteed",
            "lineageTag": "549cade0-750b-42b5-a36b-04eeac6d0bb6",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ]
          },
          {
            "name": "max month current year (2022-12)",
            "expression": "COMBINEVALUES( \"-\", YEAR( TODAY( ) ), \"12\" )",
            "isHidden": true,
            "displayFolder": "Varia",
            "lineageTag": "0a3bb3b3-7530-4ca5-99fa-a5a2373b6cb8"
          },
          {
            "name": "ytdfilter",
            "expression": [
              "VAR filterytd = SELECTEDVALUE( switch_ytd[value], 1 )",
              "VAR _max = MAX( 'date'[ytd?] )",
              "VAR _calc =",
              "    CALCULATE(",
              "        MAX( 'date'[Year Month Key] ),",
              "        REMOVEFILTERS( 'date' ),",
              "        'date'[ytd?] = 1 -- filterytd",
              "    )",
              "VAR _format = LEFT( _calc, 4 )",
              "RETURN",
              "    _calc"
            ],
            "isHidden": true,
            "displayFolder": "Varia",
            "lineageTag": "00af179e-4093-4e9a-81e4-0c281dd4f733",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "max transaction yyyymmdd",
            "expression": [
              "VAR calc =",
              "    CALCULATE(",
              "        MAX( 'fct besteed'[boekdatum] ),",
              "        'fct besteed'[a_o] = \"A\"",
              "    )",
              "VAR formatting = FORMAT( calc, \"dd/mm/yyyy\" )",
              "RETURN",
              "    formatting"
            ],
            "isHidden": true,
            "displayFolder": "Varia",
            "lineageTag": "69a4c54d-78b6-469c-8ac3-c1b109e0da43",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "days since refresh",
            "expression": "ABS( DATEDIFF( TODAY( ), [max datum report], DAY ) )",
            "isHidden": true,
            "displayFolder": "Varia",
            "lineageTag": "7a0489f2-de8a-4808-b51a-1254f8838a50",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Budget basic x",
            "expression": [
              "VAR _tabtijd = VALUES( 'date'[yyyy-mm] )",
              "VAR _adc = ADDCOLUMNS( _tabtijd, \"@budget\", [Budget basic] )",
              "VAR _sumx = SUMX( _adc, [@budget] )",
              "RETURN",
              "    _sumx"
            ],
            "isHidden": true,
            "displayFolder": "!YTD\\Budget\\Budget rechtstreeks uit SAP (basis)",
            "lineageTag": "c9fe59c6-07ef-40fd-96d8-8e245287602a",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "budget basic ytd",
            "expression": [
              "VAR filterytd = SELECTEDVALUE( switch_ytd[value], 1 )",
              "VAR LastMonthAvailable = MAX( 'date'[Year Month Number] )",
              "VAR LastYearAvailable = MAX( 'date'[Year] )",
              "VAR Result =",
              "    CALCULATE(",
              "        [Budget basic],",
              "        REMOVEFILTERS( 'date' ),",
              "        'date'[Year Month Number] <= LastMonthAvailable,",
              "        'date'[Year] = LastYearAvailable",
              "    )",
              "VAR iflogic =",
              "    IF( SELECTEDVALUE( 'date'[ytd?] ) <= filterytd, Result )",
              "RETURN",
              "    Result"
            ],
            "isHidden": true,
            "displayFolder": "!YTD\\Budget\\Budget rechtstreeks uit SAP (basis)",
            "lineageTag": "dd919fa0-e9b0-47c9-adb4-4b240bb5ad5d",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "D YTD basis",
            "expression": "[budget basic ytd] - [Actuals YTD]",
            "isHidden": true,
            "displayFolder": "!YTD\\Delta",
            "lineageTag": "c3a0aeee-dc61-4f3c-bfa7-1ec23c60541a",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "D YTD basis A<B",
            "expression": "IF( [D YTD basis] > 0, [D YTD basis] )",
            "isHidden": true,
            "displayFolder": "!YTD\\Delta",
            "lineageTag": "dad45af1-8c22-403e-939e-1a68690b285d",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "D YTD basis A>B",
            "expression": "IF( [D YTD basis] < 0, [D YTD basis] )",
            "isHidden": true,
            "displayFolder": "!YTD\\Delta",
            "lineageTag": "da66d18e-e7ab-497e-b307-ea2e41188dd7",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "B versie max numeric",
            "expression": "INT( RIGHT( [B versie max], 1 ) )",
            "isHidden": true,
            "displayFolder": "!YTD\\Budget",
            "lineageTag": "67faeb7f-5ca2-47f0-990b-1641c84313ff",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "B YTD ss scope",
            "expression": [
              "",
              "VAR filterytd = MIN( switch_ytd[value] )",
              "VAR calc =",
              "    IF(",
              "        ISFILTERED( 'date'[yyyy-mm] ) || ISFILTERED( 'date'[Month] )",
              "            || ISFILTERED( 'date'[Month Number] ),",
              "        [Besteed],",
              "        CALCULATE(",
              "            [Besteed YTD],",
              "            -- FILTER( ALL( 'date' ), 'date'[ytd?] = filterytd )",
              "            FILTER(",
              "                ALLEXCEPT( 'date', 'date'[Year] ),",
              "                'date'[ytd?] <= filterytd",
              "            )",
              "        )",
              "    )",
              "VAR ShowRow =",
              "    OR(",
              "        [BrowseDepth] <= [RowDepth],",
              "        ISINSCOPE( 'dim resultatenrekening'[soort+beschrijving] )",
              "    )",
              "VAR _scope = IF( ShowRow, [B YTD ss] )",
              "RETURN",
              "    _scope"
            ],
            "isHidden": true,
            "displayFolder": "!YTD\\Budget",
            "lineageTag": "c83548e7-a89c-4c1b-9ef7-8e6109d75677",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "D YTD ss scope",
            "expression": [
              "",
              "VAR ShowRow =",
              "    OR(",
              "        [BrowseDepth] <= [RowDepth],",
              "        ISINSCOPE( 'dim resultatenrekening'[soort+beschrijving] )",
              "    )",
              "VAR _scope = IF( ShowRow, [D YTD ss] )",
              "RETURN",
              "    _scope"
            ],
            "isHidden": true,
            "displayFolder": "!YTD\\Delta",
            "lineageTag": "f8011fd5-e21a-4561-a07d-46118072df99",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "D% YTD ss scope",
            "expression": [
              "",
              "VAR ShowRow =",
              "    OR(",
              "        [BrowseDepth] <= [RowDepth],",
              "        ISINSCOPE( 'dim resultatenrekening'[soort+beschrijving] )",
              "    )",
              "VAR _scope = IF( ShowRow, [D% YTD ss] )",
              "RETURN",
              "    _scope"
            ],
            "isHidden": true,
            "displayFolder": "!YTD\\Delta",
            "lineageTag": "d0bed2c8-6f60-4a69-8038-19dfb1437397",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "versie precalc",
            "expression": "RIGHT( MIN( 'precalc table AB'[Versie] ), 3 )",
            "isHidden": true,
            "displayFolder": "Varia",
            "lineageTag": "959fcaac-c03d-4477-924d-d78bdcfec330",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "budget 2022 v000",
            "expression": "CALCULATE( [Budget basic x], 'date'[Year] = 2022 )",
            "formatString": "0",
            "isHidden": true,
            "displayFolder": "!YTD\\Budget",
            "lineageTag": "8b210d9f-72bc-4790-86ba-ac11a6c54ce9"
          },
          {
            "name": "budget 2023 v000",
            "expression": "CALCULATE( [Budget basic x], 'date'[Year] = 2023 )",
            "isHidden": true,
            "displayFolder": "!YTD\\Budget",
            "lineageTag": "0ebf467f-5367-4b98-a450-3dd870959532",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "delta budget v000",
            "expression": "ABS( [budget 2023 v000] - [budget 2022 v000] )",
            "isHidden": true,
            "displayFolder": "!YTD\\Delta",
            "lineageTag": "ebf7e20c-175c-41d7-9763-baa2efd7b48c",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "D",
            "expression": "[B MTD]-[Besteed]",
            "isHidden": true,
            "displayFolder": "!YTD\\Delta",
            "lineageTag": "cdf68733-2ad7-4571-b736-5cfa54bbfe22"
          },
          {
            "name": "a",
            "expression": "SUM('fct besteed'[actual])",
            "isHidden": true,
            "displayFolder": "!PNL",
            "lineageTag": "27c52dca-a287-4614-b526-63715d9b2fea"
          },
          {
            "name": "a if",
            "expression": [
              "",
              "IF(",
              "    [ifl timeperiod], [a voor23], [a na23]",
              ")"
            ],
            "isHidden": true,
            "displayFolder": "!PNL",
            "lineageTag": "fd8ceece-a6aa-49bb-bca5-06772d4a93e6"
          },
          {
            "name": "a na23",
            "expression": [
              "",
              "VAR _treatas =",
              "CALCULATE(",
              "    [a],",
              "    TREATAS(",
              "        VALUES( 'dim pnl'[sleutel_na2023] ),",
              "        'fct besteed'[sleutelpnl switch]",
              "    )",
              ")",
              "--VAR _fout = CALCULATE(_treatas, REMOVEFILTERS(), pnl_conv2023[P&L niv 1] = \"fout\")",
              "RETURN",
              "    _treatas"
            ],
            "isHidden": true,
            "displayFolder": "!PNL",
            "lineageTag": "dd8d4d2a-45c8-4575-a48e-efb5340356ad",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "a voor23",
            "expression": [
              "",
              "VAR _treatas =",
              "CALCULATE(",
              "    [a],",
              "    TREATAS(",
              "        VALUES( 'dim pnl'[sleutel_voor2023] ),",
              "        'fct besteed'[sleutelpnl switch]",
              "    )",
              ")",
              "--VAR _fout = CALCULATE(_treatas, REMOVEFILTERS(), pnl_conv2023[P&L niv 1] = \"fout\")",
              "RETURN",
              "    _treatas"
            ],
            "isHidden": true,
            "displayFolder": "!PNL",
            "lineageTag": "7dc9b864-cd27-48d5-8ae2-cddd6d876b58",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "b",
            "expression": "SUM('fct budget'[budget])",
            "isHidden": true,
            "displayFolder": "!PNL",
            "lineageTag": "b4726338-d2b5-4742-9c26-d89281c1d8e3"
          },
          {
            "name": "b if",
            "expression": [
              "",
              "IF(",
              "    max('date'[Year])<2024, [b voor23], [b na23]",
              ")"
            ],
            "isHidden": true,
            "displayFolder": "!PNL",
            "lineageTag": "4ff014e5-88d6-4ada-b9c7-a7a59ff6478f",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "b na23",
            "expression": [
              "",
              "VAR _treatas =",
              "CALCULATE(",
              "    [b],",
              "    TREATAS(",
              "        VALUES( 'dim pnl'[sleutel_na2023] ),",
              "        'fct budget'[sleutelpnl switch]",
              "    )",
              ")",
              "RETURN",
              "    _treatas"
            ],
            "isHidden": true,
            "displayFolder": "!PNL",
            "lineageTag": "15f882a3-8f57-4aa9-b4e5-d9094f2308ec",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "b voor23",
            "expression": [
              "",
              "VAR _treatas =",
              "CALCULATE(",
              "    [b],",
              "    TREATAS(",
              "        VALUES( 'dim pnl'[sleutel_voor2023] ),",
              "        'fct budget'[sleutelpnl switch]",
              "    )",
              ")",
              "RETURN",
              "    _treatas"
            ],
            "isHidden": true,
            "displayFolder": "!PNL",
            "lineageTag": "920ee79a-bf57-4594-a4b9-e69f63578369",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "fixed column width",
            "expression": "9999999999999",
            "isHidden": true,
            "displayFolder": "!PNL",
            "lineageTag": "1dbcde8c-b5eb-41f3-9e48-0ef78d0e1cfb"
          },
          {
            "name": "ifl timeperiod",
            "expression": [
              "",
              "IF(",
              "    SELECTEDVALUE( 'date'[Year] )",
              "        <2023,--<> YEAR( TODAY( ) ),",
              "    TRUE( )",
              ")",
              ""
            ],
            "isHidden": true,
            "displayFolder": "!PNL",
            "lineageTag": "a3dcb1fd-c761-4d17-ad73-354f02385c77",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "switch x",
            "expression": [
              "",
              "VAR _tab = CROSSJOIN(DISTINCT('dim pnl'), VALUES('date'[Year]))",
              "VAR _addc = ADDCOLUMNS(_tab, \"@switch\" , [switch_measures])",
              "VAR _sumx = SUMX(_addc, [@switch])",
              "RETURN",
              "    _sumx"
            ],
            "isHidden": true,
            "displayFolder": "!PNL",
            "lineageTag": "257ae289-daa4-49da-a960-bbd40e52af2d",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "switch_measures",
            "expression": [
              "",
              "SWITCH(",
              "    TRUE( ),",
              "    SELECTEDVALUE( 'date'[periode code] ) = \"a\", [a if],",
              "    SELECTEDVALUE( 'date'[periode code] ) = \"b\", [b if],",
              "    SELECTEDVALUE( 'date'[periode code]) = \"p\", BLANK(),",
              "    1",
              ")"
            ],
            "isHidden": true,
            "displayFolder": "!PNL",
            "lineageTag": "ddb2c5fd-3e28-4396-acec-0bc62bf62685",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "$actual",
            "expression": "[Actuals basic]",
            "displayFolder": "$selfservice",
            "lineageTag": "be133731-3206-4bef-b163-cb28569455ef"
          },
          {
            "name": "$obligo",
            "expression": "[obligo basic]",
            "displayFolder": "$selfservice",
            "lineageTag": "3e5bf990-592e-4c26-a59a-eb42fd75b3cc"
          },
          {
            "name": "$budget",
            "expression": "[Budget basic x]",
            "displayFolder": "$selfservice",
            "lineageTag": "ccee9c9c-4525-4341-89bd-bde79e0db443"
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "cd71549b7bc74322a2fc69e16da972fd"
          },
          {
            "name": "436ba87b-9c83-4389-a31b-ebd06a36be98",
            "value": "{\"Expression\":\"\"}"
          }
        ]
      },
      {
        "name": "date",
        "lineageTag": "09acf4cf-be8a-4f51-8082-61afcd7ac0aa",
        "dataCategory": "Time",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Year",
            "dataType": "int64",
            "isNameInferred": true,
            "sourceColumn": "[year]",
            "formatString": "0",
            "displayFolder": "_Favorieten",
            "lineageTag": "212d6cf0-9156-4b34-ad4d-06cf88ae1323",
            "summarizeBy": "sum",
            "changedProperties": [
              {
                "property": "DataType"
              },
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Month",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[month]",
            "sortByColumn": "Month Number",
            "displayFolder": "_Favorieten",
            "lineageTag": "b6fc224c-b12a-43c5-9b01-8b1a7e583a69",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              },
              {
                "property": "SortByColumn"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "yeartext",
            "dataType": "string",
            "isHidden": true,
            "expression": "'date'[year]",
            "lineageTag": "0b50d580-1493-4418-b2c5-1dd06cd1fd0f",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "DataType"
              },
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Year Month Number",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[year month number]",
            "formatString": "0",
            "lineageTag": "cce22ea4-5b19-4f87-9e2c-f6efca2b59de",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "ytd?",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": [
              "",
              "",
              "VAR result = ",
              "",
              "SWITCH(",
              "    TRUE(),",
              "    -- 'date'[yyyy-mm] = [max month current year (2022-12)], 3,",
              "    'date'[YYYY-MM] <= [closing period ytd], 1,",
              "    --'date'[YYYY-MM] < [max transaction today] , 1,",
              "    2",
              "    --",
              "    --'date'[Year] = YEAR(TODAY()), 3,",
              "    --4",
              ")",
              "RETURN result"
            ],
            "formatString": "0",
            "lineageTag": "338abc2e-4f5a-4378-9286-d27117c57896",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Year Month Key",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Year Month Key]",
            "formatString": "0",
            "lineageTag": "842e41dc-7530-4b88-a173-3e994902b107",
            "summarizeBy": "count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Year Quarter",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Year Quarter]",
            "lineageTag": "e4ac6a63-ce6b-4c33-8cc5-1cd69b308018",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Year Quarter Number",
            "dataType": "double",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Year Quarter Number]",
            "lineageTag": "de7e5677-2dae-4505-841b-a8a0034455e4",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Quarter",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Quarter]",
            "lineageTag": "d06771f6-75ad-4afd-86d5-d865d22d25d8",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Year Month",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Year Month]",
            "lineageTag": "7c83a1c7-bfc0-4e08-9ab3-1886aaa0e7ec",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "yyyy-mm",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[yyyy-mm]",
            "displayFolder": "_Favorieten",
            "lineageTag": "d2f80dac-870e-44bf-a966-ae7b0f0fa137",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Month Number",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Month Number]",
            "formatString": "0",
            "lineageTag": "fdfef3fb-85f5-4a63-843e-453849ba0aab",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Month In Quarter Number",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Month In Quarter Number]",
            "formatString": "0",
            "lineageTag": "2766bc5a-5894-42e9-888e-ad88ca9e87b2",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Fiscal Year",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Fiscal Year]",
            "lineageTag": "f40d1109-2664-429d-b4fa-9b65a2569f2b",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Fiscal Year Number",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Fiscal Year Number]",
            "formatString": "0",
            "lineageTag": "84fb1f05-7ff2-4b0d-a4eb-5b83e39fb846",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Fiscal Year Quarter",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Fiscal Year Quarter]",
            "lineageTag": "95cd8f70-901f-47d5-8e8d-94b24cb985dc",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Fiscal Year Quarter Number",
            "dataType": "double",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Fiscal Year Quarter Number]",
            "lineageTag": "e9f87105-bc8b-43c2-9beb-42922dbce9a0",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Fiscal Quarter",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Fiscal Quarter]",
            "lineageTag": "c69bc3ba-cf5e-4335-9c89-9f701ccb798f",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Fiscal Month",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Fiscal Month]",
            "lineageTag": "94007cb1-2829-4253-ad89-25fe45d105d5",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Fiscal Month Number",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Fiscal Month Number]",
            "formatString": "0",
            "lineageTag": "58b7566f-8349-4a3f-9c4c-239291468b69",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Fiscal Month In Quarter Number",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Fiscal Month In Quarter Number]",
            "formatString": "0",
            "lineageTag": "0197fa47-9388-40ef-af4f-7a7fb98f0d3e",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "maandindex",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": [
              "",
              "INT(('date'[Year]-YEAR(TODAY()))*12+ 'date'[Month Number])-MONTH(TODAY())"
            ],
            "formatString": "0",
            "lineageTag": "b09dce02-d78a-4b16-ba28-dd18b503f954",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "jaarindex",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": [
              "",
              "'date'[Year]-YEAR(TODAY())"
            ],
            "formatString": "0",
            "lineageTag": "941b3a33-b88a-4a14-add2-eb094feba537",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "now?",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": [
              "",
              "",
              "IF('date'[YYYY-MM]<=[max transaction yyyymm],\"Now\", \"Future\")"
            ],
            "lineageTag": "7d18cf3c-3308-4880-b11f-72278063dc0f",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "perdiode",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": [
              "",
              "VAR _cy = YEAR( TODAY( ) )",
              "VAR _calc =",
              "    SWITCH(",
              "        TRUE( ),",
              "        'date'[Year] < _cy, \"actuals (SAP)\",",
              "        'date'[Year] = _cy, \"budget (SAP)\",",
              "        'date'[Year] > _cy, \"prognose budget (Excel)\",",
              "        \"ERROR\"",
              "    )",
              "RETURN",
              "    _calc",
              "    "
            ],
            "lineageTag": "5a49459f-0ea3-4ae0-85fc-ea5c97385e00",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "periode code",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": [
              "",
              "VAR _cy = YEAR( TODAY( ) )",
              "VAR _calc =",
              "    SWITCH(",
              "        TRUE( ),",
              "        'date'[Year] < _cy, \"a\",",
              "        'date'[Year] = _cy, \"b\",",
              "        'date'[Year] > _cy, \"p\",",
              "        \"ERROR\"",
              "    )",
              "RETURN",
              "    _calc",
              "    "
            ],
            "lineageTag": "feecc5c7-5f7c-46a4-9637-9e2fd4f403be",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "date-90887759-09d1-4159-bcb3-3028b5cff173",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR FirstFiscalMonth = 1 ",
                "VAR MonthsInYear = 12     ",
                "VAR CalendarFirstDate = MIN ( 'fct besteed'[boekdatum] )",
                "VAR CalendarLastDate = MAX ( 'fct besteed'[boekdatum] )",
                "VAR CalendarFirstYear = YEAR ( CalendarFirstDate )",
                "VAR CalendarFirstMonth = MONTH ( CalendarFirstDate )",
                "VAR CalendarLastYear = YEAR ( CalendarLastDate )",
                "VAR CalendarLastMonth = MONTH ( CalendarLastDate )",
                " ",
                "-------------------------",
                "-- Internal calculations",
                "-------------------------",
                "",
                "VAR GranularityByMonth =",
                "    SELECTCOLUMNS (",
                "        GENERATESERIES (",
                "            CalendarFirstYear * MonthsInYear + CalendarFirstMonth - 1",
                "                - (MonthsInYear - 12) * (CalendarFirstMonth < FirstFiscalMonth),",
                "            CalendarLastYear * MonthsInYear + CalendarLastMonth - 1",
                "                - (MonthsInYear - 12) * (CalendarLastMonth < FirstFiscalMonth),",
                "            1",
                "        ),",
                "        \"Year Month Number\", [Value]",
                "    )",
                "RETURN GENERATE (",
                "    GranularityByMonth,       -- Use GranularityByMonth to get one row for each month",
                "    VAR YearMonthNumber = [Year Month Number]",
                "    VAR FiscalMonthNumber =",
                "        MOD (",
                "            YearMonthNumber + 1",
                "                * (FirstFiscalMonth > 1)",
                "                * (MonthsInYear + 1 - FirstFiscalMonth),",
                "            MonthsInYear",
                "        ) + 1",
                "    VAR FiscalYearNumber =",
                "        QUOTIENT (",
                "            YearMonthNumber + 1",
                "                * (FirstFiscalMonth > 1)",
                "                * (MonthsInYear + 1 - FirstFiscalMonth),",
                "            MonthsInYear",
                "        )",
                "    VAR OffsetFiscalMonthNumber = MonthsInYear + 1 - (MonthsInYear - 12)",
                "    VAR MonthNumber =",
                "        IF (",
                "            FiscalMonthNumber <= 12 && FirstFiscalMonth > 1,",
                "            FiscalMonthNumber + FirstFiscalMonth",
                "                - IF (",
                "                    FiscalMonthNumber > (OffsetFiscalMonthNumber - FirstFiscalMonth),",
                "                    OffsetFiscalMonthNumber,",
                "                    1",
                "                ),",
                "            FiscalMonthNumber",
                "        )",
                "    VAR YearNumber = FiscalYearNumber - 1 * (MonthNumber > FiscalMonthNumber)",
                "    VAR YearMonthKey = YearNumber * 100 + MonthNumber",
                "     ",
                "    VAR MonthDate = DATE ( YearNumber, MonthNumber, 1 )",
                "    VAR FiscalQuarterNumber = MIN ( ROUNDUP ( FiscalMonthNumber / 3, 0 ), 4 )",
                "    VAR FiscalYearQuarterNumber = FiscalYearNumber * 4 + FiscalQuarterNumber - 1",
                "    VAR FiscalMonthInQuarterNumber =",
                "        MOD ( FiscalMonthNumber - 1, 3 ) + 1 + 3 * (MonthNumber > 12)",
                "    VAR MonthInQuarterNumber = MOD ( MonthNumber - 1, 3 ) + 1 + 3 * (MonthNumber > 12)",
                "    VAR QuarterNumber = MIN ( ROUNDUP ( MonthNumber / 3, 0 ), 4 )",
                "    VAR YearQuarterNumber = YearNumber * 4 + QuarterNumber - 1",
                "    RETURN ROW (",
                "        \"Year Month Key\", YearMonthKey,",
                "        \"Year\", YearNumber,",
                "        \"Year Quarter\", FORMAT ( QuarterNumber, \"\\Q0\" )",
                "            & \"-\" & FORMAT ( YearNumber, \"0000\" ),",
                "        \"Year Quarter Number\", YearQuarterNumber,",
                "        \"Quarter\", FORMAT ( QuarterNumber, \"\\Q0\" ),",
                "        \"Year Month\", IF (",
                "            MonthNumber > 12,",
                "            FORMAT ( MonthNumber, \"\\M00\" ) & FORMAT ( YearNumber, \" 0000\" ),",
                "            FORMAT ( MonthDate, \"mmm yyyy\" )",
                "        ),",
                "        \"yyyy-mm\", FORMAT ( MonthDate, \"yyyy-mm\" ),",
                "        \"Month\", IF (",
                "            MonthNumber > 12,",
                "            FORMAT ( MonthNumber, \"\\M00\" ),",
                "            FORMAT ( MonthDate, \"mmm\" )",
                "        ),",
                "        \"Month Number\", MonthNumber,",
                "        \"Month In Quarter Number\", MonthInQuarterNumber,",
                "        \"Fiscal Year\", FORMAT ( FiscalYearNumber, \"\\F\\Y 0000\" ),",
                "        \"Fiscal Year Number\", FiscalYearNumber,",
                "        \"Fiscal Year Quarter\", FORMAT ( FiscalQuarterNumber, \"\\F\\Q0\" ) & \"-\"",
                "            & FORMAT ( FiscalYearNumber, \"0000\" ),",
                "        \"Fiscal Year Quarter Number\", FiscalYearQuarterNumber,",
                "        \"Fiscal Quarter\", FORMAT ( FiscalQuarterNumber, \"\\F\\Q0\" ),",
                "        \"Fiscal Month\", IF (",
                "            MonthNumber > 12,",
                "            FORMAT ( MonthNumber, \"\\M00\" ),",
                "            FORMAT ( MonthDate, \"mmm\" )",
                "        ),",
                "        \"Fiscal Month Number\", FiscalMonthNumber,",
                "        \"Fiscal Month In Quarter Number\", FiscalMonthInQuarterNumber",
                "    )",
                ")"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "MaxDate",
            "description": "CALCULATE( MAX( actuals[boekdatum] ), ALL( 'date' ) )",
            "expression": [
              "VAR calc =",
              "    CALCULATE(",
              "        MAX( 'fct besteed'[boekdatum] ),",
              "        REMOVEFILTERS( 'date' ),",
              "        'fct besteed'[a_o] = \"A\"",
              "    )",
              "VAR form = FORMAT( calc, \"dd-mm-yyyy\" )",
              "RETURN",
              "    form"
            ],
            "isHidden": true,
            "lineageTag": "ff08ded3-36fa-4e51-8cd7-e47d86d0afcd",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ]
          },
          {
            "name": "yeartoday",
            "description": "YEAR( TODAY( ) )",
            "expression": "YEAR( TODAY( ) )",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "b9bcacac-e435-4657-91c4-6fff10351851",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ]
          },
          {
            "name": "MaxYear",
            "description": "YEAR( [MaxDate] )",
            "expression": "YEAR( [MaxDate] )",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "6e94e226-c79a-4340-98aa-c5a57be91113",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ]
          },
          {
            "name": "MaxYYYYMM",
            "description": "CALCULATE( MAX( actuals[yyyymm] ), ALL( 'date' ) )",
            "expression": [
              "VAR calc =",
              "    CALCULATE(",
              "        MAX( 'fct besteed'[boekdatum] ),",
              "        REMOVEFILTERS( 'date' ),",
              "        'fct besteed'[a_o] = \"A\"",
              "    )",
              "VAR form = FORMAT( calc, \"mm-yyyy\" )",
              "RETURN",
              "    form"
            ],
            "isHidden": true,
            "lineageTag": "89a0e403-25cc-4723-9444-8da6c96b1bc8",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ]
          },
          {
            "name": "ytdfiltermeasure",
            "expression": "MAX( 'date'[ytd?] )",
            "isHidden": true,
            "lineageTag": "c9dcaf76-3f05-4cd2-a12d-fe2727dedd4a",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          }
        ],
        "hierarchies": [
          {
            "name": "year Hierarchy",
            "isHidden": true,
            "lineageTag": "1a39c23b-2da0-40d0-a3fd-17841cca94b5",
            "levels": [
              {
                "name": "year",
                "ordinal": 0,
                "column": "Year",
                "lineageTag": "2b96a456-5c55-484c-bd7f-e535f2720461"
              },
              {
                "name": "month",
                "ordinal": 1,
                "column": "Month",
                "lineageTag": "19a6016d-5304-4b65-afc6-575d5468a022"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "7d90d4a1c90c43f3b3f8166e2e62aee4"
          },
          {
            "name": "TabularEditor_TableGroup",
            "value": "dimension"
          }
        ]
      },
      {
        "name": "bestelbon",
        "lineageTag": "7c1c11f1-a17d-4d67-b0fa-8c175367ad9a",
        "columns": [
          {
            "name": "bestel_tekst",
            "dataType": "string",
            "sourceColumn": "bestel_tekst",
            "lineageTag": "26443a56-32bb-4773-b6c8-f352afa6e2e9",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "inkoopartikel",
            "dataType": "string",
            "sourceColumn": "inkoopartikel",
            "lineageTag": "29df0c63-bc64-462a-9ce4-a75e7ebf8f76",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "leverancier_id",
            "dataType": "string",
            "sourceColumn": "leverancier_id",
            "lineageTag": "fdf978be-2220-4728-8850-837beab506d0",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "lev_land",
            "dataType": "string",
            "sourceColumn": "lev_land",
            "lineageTag": "6885984b-d839-47b7-98d3-c2e36fe6373c",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "lev_naam",
            "dataType": "string",
            "sourceColumn": "lev_naam",
            "lineageTag": "7e3920e7-12eb-4a95-9476-117044e6027f",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "lev_stad",
            "dataType": "string",
            "sourceColumn": "lev_stad",
            "lineageTag": "a7dcd805-b2e2-4411-b89b-688674d9b569",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "lev_postcode",
            "dataType": "string",
            "sourceColumn": "lev_postcode",
            "lineageTag": "d69b566b-5f7d-4a16-be5c-93a35eea12f4",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "lev_straat",
            "dataType": "string",
            "sourceColumn": "lev_straat",
            "lineageTag": "3955a69c-75b5-4396-b5e2-2cdce2c5a005",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "lev_bankrekening",
            "dataType": "string",
            "sourceColumn": "lev_bankrekening",
            "lineageTag": "3c1744b1-d616-44b3-818e-416f85c652bf",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "bestelbonnummer",
            "dataType": "string",
            "sourceColumn": "bestelbonnummer",
            "lineageTag": "0770ef54-167c-4d97-a02d-4822ab14107a",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "bestelbon_positie",
            "dataType": "string",
            "sourceColumn": "bestelbon_positie",
            "lineageTag": "f7fe8c0c-ddaa-4d4b-b43e-595ad358a9bb",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "bestelbon",
            "dataType": "string",
            "sourceColumn": "bestelbon",
            "lineageTag": "ce4236ed-0ae8-4625-89a5-1a6f2853f027",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "ingevoerd_door",
            "dataType": "string",
            "sourceColumn": "ingevoerd_door",
            "lineageTag": "82022b3d-9bfd-4791-8b78-57ae8f83c27a",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "bestelbon-a755d5e7-5676-40f3-a8e4-46c75baae01c",
            "mode": "import",
            "queryGroup": "Datalake",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = AmazonAthena.Databases(\"Simba Athena\", null),",
                "    AwsDataCatalog_Database = Source{[Name=\"AwsDataCatalog\",Kind=\"Database\"]}[Data],",
                "    analytics_nonprod_athena_Schema = AwsDataCatalog_Database{[Name=SourceAthena,Kind=\"Schema\"]}[Data],",
                "    dim_opdata_fin_ytd_bestelbon_Table = analytics_nonprod_athena_Schema{[Name=\"dim_opdata_fin_ytd_bestelbon\",Kind=\"Table\"]}[Data]",
                "in",
                "    dim_opdata_fin_ytd_bestelbon_Table"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          },
          {
            "name": "TabularEditor_TableGroup",
            "value": "dimension"
          }
        ]
      },
      {
        "name": "fct budget",
        "lineageTag": "7236a515-85a9-40ca-8403-1dcf2a09a473",
        "columns": [
          {
            "name": "soort_id",
            "dataType": "string",
            "sourceColumn": "soort_id",
            "lineageTag": "6d1fd4a6-4294-420e-83f0-5f1ab1559a64",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "artiplek_id",
            "dataType": "string",
            "sourceColumn": "artiplek_id",
            "lineageTag": "78ef13aa-d4d2-4772-aa74-c8f563dd510c",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "versie",
            "dataType": "string",
            "sourceColumn": "versie",
            "lineageTag": "95243dca-9deb-4b6b-b292-546ac235d488",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "yyyymm",
            "dataType": "string",
            "sourceColumn": "yyyymm",
            "lineageTag": "c70afbcc-3645-4345-8cf9-f7f3c9f429fb",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "afkorting",
            "dataType": "string",
            "sourceColumn": "afkorting",
            "lineageTag": "e12f322d-def3-4a92-a91d-9631432781ce",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "ratioflag",
            "dataType": "string",
            "sourceColumn": "ratioflag",
            "lineageTag": "810ac7c0-fed7-4e05-ad71-e4a99518d354",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "compkey_versie",
            "dataType": "string",
            "sourceColumn": "compkey_versie",
            "lineageTag": "793b4651-1481-4d69-8dc9-6b1c0744335c",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "budget",
            "dataType": "double",
            "sourceColumn": "budget",
            "formatString": "#,0.00",
            "lineageTag": "d3fdaefc-8533-47ff-abd9-154a33ef4747",
            "summarizeBy": "sum",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "objecttype",
            "dataType": "string",
            "sourceColumn": "objecttype",
            "lineageTag": "7175650b-af03-4765-8503-5b655db075da",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "object_id",
            "dataType": "string",
            "sourceColumn": "object_id",
            "lineageTag": "3280644a-45c1-42ad-afd3-cb18a89d621e",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "jaarbudget",
            "dataType": "double",
            "sourceColumn": "jaarbudget",
            "formatString": "#,0.00",
            "lineageTag": "7fbc5797-b3dd-4fbc-b26a-ba1f3d14c2d0",
            "summarizeBy": "sum",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "soort/artiplek_id",
            "dataType": "string",
            "sourceColumn": "soort/artiplek_id",
            "lineageTag": "7e8fa63d-f88f-4904-b185-6e7bdc36aa04",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "soort_id_zonderalgkv",
            "dataType": "string",
            "sourceColumn": "soort_id_zonderalgkv",
            "lineageTag": "82b83454-4875-429c-8e3f-d9308ddedfb8",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "af_pe_ytd",
            "dataType": "string",
            "sourceColumn": "af_pe_ytd",
            "lineageTag": "dd97a0ee-8e7b-4972-b6a8-fb6f5cafe33c",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "filterytd",
            "dataType": "string",
            "sourceColumn": "filterytd",
            "lineageTag": "7de79b23-ce22-4116-8d92-2733d5b2ec6f",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "ratio",
            "dataType": "double",
            "sourceColumn": "ratio",
            "lineageTag": "f01cbf3e-e143-4f72-aec1-1bb2e70dd4ea",
            "summarizeBy": "sum",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "sleutelpnl switch",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": [
              "",
              "VAR _sleutel ='fct budget'[object_id] & \"_\" & 'fct budget'[soort_id_zonderalgkv] ",
              "VAR _switchlogic = ",
              "    SWITCH(",
              "        TRUE(),",
              "        LEFT('fct budget'[object_id],3) in {\"RCA\",\"RTV\",\"RKE\",\"RNU\",\"RSP\", \"RNI\"}, LEFT('fct budget'[object_id],3) & \"_\" & 'fct budget'[soort_id_zonderalgkv],",
              "        LEFT('fct budget'[object_id],1) in {\"M\", \"E\"}, LEFT('fct budget'[object_id],3) & \"_\" & 'fct budget'[soort_id_zonderalgkv],",
              "        _sleutel",
              "    )",
              "RETURN",
              "    _switchlogic"
            ],
            "lineageTag": "a673e964-500b-4f4b-a8f3-5375c0a65ca8",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "fct budget-9b8a7cf0-476e-4f6d-b5d5-2b05994f777b",
            "mode": "import",
            "queryGroup": "Datalake",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = AmazonAthena.Databases(\"Simba Athena\", null),",
                "    AwsDataCatalog_Database = Source{[Name=\"AwsDataCatalog\",Kind=\"Database\"]}[Data],",
                "    analytics_nonprod_athena_Schema = AwsDataCatalog_Database{[Name=SourceAthena,Kind=\"Schema\"]}[Data],",
                "    dim_opdata_fin_ytd_bestelbon_Table = analytics_nonprod_athena_Schema{[Name=\"fct_opdata_fin_ytd_budget\",Kind=\"Table\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(dim_opdata_fin_ytd_bestelbon_Table,{{\"budget\", type number}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "TabularEditor_TableGroup",
            "value": "facts"
          }
        ]
      },
      {
        "name": "importdate",
        "lineageTag": "812b8a61-b153-4c62-b9cd-707909fce444",
        "columns": [
          {
            "name": "import_date",
            "dataType": "dateTime",
            "sourceColumn": "import_date",
            "formatString": "Long Date",
            "lineageTag": "0e5f2c79-03cd-432a-bd42-f8f39b72e010",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ]
          },
          {
            "name": "yyyymm_ytd",
            "dataType": "string",
            "sourceColumn": "yyyymm_ytd",
            "lineageTag": "e817737d-5a13-4546-a563-48de16440c9a",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "yyyymm_ytd_min1",
            "dataType": "string",
            "sourceColumn": "yyyymm_ytd_min1",
            "lineageTag": "5e8eb178-2260-4c3f-a779-dac6773bc73c",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "current_year",
            "dataType": "int64",
            "sourceColumn": "current_year",
            "formatString": "0",
            "lineageTag": "44854cd0-8eca-4e88-a620-ba5b9d095979",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "closed_year",
            "dataType": "int64",
            "sourceColumn": "closed_year",
            "formatString": "0",
            "lineageTag": "12ac78d0-dd47-4b8a-86f3-f06627ddb853",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "closed_pyear",
            "dataType": "int64",
            "sourceColumn": "closed_pyear",
            "formatString": "0",
            "lineageTag": "2234a3db-1bdc-4520-8613-395bffa888f4",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "importdate-e169a7d5-190c-49aa-a94b-14cbce9db44b",
            "mode": "import",
            "queryGroup": "Datalake",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = AmazonAthena.Databases(\"Simba Athena\", null),",
                "    AwsDataCatalog_Database = Source{[Name=\"AwsDataCatalog\",Kind=\"Database\"]}[Data],",
                "    analytics_nonprod_athena_Schema = AwsDataCatalog_Database{[Name=SourceAthena,Kind=\"Schema\"]}[Data],",
                "    dim_opdata_fin_ytd_bestelbon_Table = analytics_nonprod_athena_Schema{[Name=\"dim_opdata_fin_ytd_maximportdate\",Kind=\"Table\"]}[Data]",
                "in",
                "    dim_opdata_fin_ytd_bestelbon_Table"
              ]
            }
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          },
          {
            "name": "TabularEditor_TableGroup",
            "value": "disconnected"
          }
        ]
      },
      {
        "name": "field column",
        "lineageTag": "4d87bd5e-679a-40ca-8cf8-ba17f356c3c9",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Columns selected",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[Value1]",
            "sortByColumn": "Parameter Order",
            "lineageTag": "921cb7bc-a409-4f22-9758-d182bd5828c8",
            "summarizeBy": "none",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "Parameter Fields"
                }
              ]
            },
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Parameter Fields",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[Value2]",
            "sortByColumn": "Parameter Order",
            "lineageTag": "34afaf62-1578-41c8-a67a-e7aa5df63db0",
            "summarizeBy": "none",
            "extendedProperties": [
              {
                "type": "json",
                "name": "ParameterMetadata",
                "value": {
                  "version": 3,
                  "kind": 2
                }
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Parameter Order",
            "dataType": "int64",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[Value3]",
            "formatString": "0",
            "lineageTag": "2d455a86-e809-4442-801b-cf1f35691740",
            "summarizeBy": "sum",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Categorie",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[Value4]",
            "sortByColumn": "Categorie_sort",
            "lineageTag": "1e0f5438-947e-48a7-8fc8-36c1dcf3eeb7",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              },
              {
                "property": "SortByColumn"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Categorie_sort",
            "dataType": "int64",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[Value5]",
            "formatString": "0",
            "lineageTag": "79224d2c-cc5d-4f02-91eb-af87ed835c0c",
            "summarizeBy": "sum",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "field column-c3ed68fa-e023-44cc-aa79-62e32af21187",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "{",
                "    (\" \", NAMEOF('Key Measures'[Column]), 100, \"geen selectie\", -1),",
                "",
                "    (\"yyyy-mm\", NAMEOF('date'[yyyy-mm]), -3, \"tijd\", 0),",
                "    (\"maand\", NAMEOF('date'[Month]), -2, \"tijd\", 0),",
                "    (\"jaar\", NAMEOF('date'[Year]), -1, \"tijd\", 0),",
                "",
                "    (\"directie\", NAMEOF('object'[Directie]), 7, \"object\", 1),",
                "    (\"directie_lvl2\", NAMEOF('object'[Level3]), 2, \"object\", 1),",
                "    (\"directie_lvl3\", NAMEOF('object'[Level4]), 3, \"object\", 1),",
                "    (\"directie_lvl4\", NAMEOF('object'[Level5]), 4, \"object\", 1),",
                "    (\"object+omschrijving\", NAMEOF('object'[object+omschrijving]), 6, \"object\", 1),",
                "    (\"objecttype\", NAMEOF('object'[objecttype]), 1, \"object\", 1),",
                "",
                "    (\"soort+omschrijving\", NAMEOF('dim resultatenrekening'[soort+beschrijving]), 8, \"soort\", 2),",
                "    (\"ledger niveau 1\", NAMEOF('dim resultatenrekening'[Level2]), 9, \"soort\", 2),",
                "    (\"ledger niveau 2\", NAMEOF('dim resultatenrekening'[Level3]), 10, \"soort\", 2),",
                "    (\"ledger niveau 3\", NAMEOF('dim resultatenrekening'[Level4]), 11, \"soort\", 2),",
                "    (\"ledger niveau 4\", NAMEOF('dim resultatenrekening'[Level5]), 13, \"soort\", 2),",
                "    (\"ledger niveau 5\", NAMEOF('dim resultatenrekening'[Level6]), 14, \"soort\", 2),",
                "    (\"ledger niveau 6\", NAMEOF('dim resultatenrekening'[Level7]), 15, \"soort\", 2),",
                "",
                "    (\"bestel_tekst\", NAMEOF('bestelbon'[bestel_tekst]), 25, \"bestelbon\", 3),",
                "    (\"inkoopartikel\", NAMEOF('bestelbon'[inkoopartikel]), 21, \"bestelbon\", 3),",
                "    (\"bestelbon_id\", NAMEOF('bestelbon'[bestelbonnummer]), 22, \"bestelbon\", 3),",
                "    (\"lev_bankrekening\", NAMEOF('bestelbon'[lev_bankrekening]), 23, \"bestelbon\", 3),",
                "    (\"lev_land\", NAMEOF('bestelbon'[lev_land]), 24, \"bestelbon\", 3),",
                "    (\"lev_naam\", NAMEOF('bestelbon'[lev_naam]), 20, \"bestelbon\", 3),",
                "    (\"lev_postcode\", NAMEOF('bestelbon'[lev_postcode]), 26, \"bestelbon\", 3),",
                "    (\"lev_stad\", NAMEOF('bestelbon'[lev_stad]), 27, \"bestelbon\", 3),",
                "    (\"lev_straat\", NAMEOF('bestelbon'[lev_straat]), 28, \"bestelbon\", 3),",
                "    (\"leverancier_id\", NAMEOF('bestelbon'[leverancier_id]), 29, \"bestelbon\", 3),",
                "    (\"positie_bestel\", NAMEOF('bestelbon'[bestelbon_positie]), 30, \"bestelbon\", 3),",
                "",
                "    (\"artikel\", NAMEOF('object'[artikel]), 50, \"artikel (PO)\", 4),",
                "    (\"productiehuis\", NAMEOF('object'[productiehuis]), 51, \"artikel (PO)\", 4),",
                "    (\"categorie\", NAMEOF('object'[categorie]), 52, \"artikel (PO)\", 4),",
                "    (\"kanaal\", NAMEOF('object'[kanaal]), 53, \"artikel (PO)\", 4),",
                "    (\"productiereeks_fin_rapport\", NAMEOF('object'[productiereeks_fin_rapport]), 54, \"artikel (PO)\", 4),",
                "    (\"subgenre\", NAMEOF('object'[subgenre]), 55, \"artikel (PO)\", 4),",
                "    (\"klant\", NAMEOF('object'[klant]), 56, \"artikel (PO)\", 4),",
                "    (\"IPRO_EPRO\", NAMEOF('object'[IPRO_EPRO]), 57, \"artikel (PO)\", 4),",
                "    (\"budgetbeheer_STD\", NAMEOF('object'[budgetbeheer_STD]), 58, \"artikel (PO)\", 4),",
                "    (\"budgetbeheer_PLP\", NAMEOF('object'[budgetbeheer_PLP]), 59, \"artikel (PO)\", 4),",
                "    (\"raamovereenkomst\", NAMEOF('object'[raamovereenkomst]), 60, \"artikel (PO)\", 4),",
                "    (\"netproducent\", NAMEOF('object'[netproducent]), 61, \"artikel (PO)\", 4)",
                "}"
              ]
            }
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "c0127a7e87fc4ac4b68d502011a185f4"
          },
          {
            "name": "TabularEditor_TableGroup",
            "value": "field paramaters"
          }
        ]
      },
      {
        "name": "BvA KPI",
        "lineageTag": "d6fb739c-eeaf-4e03-9873-12f200f268d8",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "BvA KPI >",
            "dataType": "int64",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[Value]",
            "formatString": "#,0",
            "lineageTag": "7c7fde4c-52f9-443e-8e90-3af5cda26af9",
            "summarizeBy": "sum",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "BvA KPI-71a10899-49af-440c-85fd-14d5d331eabf",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "{",
                "    (1000), ",
                "    (2000),",
                "    (3000), ",
                "    (4000),",
                "    (5000), ",
                "    (10000),",
                "    (20000), ",
                "    (30000),",
                "    (40000), ",
                "    (50000),",
                "    (100000), ",
                "    (150000),",
                "    (200000), ",
                "    (250000),",
                "    (300000), ",
                "    (400000),",
                "    (500000), ",
                "    (1000000)",
                "}",
                ""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "BvA KPI value",
            "description": "SELECTEDVALUE( 'BvA KPI'[BvA KPI >], 500000 )",
            "expression": "SELECTEDVALUE( 'BvA KPI'[BvA KPI >], 500000 )",
            "formatString": "#,0",
            "lineageTag": "cc57f057-273d-42fb-9758-0181a3c2a010",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ]
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "ec48e3d396984b1091f383ca3302976a"
          },
          {
            "name": "TabularEditor_TableGroup",
            "value": "disconnected"
          }
        ]
      },
      {
        "name": "BvA% KPI",
        "lineageTag": "9eb61413-514b-406e-9f32-b914c410f37b",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "BvA% KPI >",
            "dataType": "double",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[Value]",
            "formatString": "0%;-0%;0%",
            "lineageTag": "11617b63-26b1-48fd-8428-40bcf390668c",
            "summarizeBy": "none",
            "extendedProperties": [
              {
                "type": "json",
                "name": "ParameterMetadata",
                "value": {
                  "version": 0
                }
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              },
              {
                "property": "FormatString"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "BvA% KPI-04d6d20b-5d30-49ca-925b-54d834fbc691",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": "GENERATESERIES(0, 0.5, 0.01)"
            }
          }
        ],
        "measures": [
          {
            "name": "BvA% KPI Value",
            "description": "SELECTEDVALUE( 'BvA% KPI'[BvA% KPI >], 1 )",
            "expression": "SELECTEDVALUE( 'BvA% KPI'[BvA% KPI >], 1 )",
            "formatString": "0%;-0%;0%",
            "lineageTag": "cede8014-ce62-40e3-94d2-d7254ecb3847",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ]
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "97a0c1ddb5f7431cb1c839b2199c9b27"
          },
          {
            "name": "TabularEditor_TableGroup",
            "value": "disconnected"
          }
        ]
      },
      {
        "name": "budget versie",
        "lineageTag": "acca54ee-3ef3-4d34-b422-93168c8a4721",
        "columns": [
          {
            "name": "versie",
            "dataType": "string",
            "sourceColumn": "versie",
            "lineageTag": "461515e8-ea8b-4ac8-8736-807869eb3ec2",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "objecttype",
            "dataType": "string",
            "sourceColumn": "objecttype",
            "lineageTag": "47a3a89e-44a8-4292-b5c1-ae0948dd0a3c",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "compkey_versie",
            "dataType": "string",
            "sourceColumn": "compkey_versie",
            "lineageTag": "db05048b-740f-4501-9147-578e4b149ee1",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "budget versie-2cda912e-7da5-4ec0-8392-aa72ff914f6c",
            "mode": "import",
            "queryGroup": "Datalake",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = AmazonAthena.Databases(\"Simba Athena\", null),",
                "    AwsDataCatalog_Database = Source{[Name=\"AwsDataCatalog\",Kind=\"Database\"]}[Data],",
                "    analytics_nonprod_athena_Schema = AwsDataCatalog_Database{[Name=SourceAthena,Kind=\"Schema\"]}[Data],",
                "    dim_opdata_fin_ytd_bestelbon_Table = analytics_nonprod_athena_Schema{[Name=\"dim_opdata_fin_ytd_versie_budget\",Kind=\"Table\"]}[Data],",
                "    #\"Sorted Rows\" = Table.Sort(dim_opdata_fin_ytd_bestelbon_Table,{{\"versie\", Order.Ascending}})",
                "in",
                "    #\"Sorted Rows\""
              ]
            }
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          },
          {
            "name": "TabularEditor_TableGroup",
            "value": "dimension"
          }
        ]
      },
      {
        "name": "object",
        "lineageTag": "59c39a04-f5ca-4119-8d6e-caa7d30735b9",
        "columns": [
          {
            "type": "calculated",
            "name": "path",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "path('object'[object_id], 'object'[object_parent])",
            "displayFolder": "Object",
            "lineageTag": "aa432f66-beed-442c-9c0d-5f784d7441f9",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "depth",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "PATHLENGTH( object[path] )",
            "formatString": "0",
            "displayFolder": "ParentChild",
            "lineageTag": "bdef3354-939c-4add-bff5-90f6b9e81a9e",
            "summarizeBy": "sum",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Level1",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": [
              "",
              "VAR LevelNumber = 1",
              "VAR LevelKey = PATHITEM ( object[path], LevelNumber )",
              "VAR LevelName = LOOKUPVALUE ( object[object_id], object[object_id], LevelKey ) & \" \" & LOOKUPVALUE ( object[object_description], object[object_id], LevelKey )",
              "VAR Result = LevelName",
              "RETURN",
              "if(",
              "    Result = \" \"",
              "    ,",
              "    \"nvt_\" & object[objecttype],",
              "    Result",
              ")"
            ],
            "displayFolder": "Hierarchy\\Code",
            "lineageTag": "294e729d-60de-45c1-a088-53cc51c59e5f",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Directie",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": [
              "",
              "VAR LevelNumber = 2",
              "VAR LevelKey = PATHITEM ( object[path], LevelNumber )",
              "VAR LevelName = LOOKUPVALUE ( object[object_id], object[object_id], LevelKey ) & \" \" & LOOKUPVALUE ( object[object_description], object[object_id], LevelKey )",
              "VAR Result = LevelName",
              "RETURN",
              "if(",
              "    Result = \" \"",
              "    ,",
              "    \"nvt_\" & object[objecttype],",
              "    Result",
              ")"
            ],
            "displayFolder": "Hierarchy\\Code",
            "lineageTag": "16681844-e0bb-44ea-91b7-f6cfcad4983a",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Level3",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": [
              "",
              "VAR LevelNumber = 3",
              "VAR LevelKey = PATHITEM ( object[path], LevelNumber )",
              "VAR LevelName = LOOKUPVALUE ( object[object_id], object[object_id], LevelKey ) & \" \" & LOOKUPVALUE ( object[object_description], object[object_id], LevelKey )",
              "VAR Result = LevelName",
              "RETURN",
              "if(",
              "    Result = \" \"",
              "    ,",
              "    \"nvt_\" & object[objecttype],",
              "    Result",
              ")"
            ],
            "displayFolder": "Hierarchy\\Code",
            "lineageTag": "f069c120-f678-45db-8a78-19271711559d",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Level4",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": [
              "",
              "VAR LevelNumber = 4",
              "VAR LevelKey = PATHITEM ( object[path], LevelNumber )",
              "VAR LevelName = LOOKUPVALUE ( object[object_id], object[object_id], LevelKey ) & \" \" & LOOKUPVALUE ( object[object_description], object[object_id], LevelKey )",
              "VAR Result = LevelName",
              "RETURN",
              "if(",
              "    Result = \" \"",
              "    ,",
              "    \"nvt_\" & object[objecttype],",
              "    Result",
              ")"
            ],
            "displayFolder": "Hierarchy\\Code",
            "lineageTag": "ecffea0d-6d46-4ea8-bced-d3f5775d4363",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Level5",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": [
              "",
              "VAR LevelNumber = 5",
              "VAR LevelKey = PATHITEM ( object[path], LevelNumber )",
              "VAR LevelName = LOOKUPVALUE ( object[object_id], object[object_id], LevelKey ) & \" \" & LOOKUPVALUE ( object[object_description], object[object_id], LevelKey )",
              "VAR Result = LevelName",
              "RETURN",
              "if(",
              "    Result = \" \"",
              "    ,",
              "    \"nvt_\" & object[objecttype],",
              "    Result",
              ")"
            ],
            "displayFolder": "Hierarchy\\Code",
            "lineageTag": "25b2d153-c297-4eeb-ae0c-e9c7aad9a443",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Level6",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": [
              "",
              "VAR LevelNumber = 6",
              "VAR LevelKey = PATHITEM ( object[path], LevelNumber )",
              "VAR LevelName = LOOKUPVALUE ( object[object_id], object[object_id], LevelKey ) & \" \" & LOOKUPVALUE ( object[object_description], object[object_id], LevelKey )",
              "VAR Result = LevelName",
              "RETURN",
              "if(",
              "    Result = \" \"",
              "    ,",
              "    \"nvt_\" & object[objecttype],",
              "    Result",
              ")"
            ],
            "displayFolder": "Hierarchy\\Code",
            "lineageTag": "4560dc99-8ed6-449d-9b2d-7c171b03cbbd",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "objecttype",
            "dataType": "string",
            "sourceColumn": "objecttype",
            "displayFolder": "Object",
            "lineageTag": "1007822c-2fa8-40e2-aead-7ccdecc8a8bb",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "object+omschrijving",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "object[object_id] & \" \" & object[object_description]",
            "displayFolder": "Object",
            "lineageTag": "b88364ac-9232-4a27-bd60-a4bf6bc7cd8e",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "object_id",
            "dataType": "string",
            "sourceColumn": "object_id",
            "displayFolder": "Object",
            "lineageTag": "34f73865-5f46-4bbb-bd5b-d79cee437e65",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "object_description",
            "dataType": "string",
            "sourceColumn": "object_description",
            "displayFolder": "Object",
            "lineageTag": "63c6cda8-b5fd-469b-84c9-c3c8a7cfbb49",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "object_parent",
            "dataType": "string",
            "sourceColumn": "object_parent",
            "displayFolder": "Object",
            "lineageTag": "34a934d7-b435-4cd8-ac19-4f9d17618798",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "1",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": [
              "",
              "VAR LevelNumber = 1",
              "VAR LevelKey = PATHITEM ( object[path], LevelNumber )",
              "VAR LevelName = LOOKUPVALUE ( object[object_description], object[object_id], LevelKey )",
              "RETURN",
              "if(",
              "    isblank(LevelName) || LevelName = \" \",",
              "    \"nvt_\" & object[objecttype],",
              "    LevelName",
              ")"
            ],
            "sortByColumn": "1sort",
            "displayFolder": "Hierarchy\\No_Code",
            "lineageTag": "dcc695b2-9426-4b79-8e56-f17afc264914",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              },
              {
                "property": "SortByColumn"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "2",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": [
              "",
              "VAR LevelNumber = 2",
              "VAR LevelKey = PATHITEM ( object[path], LevelNumber )",
              "VAR LevelName = LOOKUPVALUE ( object[object_description], object[object_id], LevelKey )",
              "RETURN",
              "if(",
              "    isblank(LevelName) || LevelName = \" \",",
              "    \"nvt_\" & object[objecttype],",
              "    LevelName",
              ")"
            ],
            "sortByColumn": "2sort",
            "displayFolder": "Hierarchy\\No_Code",
            "lineageTag": "b6e7c635-c0c0-4ed4-918b-3c52d06b5d71",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              },
              {
                "property": "SortByColumn"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "3",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": [
              "",
              "VAR LevelNumber = 3",
              "VAR LevelKey = PATHITEM ( object[path], LevelNumber )",
              "VAR LevelName = LOOKUPVALUE ( object[object_description], object[object_id], LevelKey )",
              "VAR LevelNameSpecial = LOOKUPVALUE ( object[object_id], object[object_id], LevelKey ) & \" \" & LOOKUPVALUE ( object[object_description], object[object_id], LevelKey )",
              "-- er zijn wat gevallen (bijvoorbeeld oude KP's) die voor eenzelfde beschrijving meerdere KP's hebben waardoor je niet kan sorteren",
              "-- effciëntse oplossing zou zijn deze gevallen er uit te filteren, maar dat mag niet omdat de business wil kunnen nagaan of er zaken verkeerd (verouderd) geboekt zijn",
              "-- oplossing: kp voor de beschrijving toevoegen zodat je wel kan filteren zonder te verwijderen",
              "VAR Result =",
              "if(",
              "    object[objecttype] = \"PO\" || object[object_parent_NC] = \"X\",",
              "    LevelNameSpecial,",
              "    LevelName",
              ")",
              "RETURN",
              "if(",
              "    isblank(Result) || Result = \" \",",
              "    \"nvt_\" & object[objecttype],",
              "    Result",
              ")"
            ],
            "sortByColumn": "3sort",
            "displayFolder": "Hierarchy\\No_Code",
            "lineageTag": "6d84f796-9d78-474c-af29-601400c7a5c0",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              },
              {
                "property": "SortByColumn"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "4",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": [
              "",
              "VAR LevelNumber = 4",
              "VAR LevelKey = PATHITEM ( object[path], LevelNumber )",
              "VAR LevelName = LOOKUPVALUE ( object[object_description], object[object_id], LevelKey )",
              "VAR LevelNameSpecial = LOOKUPVALUE ( object[object_id], object[object_id], LevelKey ) & \" \" & LOOKUPVALUE ( object[object_description], object[object_id], LevelKey )",
              "-- er zijn wat gevallen (bijvoorbeeld oude KP's) die voor eenzelfde beschrijving meerdere KP's hebben waardoor je niet kan sorteren",
              "-- effciëntse oplossing zou zijn deze gevallen er uit te filteren, maar dat mag niet omdat de business wil kunnen nagaan of er zaken verkeerd (verouderd) geboekt zijn",
              "-- oplossing: kp voor de beschrijving toevoegen zodat je wel kan filteren zonder te verwijderen",
              "VAR Result =",
              "if(",
              "    object[objecttype] = \"PO\" || object[object_parent_NC] = \"X\",",
              "    LevelNameSpecial,",
              "    LevelName",
              ")",
              "RETURN",
              "if(",
              "    isblank(Result) || Result = \" \",",
              "    \"nvt_\" & object[objecttype],",
              "    Result",
              ")"
            ],
            "sortByColumn": "4sort",
            "displayFolder": "Hierarchy\\No_Code",
            "lineageTag": "52792b7b-03ad-4821-9748-7f8fa96452cf",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              },
              {
                "property": "SortByColumn"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "5",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": [
              "",
              "VAR LevelNumber = 5",
              "VAR LevelKey = PATHITEM ( object[path], LevelNumber )",
              "VAR LevelName = LOOKUPVALUE ( object[object_description], object[object_id], LevelKey )",
              "VAR LevelNameSpecial = LOOKUPVALUE ( object[object_id], object[object_id], LevelKey ) & \" \" & LOOKUPVALUE ( object[object_description], object[object_id], LevelKey )",
              "-- er zijn wat gevallen (bijvoorbeeld oude KP's) die voor eenzelfde beschrijving meerdere KP's hebben waardoor je niet kan sorteren",
              "-- effciëntse oplossing zou zijn deze gevallen er uit te filteren, maar dat mag niet omdat de business wil kunnen nagaan of er zaken verkeerd (verouderd) geboekt zijn",
              "-- oplossing: kp voor de beschrijving toevoegen zodat je wel kan filteren zonder te verwijderen",
              "VAR Result =",
              "if(",
              "    object[objecttype] = \"PO\" || object[object_parent_NC] = \"X\",",
              "    LevelNameSpecial,",
              "    LevelName",
              ")",
              "RETURN",
              "if(",
              "    isblank(Result) || Result = \" \",",
              "    \"nvt_\" & object[objecttype],",
              "    Result",
              ")"
            ],
            "displayFolder": "Hierarchy\\No_Code",
            "lineageTag": "15c55a0f-08f1-4c89-b1f1-8954b8bd77d4",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "6",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": [
              "",
              "VAR LevelNumber = 6",
              "VAR LevelKey = PATHITEM ( object[path], LevelNumber )",
              "VAR LevelName = LOOKUPVALUE ( object[object_description], object[object_id], LevelKey )",
              "VAR LevelNameSpecial = LOOKUPVALUE ( object[object_id], object[object_id], LevelKey ) & \" \" & LOOKUPVALUE ( object[object_description], object[object_id], LevelKey )",
              "-- er zijn wat gevallen (bijvoorbeeld oude KP's) die voor eenzelfde beschrijving meerdere KP's hebben waardoor je niet kan sorteren",
              "-- effciëntse oplossing zou zijn deze gevallen er uit te filteren, maar dat mag niet omdat de business wil kunnen nagaan of er zaken verkeerd (verouderd) geboekt zijn",
              "-- oplossing: kp voor de beschrijving toevoegen zodat je wel kan filteren zonder te verwijderen",
              "VAR Result =",
              "if(",
              "    object[objecttype] = \"PO\" || object[object_parent_NC] = \"X\",",
              "    LevelNameSpecial,",
              "    LevelName",
              ")",
              "RETURN",
              "if(",
              "    isblank(Result) || Result = \" \",",
              "    \"nvt_\" & object[objecttype],",
              "    Result",
              ")"
            ],
            "displayFolder": "Hierarchy\\No_Code",
            "lineageTag": "e3ccc5f8-a7a7-4f23-835b-fae9dddb85b9",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "1sort",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": [
              "",
              "VAR LevelNumber = 1",
              "VAR LevelKey = PATHITEM ( object[path], LevelNumber )",
              "VAR LevelName = LOOKUPVALUE ( object[index_nc], object[object_id], LevelKey )",
              "VAR Result = LevelName",
              "RETURN",
              "Result"
            ],
            "formatString": "0",
            "displayFolder": "Hierarchy\\No_Code",
            "lineageTag": "507c9046-e93e-4699-be46-06fc94c98f93",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "2sort",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": [
              "",
              "VAR LevelNumber = 2",
              "VAR LevelKey = PATHITEM ( object[path], LevelNumber )",
              "VAR LevelName = LOOKUPVALUE ( object[index_nc], object[object_id], LevelKey )",
              "VAR Result = LevelName",
              "RETURN",
              "Result"
            ],
            "formatString": "0",
            "displayFolder": "Hierarchy\\No_Code",
            "lineageTag": "34e17483-c5d7-44e2-97c1-bc2be88ee21b",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "3sort",
            "dataType": "string",
            "isHidden": true,
            "expression": [
              "",
              "VAR LevelNumber = 3",
              "VAR LevelKey = PATHITEM ( object[path], LevelNumber )",
              "VAR LevelName = LOOKUPVALUE ( object[index_nc], object[object_id], LevelKey )",
              "VAR Result = LevelName",
              "RETURN",
              "if(",
              "    isblank(Result),",
              "    \"nvt_\" & object[objecttype],",
              "    Result",
              ")"
            ],
            "displayFolder": "Hierarchy\\No_Code",
            "lineageTag": "12892b0a-05dc-49e4-a7b0-ff927e871f9a",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "DataType"
              },
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "4sort",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": [
              "",
              "VAR LevelNumber = 4",
              "VAR LevelKey = PATHITEM ( object[path], LevelNumber )",
              "VAR LevelName = LOOKUPVALUE ( object[index_nc], object[object_id], LevelKey )",
              "VAR Result = LevelName",
              "RETURN",
              "if(",
              "    isblank(Result),",
              "    \"nvt_\" & object[objecttype],",
              "    Result",
              ")"
            ],
            "displayFolder": "Hierarchy\\No_Code",
            "lineageTag": "56f06695-0368-46ff-9091-d3e853f0691a",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "5sort",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": [
              "",
              "VAR LevelNumber = 5",
              "VAR LevelKey = PATHITEM ( object[path], LevelNumber )",
              "VAR LevelName = LOOKUPVALUE ( object[index_nc], object[object_id], LevelKey )",
              "VAR Result = LevelName",
              "RETURN",
              "if(",
              "    isblank(Result),",
              "    \"nvt_\" & object[objecttype],",
              "    Result",
              ")"
            ],
            "displayFolder": "Hierarchy\\No_Code",
            "lineageTag": "82b7f8a2-573e-4189-a014-f529da7e0dfb",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "6sort",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": [
              "",
              "VAR LevelNumber = 6",
              "VAR LevelKey = PATHITEM ( object[path], LevelNumber )",
              "VAR LevelName = LOOKUPVALUE ( object[index_nc], object[object_id], LevelKey )",
              "VAR Result = LevelName",
              "RETURN",
              "if(",
              "    isblank(Result),",
              "    \"nvt_\" & object[objecttype],",
              "    Result",
              ")"
            ],
            "displayFolder": "Hierarchy\\No_Code",
            "lineageTag": "74679070-de90-4f6a-8696-fb163bdbb8bb",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "object_id_nc",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "object_id_nc",
            "displayFolder": "ParentChild",
            "lineageTag": "026cf2e2-0949-4dc9-8419-3dd43db0edb0",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "object_parent_nc",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "object_parent_nc",
            "displayFolder": "ParentChild",
            "lineageTag": "ee56ae0b-17a7-4219-a398-f14f77c802d5",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "index_nc",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "index_nc",
            "displayFolder": "Hierarchy\\No_Code",
            "lineageTag": "a8744b59-a0bc-4c25-aa2a-e574f4ad319e",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "artikel",
            "dataType": "string",
            "sourceColumn": "artikel",
            "displayFolder": "Artikel",
            "lineageTag": "25dd935e-4e36-42e9-b3e7-53b2e79870b7",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "productiehuis",
            "dataType": "string",
            "sourceColumn": "productiehuis",
            "displayFolder": "Artikel",
            "lineageTag": "60717082-76f1-4ba5-8341-01d0b144f52b",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "categorie",
            "dataType": "string",
            "sourceColumn": "categorie",
            "displayFolder": "Artikel",
            "lineageTag": "0ebcb25a-c23a-46a7-a1e1-27c9f20fbc73",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "kanaal",
            "dataType": "string",
            "sourceColumn": "kanaal",
            "displayFolder": "Artikel",
            "lineageTag": "b4f5d6fd-32a0-4b90-93c9-f68b43e1fa1a",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "productiereeks_fin_rapport",
            "dataType": "string",
            "sourceColumn": "productiereeks_fin_rapport",
            "displayFolder": "Artikel",
            "lineageTag": "25f81c51-aae1-4428-beb8-a1aad0f75c1e",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "subgenre",
            "dataType": "string",
            "sourceColumn": "subgenre",
            "displayFolder": "Artikel",
            "lineageTag": "42b5b0a6-5c1e-4e8b-9646-a01113daea12",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "klant",
            "dataType": "string",
            "sourceColumn": "klant",
            "displayFolder": "Artikel",
            "lineageTag": "9ec161ec-bde7-4a49-8ef7-e0ebc0865612",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "ipro_epro",
            "dataType": "string",
            "sourceColumn": "ipro_epro",
            "displayFolder": "Artikel",
            "lineageTag": "ed8adc87-fd2e-41df-b47b-8968dccb33c9",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "budgetbeheer_std",
            "dataType": "string",
            "sourceColumn": "budgetbeheer_std",
            "displayFolder": "Artikel",
            "lineageTag": "ad5110fa-9a66-4433-9ff8-f649ad3a97ba",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "budgetbeheer_plp",
            "dataType": "string",
            "sourceColumn": "budgetbeheer_plp",
            "displayFolder": "Artikel",
            "lineageTag": "bb9723d4-141a-450b-b413-719a1c18dd4c",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "raamovereenkomst",
            "dataType": "string",
            "sourceColumn": "raamovereenkomst",
            "displayFolder": "Artikel",
            "lineageTag": "5e95dead-3470-4e5c-b791-2444b5d7f0c5",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "netproducent",
            "dataType": "string",
            "sourceColumn": "netproducent",
            "displayFolder": "Artikel",
            "lineageTag": "c83bf1da-a3af-43b0-aae0-deacd84ddda2",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "beschrijving_artikel_uppercase",
            "dataType": "string",
            "sourceColumn": "beschrijving_artikel_uppercase",
            "displayFolder": "Artikel",
            "lineageTag": "5abd7e68-2e8c-4069-bb64-640204b6d56b",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "object-cc144e32-017c-4a7b-a730-f60db3f9b65e",
            "mode": "import",
            "queryGroup": "Datalake",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = AmazonAthena.Databases(\"Simba Athena\", null),",
                "    AwsDataCatalog_Database = Source{[Name=\"AwsDataCatalog\",Kind=\"Database\"]}[Data],",
                "    analytics_nonprod_athena_Schema = AwsDataCatalog_Database{[Name=SourceAthena,Kind=\"Schema\"]}[Data],",
                "    dim_opdata_fin_ytd_object_joinkpoppo_Table = analytics_nonprod_athena_Schema{[Name=\"dim_opdata_fin_ytd_object\",Kind=\"Table\"]}[Data],",
                "    #\"Replaced Value1\" = Table.ReplaceValue(dim_opdata_fin_ytd_object_joinkpoppo_Table,\"\",null,Replacer.ReplaceValue,{\"object_parent\"}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Replaced Value1\",{{\"index_nc\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "RowDepth",
            "description": "MAX( object[depth] ) - 1",
            "expression": "MAX( object[depth] ) - 1",
            "formatString": "0",
            "isHidden": true,
            "displayFolder": "ParentChild",
            "lineageTag": "1db2400e-7b20-462e-9549-b8ff05ece440"
          },
          {
            "name": "BrowseDepth",
            "description": [
              "ISINSCOPE( object[Level1] ) + ISINSCOPE( object[Directie] )",
              "    + ISINSCOPE( object[Level3] )",
              "    + ISINSCOPE( object[Level4] )",
              "    + ISINSCOPE( object[Level5] )",
              "    + ISINSCOPE( object[Level6] )"
            ],
            "expression": [
              "ISINSCOPE( object[Level1] ) + ISINSCOPE( object[Directie] )",
              "    + ISINSCOPE( object[Level3] )",
              "    + ISINSCOPE( object[Level4] )",
              "    + ISINSCOPE( object[Level5] )",
              "    + ISINSCOPE( object[Level6] )",
              "    + ISINSCOPE( object[1] )",
              "    + ISINSCOPE( object[2] )",
              "    + ISINSCOPE( object[3] )",
              "    + ISINSCOPE( object[4] )",
              "    + ISINSCOPE( object[5] )",
              "    + ISINSCOPE( object[6] )"
            ],
            "formatString": "0",
            "isHidden": true,
            "displayFolder": "ParentChild",
            "lineageTag": "cd713c28-9018-4dc9-8762-6dada0bc0d65",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ]
          },
          {
            "name": "path min",
            "description": [
              "VAR mindepth = MIN( object[depth] )",
              "VAR minpath =",
              "    CALCULATE(",
              "        SELECTEDVALUE( object[path] ),",
              "        object[depth] = mindepth",
              "    )",
              "RETURN",
              "    minpath"
            ],
            "expression": [
              "VAR mindepth = MIN( object[depth] )",
              "VAR minpath =",
              "    CALCULATE(",
              "        SELECTEDVALUE( object[path] ),",
              "        object[depth] = mindepth",
              "    )",
              "RETURN",
              "    minpath"
            ],
            "isHidden": true,
            "displayFolder": "ParentChild",
            "lineageTag": "489b9228-c848-4c04-a812-559c8056736c"
          },
          {
            "name": "BrowseDepthNoCode",
            "expression": [
              "ISINSCOPE( object[1] ) + ISINSCOPE( object[2] )",
              "    + ISINSCOPE( object[3] )",
              "    + ISINSCOPE( object[4] )",
              "    + ISINSCOPE( object[5] )",
              "    + ISINSCOPE( object[6] )"
            ],
            "formatString": "0",
            "isHidden": true,
            "displayFolder": "ParentChild",
            "lineageTag": "848b21e1-d5fb-47df-b84b-4050a2f98515",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ]
          },
          {
            "name": "3 count",
            "expression": "COUNT( object[5sort] )",
            "formatString": "0",
            "isHidden": true,
            "displayFolder": "Hierarchy\\No_Code",
            "lineageTag": "da0aa910-3c44-4dc1-9d96-806380c177de"
          }
        ],
        "hierarchies": [
          {
            "name": "Object Hierarchy",
            "displayFolder": "Hierarchy\\Code",
            "lineageTag": "cc2e1cfd-d52b-4dae-bae4-fef14cc5d960",
            "levels": [
              {
                "name": "Directie",
                "ordinal": 0,
                "column": "Directie",
                "lineageTag": "f721d4da-34bb-4afe-88ef-b0eb7fd18e4f"
              },
              {
                "name": "Level3",
                "ordinal": 1,
                "column": "Level3",
                "lineageTag": "f604e84a-831b-46c0-8336-5835f517245b"
              },
              {
                "name": "Level4",
                "ordinal": 2,
                "column": "Level4",
                "lineageTag": "01ef2355-32df-4953-a802-a930b3413cb6"
              },
              {
                "name": "Level5",
                "ordinal": 3,
                "column": "Level5",
                "lineageTag": "429074a4-688e-460f-b546-08c7ee534045"
              },
              {
                "name": "Level6",
                "ordinal": 4,
                "column": "Level6",
                "lineageTag": "f2e14692-6370-40de-b167-5bff0bd108b3"
              }
            ]
          },
          {
            "name": "Object Hierarchy basic",
            "displayFolder": "Hierarchy\\Code",
            "lineageTag": "590927fb-03f0-4e03-a1f8-fb4944dfe67f",
            "levels": [
              {
                "name": "Directie",
                "ordinal": 0,
                "column": "Directie",
                "lineageTag": "eb3c0e20-9803-4cdd-8742-0167176d9b0d"
              },
              {
                "name": "Level3",
                "ordinal": 1,
                "column": "Level3",
                "lineageTag": "f5f91021-2c6d-4c22-8ce5-ac588413d58a"
              },
              {
                "name": "object+omschrijving",
                "ordinal": 2,
                "column": "object+omschrijving",
                "lineageTag": "7417b873-56f8-41a6-8ef5-84cf0ce1727c"
              }
            ]
          },
          {
            "name": "Object Hierarchy no code",
            "isHidden": true,
            "displayFolder": "Hierarchy\\No_Code",
            "lineageTag": "96145836-0e2a-41e7-8576-28c61bf3ba7c",
            "levels": [
              {
                "name": "1",
                "ordinal": 0,
                "column": "1",
                "lineageTag": "41618c40-d2df-4333-a7ea-050137a43d1e"
              },
              {
                "name": "2",
                "ordinal": 1,
                "column": "2",
                "lineageTag": "4ae5417d-cc45-4c4e-b886-1325f22341e4"
              },
              {
                "name": "3",
                "ordinal": 2,
                "column": "3",
                "lineageTag": "6e7856e4-282e-45d8-bbd5-b12dab6efa56"
              },
              {
                "name": "4",
                "ordinal": 3,
                "column": "4",
                "lineageTag": "274826c7-f2e3-47e0-a05e-771b41d3d771"
              },
              {
                "name": "5",
                "ordinal": 4,
                "column": "5",
                "lineageTag": "62304439-fffb-436e-8456-b01da64fca73"
              },
              {
                "name": "6",
                "ordinal": 5,
                "column": "6",
                "lineageTag": "47fcfe8b-b637-43d5-bb64-0dd5a60170d3"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          },
          {
            "name": "TabularEditor_TableGroup",
            "value": "dimension"
          }
        ]
      },
      {
        "name": "switch_ytd",
        "lineageTag": "54b70b49-0771-47f8-9a33-91537e9d2274",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Filter YTD",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[Value1]",
            "sortByColumn": "value",
            "lineageTag": "18f86490-49f7-4430-8623-be9969b38c07",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "value",
            "dataType": "int64",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[Value2]",
            "formatString": "0",
            "lineageTag": "7fdb6244-7f9e-47dc-a822-005b4ec4dae0",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Keuze",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[Value3]",
            "lineageTag": "e8d59c58-6d97-40b6-b208-2ef28c276b46",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Keuze zonder obligo",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[Value4]",
            "lineageTag": "b62b499d-7266-4c1f-89aa-a9f017edd52f",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "switch_ytd-9da66cf0-643c-4f92-a23a-ecfca493c442",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "{",
                "    (\"Jaarbasis\", 2, \"JAARBASIS : alle actuals en obligo's vs. het jaarbudget\", \"Alle actuals vs budget op jaarbasis\"),",
                "    --(\"alle actuals\", 2, \"Alle actuals dit jaar\", \"nvt\"),",
                "    (\"Afgesloten periode\", 1, \"AFGESLOTEN PERIODE: actuals YTD vs budget YTD\", \"Afgesloten actuals vs budget YTD\")",
                "}"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "keuze header",
            "expression": [
              "SELECTEDVALUE( switch_ytd[Keuze] ) & \": \"",
              "    & SELECTEDVALUE( object[objecttype] )"
            ],
            "lineageTag": "e8554279-6407-4e32-8eb8-8447d9ebbc82",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "keuze header 2 zonder :",
            "expression": [
              "SELECTEDVALUE( switch_ytd[Keuze zonder obligo] ) & \" (\"",
              "    & MAX( 'date'[Year] )",
              "    & \" v\"",
              "    & MAX( 'budget versie'[versie] )",
              "    & \"), \"",
              "    & SWITCH(",
              "        SELECTEDVALUE( weergave_getal[Weergave getal] ),",
              "        \"1.000.000,00\", \"uitgedrukt in M\",",
              "        \"1.000.000\", \"uitgedrukt in M\",",
              "        \"1.000,00\", \"uitgedrukt in K\",",
              "        \"1.000,00\", \"uitgedrukt in K\",",
              "        \"1,00\", \"uitgedrukt in euro\",",
              "        \"1\", \"uitgedrukt in euro\",",
              "        BLANK( )",
              "    )"
            ],
            "lineageTag": "5775937d-da0d-4ade-8547-86b9e24472f6",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "switchytd",
            "expression": "MIN( switch_ytd[value] )",
            "lineageTag": "ddb8d903-f8cc-49f9-a919-56816b7cf367",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "c85a23ba5044423785875fb2f44879a3"
          },
          {
            "name": "TabularEditor_TableGroup",
            "value": "disconnected"
          }
        ]
      },
      {
        "name": "par1_12",
        "lineageTag": "ba555278-fb0e-4273-a662-1cbb9c61edbf",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Parameter",
            "dataType": "int64",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[Value]",
            "formatString": "0",
            "lineageTag": "352da7f7-1b27-4f61-9627-d2148b4e12c5",
            "summarizeBy": "none",
            "extendedProperties": [
              {
                "type": "json",
                "name": "ParameterMetadata",
                "value": {
                  "version": 0
                }
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "budget is gelijk aan actuals tot maand",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": [
              "",
              "SWITCH(",
              "    par1_12[Parameter],",
              "    1, \"budget pas zich niet aan\",",
              "    2, \"2. februari\",",
              "    3, \"3. maart\",",
              "    4, \"4. april\",",
              "    5, \"5. mei\",",
              "    6, \"6. juni\",",
              "    7, \"7. juli\",",
              "    8, \"8. augustus\",",
              "    9, \"9. september\",",
              "    10, \"10. oktober\",",
              "    11, \"11. november\",",
              "    12, \"12. december\"",
              ")",
              ""
            ],
            "sortByColumn": "Parameter",
            "lineageTag": "7a20b844-d51d-422f-bc48-66505db7fbfe",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "adaptief budget tot maand",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": [
              "",
              "SWITCH(",
              "    par1_12[Parameter],",
              "    1, \"budget pas zich niet aan\",",
              "    2, \"februari\",",
              "    3, \"maart\",",
              "    4, \"april\",",
              "    5, \"mei\",",
              "    6, \"juni\",",
              "    7, \"juli\",",
              "    8, \"augustus\",",
              "    9, \"september\",",
              "    10, \"oktober\",",
              "    11, \"november\",",
              "    12, \"december\"",
              ")",
              ""
            ],
            "sortByColumn": "Parameter",
            "lineageTag": "ea3f4a77-1b0b-4c71-bf72-c520924647e8",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "par1_12-402b5a3e-f85d-48d2-8cef-16f6f74bf384",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": "GENERATESERIES(1, 12, 1)"
            }
          }
        ],
        "measures": [
          {
            "name": "Parameter Value",
            "description": "SELECTEDVALUE( par1_12[Parameter], 6 )",
            "expression": "SELECTEDVALUE( par1_12[Parameter], 1 ) - 1",
            "formatString": "0",
            "lineageTag": "0bf71be7-d7b5-406c-ba64-c0457b12daf2",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ]
          },
          {
            "name": "Vanaf wanneer adaptief?",
            "expression": "[Parameter Value]",
            "lineageTag": "ac8e5294-d99a-44d9-8daa-2c02197161b9"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "103388d65b284de69a49f25abde22a0f"
          },
          {
            "name": "TabularEditor_TableGroup",
            "value": "disconnected"
          }
        ]
      },
      {
        "name": "switch_KPI",
        "lineageTag": "d56b0e10-9969-4fae-89cc-d6c66c2e0cd5",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "KPI",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[Value1]",
            "sortByColumn": "Value",
            "lineageTag": "77791aae-2442-4439-8544-af484a575ba0",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Value",
            "dataType": "int64",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[Value2]",
            "formatString": "0",
            "lineageTag": "fea3a3fd-9654-4dc1-bf1f-0cb9152f3394",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "switch_KPI-ebdf638c-f6b1-4694-a9b2-70696b0a6bd8",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "{",
                "    (\"Beide\", 1),",
                "    (\"Delta\", 2),",
                "    (\"Delta%\", 3)",
                "}"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "KPI if",
            "description": [
              "SWITCH(",
              "    TRUE,",
              "    SELECTEDVALUE( switch_KPI[Value] ) = 1, [KPI both],",
              "    SELECTEDVALUE( switch_KPI[Value] ) = 2, [KPI abs],",
              "    SELECTEDVALUE( switch_KPI[Value] ) = 3, [KPI rel],",
              "    [KPI both]",
              ")"
            ],
            "expression": [
              "SWITCH(",
              "    TRUE,",
              "    SELECTEDVALUE( switch_KPI[Value] ) = 1, [KPI both],",
              "    SELECTEDVALUE( switch_KPI[Value] ) = 2, [KPI abs],",
              "    SELECTEDVALUE( switch_KPI[Value] ) = 3, [KPI rel],",
              "    [KPI both]",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "5a4408db-1ab4-410a-b6fc-81a43ee69929"
          },
          {
            "name": "KPI abs",
            "description": [
              "// deze KPI moet aangeven welke directie's toegelicht dienen te worden",
              "// bedoeling is dat je manueel de parameters hiervoor kan selecteren",
              "// waarde 2 komt overeen met hoogste alarm (rood), waar 1 met orangje, waarde 0 is ok",
              "VAR inputabs = [BvA KPI value]",
              "VAR inputrel = [BvA% KPI Value]",
              "VAR iflogic =",
              "    IF(",
              "        ABS( [BvA YTD last] ) > inputabs,",
              "        2,",
              "        IF( ABS( [BvA YTD last] ) > inputabs / 2, 1, BLANK( ) )",
              "    )",
              "RETURN",
              "    iflogic"
            ],
            "expression": [
              "VAR input_abs_2 = [BvA KPI value]",
              "VAR input_rel_2 = [BvA% KPI Value]",
              "VAR input_abs_1 = DIVIDE( input_abs_2, 2 )",
              "VAR input_rel_1 = DIVIDE( input_rel_2, 2 )",
              "VAR if_vw2 = ( ABS( [D YTD ss] ) > input_abs_2 )",
              "VAR if_vw1 = ( ABS( [D YTD ss] ) > input_abs_1 )",
              "VAR iflogic =",
              "    SWITCH(",
              "        TRUE( ),",
              "        if_vw2, 2,",
              "        if_vw1, 1,",
              "        BLANK( )",
              "    )",
              "RETURN",
              "    iflogic"
            ],
            "formatString": "0",
            "displayFolder": "switch_KPI",
            "lineageTag": "2a4da31d-b444-46dd-9823-aafc257cb56d"
          },
          {
            "name": "KPI both",
            "description": [
              "// deze KPI moet aangeven welke directie's toegelicht dienen te worden",
              "// bedoeling is dat je manueel de parameters hiervoor kan selecteren",
              "// waarde 2 komt overeen met hoogste alarm (rood), waar 1 met orangje, waarde 0 is ok",
              "VAR inputabs = [BvA KPI value]",
              "VAR inputrel = [BvA% KPI Value]",
              "VAR iflogic =",
              "    IF(",
              "        AND(",
              "            ABS( [BvA YTD last] ) > inputabs,",
              "            ABS( [BvA% YTD] ) > inputrel",
              "        ),",
              "        2,",
              "        IF(",
              "            AND(",
              "                ABS( [BvA YTD last] ) > inputabs / 2,",
              "                ABS( [BvA% YTD] ) > inputrel / 2",
              "            ),",
              "            1,",
              "            BLANK( )",
              "        )",
              "    )",
              "RETURN",
              "    iflogic"
            ],
            "expression": [
              "VAR input_abs_2 = [BvA KPI value]",
              "VAR input_rel_2 = [BvA% KPI Value]",
              "VAR input_abs_1 = DIVIDE( input_abs_2, 2 )",
              "VAR input_rel_1 = DIVIDE( input_rel_2, 2 )",
              "VAR if_vw2 =",
              "    AND(",
              "        ABS( [D YTD ss] ) > input_abs_2,",
              "        ABS( [D% YTD ss] ) > input_rel_2",
              "    )",
              "VAR if_vw1 =",
              "    AND(",
              "        ABS( [D YTD ss] ) > input_abs_1,",
              "        ABS( [D% YTD ss] ) > input_rel_1",
              "    )",
              "VAR iflogic =",
              "    SWITCH(",
              "        TRUE( ),",
              "        if_vw2, 2,",
              "        if_vw1, 1,",
              "        BLANK( )",
              "    )",
              "RETURN",
              "    iflogic"
            ],
            "formatString": "0",
            "displayFolder": "switch_KPI",
            "lineageTag": "74872e43-d12a-4a2d-8737-f717790d5185"
          },
          {
            "name": "KPI rel",
            "description": [
              "// deze KPI moet aangeven welke directie's toegelicht dienen te worden",
              "// bedoeling is dat je manueel de parameters hiervoor kan selecteren",
              "// waarde 2 komt overeen met hoogste alarm (rood), waar 1 met orangje, waarde 0 is ok",
              "VAR inputabs = [BvA KPI value]",
              "VAR inputrel = [BvA% KPI Value]",
              "VAR iflogic =",
              "    IF(",
              "        ABS( [BvA% YTD] ) > inputrel,",
              "        2,",
              "        IF( ABS( [BvA% YTD] ) > inputrel / 2, 1, BLANK( ) )",
              "    )",
              "RETURN",
              "    iflogic"
            ],
            "expression": [
              "VAR input_abs_2 = [BvA KPI value]",
              "VAR input_rel_2 = [BvA% KPI Value]",
              "VAR input_abs_1 = DIVIDE( input_abs_2, 2 )",
              "VAR input_rel_1 = DIVIDE( input_rel_2, 2 )",
              "VAR if_vw2 = ( ABS( [D% YTD ss] ) > input_rel_2 )",
              "VAR if_vw1 = ( ABS( [D% YTD ss] ) > input_rel_1 )",
              "VAR iflogic =",
              "    SWITCH(",
              "        TRUE( ),",
              "        if_vw2, 2,",
              "        if_vw1, 1,",
              "        BLANK( )",
              "    )",
              "RETURN",
              "    iflogic"
            ],
            "formatString": "0",
            "displayFolder": "switch_KPI",
            "lineageTag": "abf5ac2a-c224-4a74-8496-bacce510a856"
          },
          {
            "name": "kpi test",
            "expression": [
              "",
              "VAR input_abs_2 = [BvA KPI value]",
              "VAR input_rel_2 = [BvA% KPI Value]",
              "VAR input_abs_1 = DIVIDE( input_abs_2, 2 )",
              "VAR input_rel_1 = DIVIDE( input_rel_2, 2 )",
              "VAR if_vw2 =",
              "    AND(",
              "        ABS( [D YTD ss] ) > input_abs_2,",
              "        ABS( [D% YTD ss] ) > input_rel_2",
              "    )",
              "VAR if_vw1 =",
              "    AND(",
              "        ABS( [D YTD ss] ) > input_abs_1,",
              "        ABS( [D% YTD ss] ) > input_rel_1",
              "    )",
              "VAR iflogic =",
              "    SWITCH(",
              "        TRUE( ),",
              "        if_vw2, 2,",
              "        if_vw1, 1,",
              "        BLANK( )",
              "    )",
              "VAR ShowRow =",
              "    OR(",
              "        [BrowseDepth] <= [RowDepth],",
              "        ISINSCOPE( 'dim resultatenrekening'[soort+beschrijving])",
              "    )",
              "VAR _scope = IF( ShowRow, iflogic )",
              "RETURN",
              "    _scope"
            ],
            "lineageTag": "18067835-e510-40c3-8a52-94f2556a4e67",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "48bf1301dbeb43e694ac4834ddf316ad"
          },
          {
            "name": "TabularEditor_TableGroup",
            "value": "disconnected"
          }
        ]
      },
      {
        "name": "opmerkingen",
        "lineageTag": "61cae0bd-85f3-4873-a0b0-0f41e178be61",
        "columns": [
          {
            "name": "object_id",
            "dataType": "string",
            "sourceColumn": "object_id",
            "lineageTag": "af209de8-e444-44e6-9877-c748450db7f9",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "datum",
            "dataType": "dateTime",
            "sourceColumn": "datum",
            "formatString": "Short Date",
            "lineageTag": "caaf62ff-dd2c-4766-a3c1-b464558c4053",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ]
          },
          {
            "name": "opmerking",
            "dataType": "string",
            "sourceColumn": "opmerking",
            "lineageTag": "47c885b5-0162-4395-abcd-de9c0ab13842",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "gebruiker",
            "dataType": "string",
            "sourceColumn": "gebruiker",
            "lineageTag": "35e9fde1-1284-4a51-8680-5d5155d5227d",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "yyyymm",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "format(opmerkingen[datum], \"yyyy-mm\")",
            "lineageTag": "dfa172f4-e634-43ff-8a66-bd2700aad41b",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "opmerkingen-d528eed7-2c10-4e68-8ce8-d8789899a1de",
            "mode": "import",
            "queryGroup": "Sharepoint\\Sharepoint YTD",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = SharePoint.Files(\"https://rto365.sharepoint.com/sites/FCO-14PowerBI2/\", [ApiVersion = 15]),",
                "    #\"Opmerkingen bij afwijkingen xlsx_https://rto365 sharepoint com/sites/FCO-14PowerBI2/Data Power BI/Financiële data/Opmerkingen/\" = Source{[Name=\"Opmerkingen bij afwijkingen.xlsx\",#\"Folder Path\"=\"https://rto365.sharepoint.com/sites/FCO-14PowerBI2/Data Power BI/Financiële data/Opmerkingen/\"]}[Content],",
                "    #\"Imported Excel Workbook\" = Excel.Workbook(#\"Opmerkingen bij afwijkingen xlsx_https://rto365 sharepoint com/sites/FCO-14PowerBI2/Data Power BI/Financiële data/Opmerkingen/\"),",
                "    Tabel1_Table = #\"Imported Excel Workbook\"{[Item=\"Tabel1\",Kind=\"Table\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Tabel1_Table,{{\"object_id\", type text}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "#opm.",
            "expression": [
              "",
              "VAR ShowRow = [BrowseDepth] <= [RowDepth]",
              "VAR iflogic = IF( ShowRow, COUNTROWS( opmerkingen ) )",
              "RETURN",
              "    iflogic"
            ],
            "formatString": "0",
            "lineageTag": "a444a329-a2a1-4a27-ba9f-d9b247f96a85",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ]
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "TabularEditor_TableGroup",
            "value": "dimension"
          }
        ]
      },
      {
        "name": "Tab now",
        "lineageTag": "efc4e4b9-271b-4b62-800a-12d1c76a0c48",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Datum",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Datum]",
            "formatString": "Short Date",
            "lineageTag": "8ccf163f-667b-4705-9460-7ec11d176617",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Tab now-5baac73c-4796-43dd-a8b2-53e0b4ff60d6",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": "Row(\"Datum\", Today())"
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "3adee386f5dd46999070a78a502d2207"
          },
          {
            "name": "TabularEditor_TableGroup",
            "value": "disconnected"
          }
        ]
      },
      {
        "name": "tab obligo",
        "lineageTag": "103c27a3-0d27-4e1b-a450-fa0e742cc8f9",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Value",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Value]",
            "formatString": "0",
            "lineageTag": "a11b4b46-3e90-4325-9646-0851c3946dc4",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Metric",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Metric]",
            "sortByColumn": "sort metric",
            "lineageTag": "ec77ce61-210c-4122-963b-f8e4a728991d",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Categorie metric",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Categorie metric]",
            "lineageTag": "01e544b0-9461-402b-84b9-8688fe77af38",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "sort cat",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[sort cat]",
            "formatString": "0",
            "lineageTag": "71b22641-cf23-43d3-8873-c65be1e3336c",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Categorie short metric",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Categorie short metric]",
            "sortByColumn": "sort short",
            "lineageTag": "ac61f15a-5245-4507-94c1-119099562c18",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "sort short",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[sort short]",
            "formatString": "0",
            "lineageTag": "e00973ca-2be0-4bfb-8611-d8ddb418d0cb",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "sort metric",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[sort metric]",
            "formatString": "0",
            "lineageTag": "2f099e9e-64ea-4865-b547-6ef2f927c624",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "tab obligo-a59e5537-bbc5-4778-bb2f-0f2f8746798d",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "SELECTCOLUMNS(",
                "{",
                "    (1, \"Actuals\",       \"Besteed\",  \"A\", 1, 1, 1),",
                "    (2, \"Obligo\",        \"Besteed\",  \"A\", 1, 1, 2),",
                "    (0, \"Actuals YTG\",   \"Besteed\",  \"A\", 1, 1, 3),",
                "    (3, \"Budget\",        \"Budget\",   \"B\", 0, 2, 4),",
                "    (4, \"Delta\",         \"Delta\",    \"∆\", 3, 3, 5),",
                "    (5, \"Delta%\",        \"Delta%\",   \"∆%\", 4, 4, 6)",
                "},",
                "\"Value\", [Value1],",
                "\"Metric\", [Value2],",
                "\"Categorie metric\", [Value3],",
                "\"Categorie short metric\", [Value4],",
                "\"sort cat\", [Value5],",
                "\"sort short\", [Value6],",
                "\"sort metric\", [Value7]",
                ")",
                ""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "switch obligo",
            "expression": [
              "VAR switcher =",
              "    SWITCH(",
              "        TRUE( ),",
              "        SELECTEDVALUE( 'tab obligo'[Value] ) = 0, [Besteed YTG ss],",
              "        SELECTEDVALUE( 'tab obligo'[Value] ) = 1, [Actuals],",
              "        SELECTEDVALUE( 'tab obligo'[Value] ) = 2, [obligo],",
              "        SELECTEDVALUE( 'tab obligo'[Value] ) = 3, [B YTD ss],",
              "        SELECTEDVALUE( 'tab obligo'[Value] ) = 4,",
              "            [B YTD ss] - [Actuals] - [obligo],",
              "        SELECTEDVALUE( 'tab obligo'[Value] ) = 5, [D% YTD ss yearb]",
              "    )",
              "VAR blancos = IF( ISBLANK( switcher ), 0, switcher )",
              "RETURN",
              "    blancos"
            ],
            "formatString": "#,0",
            "lineageTag": "e9cfc5cc-5c06-4870-a0ea-34ebac5ce5da",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ]
          },
          {
            "name": "switch obligo %",
            "expression": [
              "VAR switcher =",
              "    SWITCH(",
              "        TRUE( ),",
              "        SELECTEDVALUE( 'tab obligo'[Value] ) = 0, [Besteed YTG ss],",
              "        SELECTEDVALUE( 'tab obligo'[Value] ) = 1, [werkelijk],",
              "        SELECTEDVALUE( 'tab obligo'[Value] ) = 2, [obligo],",
              "        SELECTEDVALUE( 'tab obligo'[Value] ) = 3, [gew. budget],",
              "        SELECTEDVALUE( 'tab obligo'[Value] ) = 4,",
              "            [gew. budget] - [werkelijk] - [obligo],",
              "        SELECTEDVALUE( 'tab obligo'[Value] ) = 5, [D% YTD ss yearb]",
              "    )",
              "VAR blancos = IF( ISBLANK( switcher ), 0, switcher )",
              "RETURN",
              "    blancos"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "d9b2e118-968e-4ff7-8e8f-c2e9a75d3da4"
          },
          {
            "name": "Value selected",
            "expression": "SELECTEDVALUE( 'tab obligo'[Value] )",
            "lineageTag": "31073c3d-8d0d-4fba-9dd7-f5b9f965d31f",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "8b850f7da1a8413a9e2b90328c892cec"
          },
          {
            "name": "TabularEditor_TableGroup",
            "value": "disconnected"
          }
        ]
      },
      {
        "name": "field object",
        "lineageTag": "7ebea189-1bd5-4461-a6b9-3c1ea2385fc5",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "field object",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[Value1]",
            "sortByColumn": "field object Order",
            "lineageTag": "36e3780b-dbd7-4a14-b2fc-fe69eb3cb068",
            "summarizeBy": "none",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "field object Fields"
                }
              ]
            },
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "field object Fields",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[Value2]",
            "sortByColumn": "field object Order",
            "lineageTag": "5ee85bd9-8b47-45f3-a713-8d344c72a0c1",
            "summarizeBy": "none",
            "extendedProperties": [
              {
                "type": "json",
                "name": "ParameterMetadata",
                "value": {
                  "version": 3,
                  "kind": 2
                }
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "field object Order",
            "dataType": "int64",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[Value3]",
            "formatString": "0",
            "lineageTag": "92c5358a-e001-4daa-9ad2-cdfdae1aeeb1",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "weergave directiestructuur",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[Value4]",
            "lineageTag": "92946e3d-7063-44de-8991-eb80a86dc8f0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "field object-b3d21e29-3017-49ce-8140-df6406c4dc6e",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": [
                "{",
                "    --(\"1\", NAMEOF('object'[1]), 0, \"benaming\"),",
                "    (\"Directie\", NAMEOF('object'[2]), 1, \"benaming\"),",
                "    (\"3\", NAMEOF('object'[3]), 2, \"benaming\"),",
                "    (\"4\", NAMEOF('object'[4]), 3, \"benaming\"),",
                "    (\"5\", NAMEOF('object'[5]), 4, \"benaming\"),",
                "    (\"6\", NAMEOF('object'[6]), 5, \"benaming\"),",
                "    --(\"Level1\", NAMEOF('object'[Level1]), 6, \"code+benaming\"),",
                "    (\"Directie\", NAMEOF('object'[Directie]), 7, \"code+benaming\"),",
                "    (\"Level3\", NAMEOF('object'[Level3]), 8, \"code+benaming\"),",
                "    (\"Level4\", NAMEOF('object'[Level4]), 9, \"code+benaming\"),",
                "    (\"Level5\", NAMEOF('object'[Level5]), 10, \"code+benaming\"),",
                "    (\"Level6\", NAMEOF('object'[Level6]), 11, \"code+benaming\")",
                "}"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "af74f7b65a9b47eea4d7674f336e1b43"
          },
          {
            "name": "TabularEditor_TableGroup",
            "value": "field paramaters"
          }
        ]
      },
      {
        "name": "fct besteed",
        "lineageTag": "5afa8e26-3771-4edf-a407-19e93e032b87",
        "columns": [
          {
            "name": "object_id",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "object_id",
            "lineageTag": "e7dea6f2-fb46-4991-bd4b-34e0f674c2d0",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "objecttype",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "objecttype",
            "lineageTag": "c588bc49-9826-4d7d-a32a-05268712fbd8",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "boekdatum",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "boekdatum",
            "formatString": "Short Date",
            "lineageTag": "69b467d5-4e85-4fcf-92b2-163d1a2762dc",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ]
          },
          {
            "name": "yyyymm",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "yyyymm",
            "lineageTag": "5f42c457-399e-4e52-ad58-8f575e65911c",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "artikel_id",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "artikel_id",
            "lineageTag": "422f621c-d5b3-4b63-bf79-657c8e376044",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "soort_id",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "soort_id",
            "lineageTag": "e2a59588-47ba-4367-a1a6-19f09e16d38a",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "omschrijving",
            "dataType": "string",
            "sourceColumn": "omschrijving",
            "lineageTag": "c3a12938-5331-443d-9f45-6609e57c844f",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "actual",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "actual",
            "formatString": "#,0.00",
            "lineageTag": "9c125824-85f7-4eb6-8fa6-c74184e53ae2",
            "summarizeBy": "sum",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "obligo",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "obligo",
            "formatString": "#,0.00",
            "lineageTag": "34f47c78-a668-4fdb-9600-790726c924b3",
            "summarizeBy": "sum",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "bestelbon_id",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "bestelbon_id",
            "lineageTag": "be3f11ea-650d-4e6d-bf48-c492c2a5f2f1",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "termijnpositie",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "termijnpositie",
            "lineageTag": "25b8a142-a1d6-40ff-979f-c72be9ceeeab",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "import_date",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "import_date",
            "formatString": "Short Date",
            "lineageTag": "36e1d98d-66af-4944-bb78-3aa410934363",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ]
          },
          {
            "name": "a_o",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "a_o",
            "lineageTag": "b3841fe0-05b3-4c2b-8ecb-5bd895680819",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "rn",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "rn",
            "formatString": "0",
            "lineageTag": "1c80c722-4876-4a56-8ef0-734e64f4aa3f",
            "summarizeBy": "sum",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "soort_id_zonderalgkv",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "soort_id_zonderalgkv",
            "lineageTag": "20ff58b4-32a8-41b7-bdba-33a63dfefa91",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "af_pe_ytd",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "af_pe_ytd",
            "lineageTag": "65477810-3692-4c3d-8daf-b1226d818287",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "filterytd",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "filterytd",
            "lineageTag": "506602a9-6884-4011-9fec-5fc3c914c0e4",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "sleutelpnl switch",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": [
              "",
              "VAR _sleutel ='fct besteed'[object_id] & \"_\" & 'fct besteed'[soort_id_zonderalgkv] ",
              "VAR _switchlogic = ",
              "    SWITCH(",
              "        TRUE(),",
              "        LEFT('fct besteed'[object_id],3) in {\"RCA\",\"RTV\",\"RKE\",\"RNU\",\"RSP\", \"RNI\"}, LEFT('fct besteed'[object_id],3) & \"_\" & 'fct besteed'[soort_id_zonderalgkv],",
              "        LEFT('fct besteed'[object_id],1) in {\"M\", \"E\"}, LEFT('fct besteed'[object_id],3) & \"_\" & 'fct besteed'[soort_id_zonderalgkv],",
              "        _sleutel",
              "    )",
              "RETURN",
              "    _switchlogic"
            ],
            "lineageTag": "0cb8f778-a11d-4a16-aa25-cc3121e092c3",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "fct besteed-92c758fe-635b-47dd-aaf2-a1a340d779c4",
            "mode": "import",
            "queryGroup": "Datalake",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Bron = AmazonAthena.Databases(\"Simba Athena\", null),",
                "    AwsDataCatalog_Database = Bron{[Name=\"AwsDataCatalog\",Kind=\"Database\"]}[Data],",
                "    analytics_nonprod_athena_Schema = AwsDataCatalog_Database{[Name=SourceAthena,Kind=\"Schema\"]}[Data],",
                "    fct_opdata_fin_sap_besteed_Table = analytics_nonprod_athena_Schema{[Name=\"fct_opdata_fin_sap_besteed_filtercolumnadded\",Kind=\"Table\"]}[Data]",
                "in",
                "    fct_opdata_fin_sap_besteed_Table"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "actuals total",
            "expression": [
              "",
              "-- keuzeknop: enkel closed actuals of alle actuals + obligo's",
              "VAR filterytd = SELECTEDVALUE( switch_ytd[value], 1 )",
              "-- parent child hierarchy van dim object, je wil geen lege rijen tonen in de matrix",
              "VAR ShowRow =",
              "    OR(",
              "        [BrowseDepth] <= [RowDepth],",
              "        ISINSCOPE( 'dim resultatenrekening'[soort+beschrijving] )",
              "    )",
              "VAR actualsytd =",
              "    CALCULATE(",
              "        IF( ShowRow, SUM( 'fct besteed'[actual] ) ),",
              "        CALCULATETABLE( 'date', 'date'[ytd?] <= filterytd )",
              "    )",
              "RETURN",
              "    actualsytd"
            ],
            "formatString": "#,0",
            "isHidden": true,
            "lineageTag": "1bde65e0-17c1-4f78-a6e7-40aa1ee6b59d",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "obligo total",
            "expression": [
              "",
              "-- keuzeknop: enkel closed actuals of alle actuals + obligo's",
              "VAR filterytd = SELECTEDVALUE( switch_ytd[value], 1 )",
              "-- parent child hierarchy van dim object, je wil geen lege rijen tonen in de matrix",
              "VAR ShowRow =",
              "    OR(",
              "        [BrowseDepth] <= [RowDepth],",
              "        ISINSCOPE( 'dim resultatenrekening'[soort+beschrijving] )",
              "    )",
              "VAR actualsytd =",
              "    CALCULATE(",
              "        IF( ShowRow, SUM( 'fct besteed'[obligo] ) ),",
              "        CALCULATETABLE( 'date', 'date'[ytd?] <= filterytd )",
              "    )",
              "RETURN",
              "    actualsytd"
            ],
            "formatString": "#,0",
            "isHidden": true,
            "lineageTag": "e3582188-7226-4890-b0e5-b6c16140796c",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ]
          },
          {
            "name": "besteed total",
            "expression": "[actuals total] + [obligo total]",
            "formatString": "#,0",
            "isHidden": true,
            "lineageTag": "98312a1a-db3c-485d-924f-08ff33066d5d",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ]
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "TabularEditor_TableGroup",
            "value": "facts"
          }
        ]
      },
      {
        "name": "field measure drill",
        "lineageTag": "5761e669-c981-4aee-aabc-c51aa90f45c1",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "field measure drill",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[Value1]",
            "sortByColumn": "field measure drill Order",
            "lineageTag": "8092b532-4b70-44af-b8ac-53959300a193",
            "summarizeBy": "none",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "field measure drill Fields"
                }
              ]
            },
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "field measure drill Fields",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[Value2]",
            "sortByColumn": "field measure drill Order",
            "lineageTag": "93057aa1-3e9a-4b0c-9a5c-1d9db1bfa38b",
            "summarizeBy": "none",
            "extendedProperties": [
              {
                "type": "json",
                "name": "ParameterMetadata",
                "value": {
                  "version": 3,
                  "kind": 2
                }
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "field measure drill Order",
            "dataType": "int64",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[Value3]",
            "formatString": "0",
            "lineageTag": "e5049d7f-7b88-40f7-b3c6-935b177b6b9e",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "field measure drill-9385edd6-99a8-47f4-a245-e8e864b633ff",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": [
                "{",
                "    (\"actuals (A)\", NAMEOF('Key Measures'[Actuals basic]),      0),",
                "    (\"obligo (O)\", NAMEOF('Key Measures'[obligo basic]),         1),",
                "    (\"besteed (A+O)\", NAMEOF('Key Measures'[Besteed]),       2),",
                "    (\"budget (B)\", NAMEOF('Key Measures'[B MTD]),   3)",
                "}"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "e7270095665b45e0b49ee0c128558e08"
          },
          {
            "name": "TabularEditor_TableGroup",
            "value": "field paramaters"
          }
        ]
      },
      {
        "name": "opbrengsten_structuur",
        "excludeFromModelRefresh": true,
        "lineageTag": "fe145399-0938-4f2f-963c-aacf3dcc5a38",
        "columns": [
          {
            "name": "Pijlers",
            "dataType": "string",
            "sourceColumn": "Pijlers",
            "sortByColumn": "Begrenzing",
            "lineageTag": "38932763-9a38-47a3-bf84-1513378b4307",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Soort+beschrijving",
            "dataType": "string",
            "sourceColumn": "Soort+beschrijving",
            "lineageTag": "d02b8013-a0cb-4dc5-9fcf-945550d14e10",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Begrenzing",
            "dataType": "double",
            "sourceColumn": "Begrenzing",
            "formatString": "0",
            "lineageTag": "86172ccb-3f94-42f8-a958-e4c2c2cbfaea",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Beschrijving begrenzing",
            "dataType": "string",
            "sourceColumn": "Beschrijving begrenzing",
            "sortByColumn": "Begrenzing",
            "lineageTag": "68f0d0d0-f8ec-4242-8599-75f45a350769",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Soort_id",
            "dataType": "string",
            "sourceColumn": "Soort_id",
            "lineageTag": "dcb4e727-073f-4a3f-879e-9314d7e475af",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "plafond",
            "dataType": "double",
            "sourceColumn": "plafond",
            "formatString": "\"€\"\\ #,0.###############;#,0.###############\\ -\"€\";\"€\"\\ #,0.###############",
            "lineageTag": "838655c7-9874-448e-ab2c-6656e2ce6114",
            "summarizeBy": "sum",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"nl-BE\"}"
              }
            ]
          },
          {
            "name": "Categorie pijler",
            "dataType": "string",
            "sourceColumn": "Categorie pijler",
            "lineageTag": "767e528c-b642-4d8b-ba29-5689435927eb",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "opbrengsten_structuur-5267a43d-1381-4f3d-be0a-eeb7be10ba00",
            "mode": "import",
            "queryGroup": "Sharepoint\\Sharepoint Opbrengsten",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = SharePoint.Files(\"https://rto365.sharepoint.com/sites/FCO-14PowerBI2/\", [ApiVersion = 15]),",
                "    #\"Sorted Rows\" = Table.Sort(Source,{{\"Name\", Order.Ascending}}),",
                "    #\"structuur_opbrengsten xlsx_https://rto365 sharepoint com/sites/FCO-14PowerBI2/Data Power BI/Financiële data/Feedback/\" = #\"Sorted Rows\"{[Name=\"structuur_opbrengsten.xlsx\",#\"Folder Path\"=\"https://rto365.sharepoint.com/sites/FCO-14PowerBI2/Data Power BI/Financiële data/Feedback/\"]}[Content],",
                "    ImportedExcelWorkbook = Excel.Workbook(#\"structuur_opbrengsten xlsx_https://rto365 sharepoint com/sites/FCO-14PowerBI2/Data Power BI/Financiële data/Feedback/\"),",
                "    Opbrengsten_Table = ImportedExcelWorkbook{[Item=\"Opbrengsten\",Kind=\"Table\"]}[Data],",
                "",
                "    #\"Merged Queries\" = Table.NestedJoin(Opbrengsten_Table, {\"Begrenzing\"}, opbrengsten_plafond, {\"Begrenzing\"}, \"opbrengsten_plafond\", JoinKind.LeftOuter),",
                "    #\"Expanded opbrengsten_plafond\" = Table.ExpandTableColumn(#\"Merged Queries\", \"opbrengsten_plafond\", {\"plafond\"}, {\"plafond\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Expanded opbrengsten_plafond\",{{\"KOLOM CHARLOTTE\", \"Categorie pijler\"}})",
                "in",
                "    #\"Renamed Columns\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "opbrengsten",
            "expression": [
              "-- gebruik TREATAS omdat een eenvoudige relatie niet mogelijk is, structuur opbrengsten bevat namelijk dubbels",
              "VAR filterytd = SELECTEDVALUE( switch_ytd[value], 1 )",
              "VAR _result =",
              "    CALCULATE(",
              "        CALCULATE(",
              "            SUM( 'fct besteed'[actual] ),",
              "            TREATAS(",
              "                VALUES( opbrengsten_structuur[Soort_id] ),",
              "                'fct besteed'[soort_id]",
              "            )",
              "        ),",
              "        CALCULATETABLE( 'date', 'date'[ytd?] <= filterytd )",
              "    )",
              "RETURN",
              "    _result"
            ],
            "formatString": "\"€\"\\ #,0;-\"€\"\\ #,0;\"€\"\\ #,0",
            "lineageTag": "7abe282c-e4e9-4eb7-bcdd-c99ac58d0533",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "OP PY",
            "expression": [
              "// Omwille van de structuur tijdstabel niet mogelijk om met dateadd te werken",
              "VAR CurrentYearNumber = SELECTEDVALUE( 'date'[Year] )",
              "VAR PreviousYearNumber = CurrentYearNumber - 1",
              "VAR Result =",
              "    CALCULATE(",
              "        [opbrengsten],",
              "        REMOVEFILTERS( 'date' ),",
              "        VALUES( 'date'[Month] ),",
              "        'date'[Year] = PreviousYearNumber",
              "    )",
              "RETURN",
              "    Result"
            ],
            "formatString": "\"€\"\\ #,0;-\"€\"\\ #,0;\"€\"\\ #,0",
            "lineageTag": "c17eddab-021f-430f-97ae-f609540f5543",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "OP PY % total",
            "expression": "DIVIDE( [OP PY], [OP PY total] )",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "1e716cb5-c09b-46d0-911b-a87319ab9995",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "OP PY total",
            "expression": [
              "CALCULATE(",
              "    [OP PY],",
              "    REMOVEFILTERS( 'date' ),",
              "    REMOVEFILTERS( opbrengsten_structuur ),",
              "    VALUES( 'date'[Year] ),",
              "    --VALUES(opbrengsten_structuur[Soort_id])",
              "    VALUES( opbrengsten_structuur[Pijlers] )",
              ")"
            ],
            "lineageTag": "04700d93-fb01-453f-a972-11fca8c5d6cb",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "budget eerst",
            "expression": [
              "-- gebruik TREATAS omdat een eenvoudige relatie niet mogelijk is, structuur opbrengsten bevat namelijk dubbels",
              "VAR _filterytd = SELECTEDVALUE( switch_ytd[value], 1 )",
              "VAR _versie = \"000\"",
              "VAR _calc =",
              "    CALCULATE(",
              "        CALCULATE(",
              "            SUM( 'fct budget'[budget] ),",
              "            'budget versie'[versie] = _versie,",
              "            TREATAS(",
              "                VALUES( opbrengsten_structuur[Soort_id] ),",
              "                'fct budget'[soort_id]",
              "            )",
              "        ),",
              "        CALCULATETABLE( 'date', 'date'[ytd?] <= _filterytd )",
              "    )",
              "VAR _scope = IF( [scope_object], _calc )",
              "RETURN",
              "    _calc"
            ],
            "formatString": "#,0.00",
            "lineageTag": "2c92d117-1504-4012-9fc0-ca43c62d3c8b",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "prognose ",
            "expression": [
              "-- gebruik TREATAS omdat een eenvoudige relatie niet mogelijk is, structuur opbrengsten bevat namelijk dubbels",
              "VAR filterytd = 3 --SELECTEDVALUE( switch_ytd[value], 1 )",
              "VAR _result =",
              "    CALCULATE(",
              "        CALCULATE(",
              "            SUM( 'fct prognose opbrengsten'[prognose maandbasis] ),",
              "            TREATAS(",
              "                VALUES( opbrengsten_structuur[Soort_id] ),",
              "                'fct prognose opbrengsten'[Rekening]",
              "            )",
              "        ),",
              "        CALCULATETABLE( 'date', 'date'[ytd?] <= filterytd )",
              "    )",
              "VAR _scope = IF( [scope_object], _result )",
              "RETURN",
              "    _result"
            ],
            "lineageTag": "42f28f43-711a-4ab6-a179-a40eb05138b2",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "check",
            "expression": [
              "VAR _scope =",
              "    NOT ( ISINSCOPE( opbrengsten_structuur[Soort+beschrijving] )",
              "        || ISINSCOPE( opbrengsten_structuur[Categorie pijler] ) )",
              "VAR _calc = IF( _scope, [plafond max] - [prognose ] )",
              "RETURN",
              "    _calc"
            ],
            "lineageTag": "bfaecf3e-f712-4973-9cad-feabc80f3f27",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "scope_object",
            "expression": [
              "ISINSCOPE( opbrengsten_structuur[Begrenzing] )",
              "    || ISINSCOPE( opbrengsten_structuur[Beschrijving begrenzing] )",
              "    || ISINSCOPE( opbrengsten_structuur[Pijlers] )"
            ],
            "lineageTag": "5db5c788-52a8-4268-b240-112ed9c53273",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "delta bva",
            "expression": "[opbrengsten] - [budget laatst]",
            "lineageTag": "f6c47870-d50f-47d6-8e82-a33bac4701d7",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "plafond max",
            "expression": "MAX( opbrengsten_structuur[plafond] )",
            "lineageTag": "d65c567c-efb8-4177-a944-2f73be0c507e",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "plafond max multiplied",
            "expression": "1.1 * [plafond max]",
            "lineageTag": "aff966e5-5a7f-4a6a-ad69-20422dca621b",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "budget laatst",
            "expression": [
              "-- gebruik TREATAS omdat een eenvoudige relatie niet mogelijk is, structuur opbrengsten bevat namelijk dubbels",
              "VAR _filterytd = SELECTEDVALUE( switch_ytd[value], 1 )",
              "VAR _versie = [B versie max]",
              "VAR _calc =",
              "    CALCULATE(",
              "        CALCULATE(",
              "            SUM( 'fct budget'[budget] ),",
              "            'budget versie'[versie] = _versie,",
              "            TREATAS(",
              "                VALUES( opbrengsten_structuur[Soort_id] ),",
              "                'fct budget'[soort_id]",
              "            )",
              "        ),",
              "        CALCULATETABLE( 'date', 'date'[ytd?] <= _filterytd )",
              "    )",
              "VAR _scope = IF( [scope_object], _calc )",
              "RETURN",
              "    _calc"
            ],
            "lineageTag": "74429fdc-8930-4360-aea5-a3aefe75ab35"
          },
          {
            "name": "headar pvp",
            "expression": [
              "\"Ligt de prognose onder het plafond? Bedragen \"",
              "    & SWITCH(",
              "        SELECTEDVALUE( weergave_getal[Weergave getal] ),",
              "        \"1.000.000,00\", \"uitgedrukt in M\",",
              "        \"1.000.000\", \"uitgedrukt in M\",",
              "        \"1.000,00\", \"uitgedrukt in K\",",
              "        \"1.000,00\", \"uitgedrukt in K\",",
              "        \"1,00\", \"uitgedrukt in euro\",",
              "        \"1\", \"uitgedrukt in euro\",",
              "        BLANK( )",
              "    )"
            ],
            "lineageTag": "839998e0-ecfe-4f99-bb15-c108f017c702",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "TabularEditor_TableGroup",
            "value": "dimension"
          }
        ]
      },
      {
        "name": "weergave_getal",
        "lineageTag": "49cf54d8-b07f-41e0-a32d-fc10ea26cf62",
        "calculationGroup": {
          "precedence": 10,
          "calculationItems": [
            {
              "name": "1.000.000,00",
              "expression": [
                "",
                "IF(",
                "    ISSELECTEDMEASURE( [keuze header 2 zonder :] )",
                "        || ISSELECTEDMEASURE( [keuze header] )",
                "        || ISSELECTEDMEASURE( [headar pvp] ),",
                "    SELECTEDMEASURE( ),",
                "    SELECTEDMEASURE( ) / 1000000",
                ")"
              ],
              "ordinal": 5,
              "formatStringDefinition": {
                "expression": "\"#,0.00\""
              }
            },
            {
              "name": "1,00",
              "expression": [
                "",
                "IF(",
                "    ISSELECTEDMEASURE( [keuze header 2 zonder :] )",
                "        || ISSELECTEDMEASURE( [keuze header] )",
                "        || ISSELECTEDMEASURE( [headar pvp] ),",
                "    SELECTEDMEASURE( ),",
                "    SELECTEDMEASURE( )",
                ")"
              ],
              "ordinal": 1,
              "formatStringDefinition": {
                "expression": "\"#,0.00\""
              }
            },
            {
              "name": "1",
              "expression": [
                "",
                "IF(",
                "    ISSELECTEDMEASURE( [keuze header 2 zonder :] )",
                "    || ISSELECTEDMEASURE( [keuze header] )",
                "    || ISSELECTEDMEASURE( [headar pvp] ),",
                "    SELECTEDMEASURE(),",
                "    SELECTEDMEASURE()",
                ")"
              ],
              "ordinal": 0,
              "formatStringDefinition": {
                "expression": "\"#,0\""
              }
            },
            {
              "name": "1.000,00",
              "expression": [
                "",
                "IF(",
                "    ISSELECTEDMEASURE( [keuze header 2 zonder :] )",
                "        || ISSELECTEDMEASURE( [keuze header] )",
                "        || ISSELECTEDMEASURE( [headar pvp] ),",
                "    SELECTEDMEASURE( ),",
                "    SELECTEDMEASURE( )/1000",
                ")"
              ],
              "ordinal": 3,
              "formatStringDefinition": {
                "expression": "\"#,0.00\""
              }
            },
            {
              "name": "1.000",
              "expression": [
                "",
                "IF(",
                "    ISSELECTEDMEASURE( [keuze header 2 zonder :] )",
                "    || ISSELECTEDMEASURE( [keuze header] )",
                "    || ISSELECTEDMEASURE( [headar pvp] ),",
                "    SELECTEDMEASURE(),",
                "    SELECTEDMEASURE()/1000",
                ")"
              ],
              "ordinal": 2,
              "formatStringDefinition": {
                "expression": "\"#,0\""
              }
            },
            {
              "name": "1.000.000",
              "expression": [
                "",
                "IF(",
                "    ISSELECTEDMEASURE( [keuze header 2 zonder :] )",
                "    || ISSELECTEDMEASURE( [keuze header] )",
                "    || ISSELECTEDMEASURE( [headar pvp] ),",
                "    SELECTEDMEASURE(),",
                "    SELECTEDMEASURE()/1000000",
                "    ",
                ")"
              ],
              "ordinal": 4,
              "formatStringDefinition": {
                "expression": "\"#,0\""
              }
            }
          ]
        },
        "columns": [
          {
            "name": "Weergave getal",
            "dataType": "string",
            "sourceColumn": "Name",
            "sortByColumn": "Ordinal",
            "lineageTag": "98b9fb07-ac1b-43a7-92bc-59e125ef5701",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Ordinal",
            "dataType": "int64",
            "sourceColumn": "Ordinal",
            "lineageTag": "a906579b-7b6e-4246-95bf-157605353237",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "mode": "import",
            "source": {
              "type": "calculationGroup"
            }
          }
        ],
        "measures": [
          {
            "name": "txt weergave getal",
            "expression": [
              "",
              "SWITCH(",
              "    TRUE(),",
              "    SELECTEDVALUE( 'weergave_getal'[Ordinal] ) = 5, \"bedrag in M euro\",",
              "    SELECTEDVALUE( 'weergave_getal'[Ordinal] ) = 4, \"bedrag in M euro, afgerond\",",
              "    SELECTEDVALUE( 'weergave_getal'[Ordinal] ) = 3, \"bedrag in K euro\",",
              "    SELECTEDVALUE( 'weergave_getal'[Ordinal] ) = 2, \"bedrag in K euro, afgerond\",",
              "    SELECTEDVALUE( 'weergave_getal'[Ordinal] ) = 1, \"bedrag in euro\",",
              "    SELECTEDVALUE( 'weergave_getal'[Ordinal] ) = 0, \"bedrag in euro, afgerond\",",
              "    \"ERROR\"",
              ")"
            ],
            "lineageTag": "e63178d7-f645-40e1-bebc-32f7f4222bfa",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "TabularEditor_TableGroup",
            "value": "calculation groups"
          }
        ]
      },
      {
        "name": "YTDMTD",
        "lineageTag": "2657fe4b-50ca-46fb-8a3b-d1719f51cedf",
        "calculationGroup": {
          "precedence": 3,
          "calculationItems": [
            {
              "name": "MTD",
              "expression": "SELECTEDMEASURE()"
            },
            {
              "name": "YTD (cumulatief)",
              "expression": [
                "",
                "VAR LastMonthAvailable =",
                "    MAX ( 'date'[Year Month Number] )",
                "VAR LastYearAvailable =",
                "    MAX ( 'date'[Year] )",
                "VAR Result =",
                "    CALCULATE (",
                "        SELECTEDMEASURE(),",
                "        REMOVEFILTERS ( 'date' ),",
                "        'date'[Year Month Number] <= LastMonthAvailable,",
                "        'date'[Year] = LastYearAvailable",
                "    )",
                "RETURN",
                "    Result"
              ]
            }
          ]
        },
        "columns": [
          {
            "name": "MTD/YTD",
            "dataType": "string",
            "sourceColumn": "Name",
            "sortByColumn": "Ordinal",
            "lineageTag": "76341a78-b8c9-40ae-be2b-e78bbb0be9ed",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Ordinal",
            "dataType": "int64",
            "sourceColumn": "Ordinal",
            "lineageTag": "e6fa6116-59ff-4775-baa1-a34840a44fb1",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "mode": "import",
            "source": {
              "type": "calculationGroup"
            }
          }
        ],
        "annotations": [
          {
            "name": "TabularEditor_TableGroup",
            "value": "calculation groups"
          }
        ]
      },
      {
        "name": "fct prognose opbrengsten",
        "lineageTag": "1dbd181e-fe0b-4dca-a620-d3848a42725e",
        "columns": [
          {
            "name": "Rekening",
            "dataType": "string",
            "sourceColumn": "Rekening",
            "lineageTag": "0b122741-40fc-4c1a-82a0-d1dcdd93d619",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "prognose jaarbasis",
            "dataType": "double",
            "sourceColumn": "prognose jaarbasis",
            "lineageTag": "306d1202-389a-4746-8033-7059fe6d5837",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "YYYY-M",
            "dataType": "string",
            "sourceColumn": "YYYY-M",
            "lineageTag": "591c5b08-a4a9-491b-98ee-976f522aeaa1",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "maandbasis verdeling %",
            "dataType": "double",
            "sourceColumn": "maandbasis verdeling %",
            "lineageTag": "bb57ef62-db0c-4d3d-a06b-2fd324d25d22",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "prognose maandbasis",
            "dataType": "decimal",
            "sourceColumn": "prognose maandbasis",
            "formatString": "\"€\"\\ #,0.###############;#,0.###############\\ -\"€\";\"€\"\\ #,0.###############",
            "lineageTag": "aab314d4-8f49-453f-b82e-96e212694eea",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"nl-BE\"}"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "fct prognose opbrengsten-5529c6ed-d58a-4e68-9272-7494cb94b2e5",
            "mode": "import",
            "queryGroup": "Sharepoint\\Sharepoint Opbrengsten",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = SharePoint.Files(\"https://rto365.sharepoint.com/sites/FCO-14PowerBI2/\", [ApiVersion = 15]),",
                "    #\"Sorted Rows\" = Table.Sort(Source,{{\"Name\", Order.Ascending}}),",
                "    #\"structuur_opbrengsten xlsx_https://rto365 sharepoint com/sites/FCO-14PowerBI2/Data Power BI/Financiële data/Feedback/\" = #\"Sorted Rows\"{[Name=\"structuur_opbrengsten.xlsx\",#\"Folder Path\"=\"https://rto365.sharepoint.com/sites/FCO-14PowerBI2/Data Power BI/Financiële data/Feedback/\"]}[Content],",
                "    ImportedExcelWorkbook = Excel.Workbook(#\"structuur_opbrengsten xlsx_https://rto365 sharepoint com/sites/FCO-14PowerBI2/Data Power BI/Financiële data/Feedback/\"),",
                "    prognose_cijfers_Table = ImportedExcelWorkbook{[Item=\"prognose_cijfers\",Kind=\"Table\"]}[Data],",
                "    #\"Unpivoted Other Columns\" = Table.UnpivotOtherColumns(prognose_cijfers_Table, {\"Rekening\", \"prognose jaarbasis\"}, \"Attribute\", \"Value\"),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Unpivoted Other Columns\",{{\"Value\", Percentage.Type}}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Changed Type\",{{\"Attribute\", \"YYYY-M\"}}),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Renamed Columns\", \"calc\", each [prognose jaarbasis]*[Value]),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Added Custom\",{{\"calc\", \"prognose maandbasis\"}, {\"Value\", \"maandbasis verdeling %\"}}),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Renamed Columns1\",{{\"prognose maandbasis\", Currency.Type}})",
                "in",
                "    #\"Changed Type1\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "TabularEditor_TableGroup",
            "value": "facts"
          }
        ]
      },
      {
        "name": "precalc table AB",
        "lineageTag": "77608b29-785f-4b12-8a9b-2b08a15d0ee2",
        "columns": [
          {
            "name": "object_id",
            "dataType": "string",
            "sourceColumn": "object_id",
            "lineageTag": "6cca5d53-e4d7-41e4-8a51-72f2998d6e56",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "yyyymm",
            "dataType": "string",
            "sourceColumn": "yyyymm",
            "lineageTag": "a87b8654-feef-4030-97b5-9f5390483bab",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "year",
            "dataType": "string",
            "sourceColumn": "year",
            "lineageTag": "67ca4f1c-ccfe-478a-84db-a85e62bc6651",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "par1_12",
            "dataType": "int64",
            "sourceColumn": "par1_12",
            "formatString": "0",
            "lineageTag": "f72c158e-6471-46d9-84b1-7e1ee0847d8c",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "versie",
            "dataType": "string",
            "sourceColumn": "versie",
            "lineageTag": "1b3092e6-b3a3-4f2b-b851-c4105a3c18eb",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "a",
            "dataType": "double",
            "sourceColumn": "a",
            "lineageTag": "e8a7d2ed-fbb1-4d1a-a7dc-9de00875254c",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "b_og",
            "dataType": "double",
            "sourceColumn": "b_og",
            "lineageTag": "9a12e7f0-b652-481f-8c62-184aab1d47ab",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "b_dyn",
            "dataType": "double",
            "sourceColumn": "b_dyn",
            "lineageTag": "66ddc454-fd7a-4c2b-891e-625ac8f63c94",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "objecttype",
            "dataType": "string",
            "sourceColumn": "objecttype",
            "lineageTag": "c7d6da2a-362f-4c83-9d28-bf2d7b7c0711",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "versie_og",
            "dataType": "string",
            "sourceColumn": "versie_og",
            "lineageTag": "30d98e1d-2b95-4251-9ebf-2a342028ba7b",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "compkey_versie",
            "dataType": "string",
            "sourceColumn": "compkey_versie",
            "lineageTag": "e5eff251-52b1-4373-a959-2823991966cd",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "precalc table AB-01202b48-2f28-41bc-b82e-145959c428ff",
            "mode": "import",
            "queryGroup": "Datalake",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = AmazonAthena.Databases(\"Simba Athena\", null),",
                "    AwsDataCatalog_Database = Source{[Name=\"AwsDataCatalog\",Kind=\"Database\"]}[Data],",
                "    analytics_nonprod_athena_Schema = AwsDataCatalog_Database{[Name=SourceAthena,Kind=\"Schema\"]}[Data],",
                "    fct_opdata_fin_ytd_precalc_Table = analytics_nonprod_athena_Schema{[Name=\"fct_opdata_fin_ytd_precalc\",Kind=\"Table\"]}[Data]",
                "in",
                "    fct_opdata_fin_ytd_precalc_Table"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          },
          {
            "name": "TabularEditor_TableGroup",
            "value": "facts"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ]
      },
      {
        "name": "field row",
        "lineageTag": "7d9591b9-bde7-4d5f-b59e-67e3adecaeb9",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Rows selected",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[Value1]",
            "sortByColumn": "field row Order",
            "lineageTag": "45096d04-da6f-415d-ba3e-4972fd70440d",
            "summarizeBy": "none",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "field row Fields"
                }
              ]
            },
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "field row Fields",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[Value2]",
            "sortByColumn": "field row Order",
            "lineageTag": "d8fe174e-a0da-444b-84d3-c1e26f47dd8f",
            "summarizeBy": "none",
            "extendedProperties": [
              {
                "type": "json",
                "name": "ParameterMetadata",
                "value": {
                  "version": 3,
                  "kind": 2
                }
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "field row Order",
            "dataType": "int64",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[Value3]",
            "formatString": "0",
            "lineageTag": "3da6413e-ecf2-4652-8b20-a9e447c63a2e",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "dimensie",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[Value4]",
            "sortByColumn": "dimsort",
            "lineageTag": "23c78d1f-16d8-43b7-9d69-69bffe8ec3c2",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "dimsort",
            "dataType": "int64",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[Value5]",
            "formatString": "0",
            "lineageTag": "03704eed-c787-4224-bef8-7324f032bf8d",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "field row-768f8fc0-eb90-484b-83a7-374a546ac770",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "{",
                "    (\" \", NAMEOF('Key Measures'[Column]), 100, \"geen selectie\", -1),",
                "",
                "    (\"yyyy-mm\", NAMEOF('date'[yyyy-mm]), -3, \"tijd\", 0),",
                "    (\"maand\", NAMEOF('date'[Month]), -2, \"tijd\", 0),",
                "    (\"jaar\", NAMEOF('date'[Year]), -1, \"tijd\", 0),",
                "",
                "    (\"directie\", NAMEOF('object'[Directie]), 7, \"object\", 1),",
                "    (\"directie_lvl2\", NAMEOF('object'[Level3]), 2, \"object\", 1),",
                "    (\"directie_lvl3\", NAMEOF('object'[Level4]), 3, \"object\", 1),",
                "    (\"directie_lvl4\", NAMEOF('object'[Level5]), 4, \"object\", 1),",
                "    (\"object+omschrijving\", NAMEOF('object'[object+omschrijving]), 6, \"object\", 1),",
                "    (\"objecttype\", NAMEOF('object'[objecttype]), 1, \"object\", 1),",
                "",
                "    (\"soort+omschrijving\", NAMEOF('dim resultatenrekening'[soort+beschrijving]), 8, \"soort\", 2),",
                "    (\"ledger niveau 1\", NAMEOF('dim resultatenrekening'[Level2]), 9, \"soort\", 2),",
                "    (\"ledger niveau 2\", NAMEOF('dim resultatenrekening'[Level3]), 10, \"soort\", 2),",
                "    (\"ledger niveau 3\", NAMEOF('dim resultatenrekening'[Level4]), 11, \"soort\", 2),",
                "    (\"ledger niveau 4\", NAMEOF('dim resultatenrekening'[Level5]), 13, \"soort\", 2),",
                "    (\"ledger niveau 5\", NAMEOF('dim resultatenrekening'[Level6]), 14, \"soort\", 2),",
                "    (\"ledger niveau 6\", NAMEOF('dim resultatenrekening'[Level7]), 15, \"soort\", 2),",
                "",
                "    (\"bestel_tekst\", NAMEOF('bestelbon'[bestel_tekst]), 25, \"bestelbon\", 3),",
                "    (\"inkoopartikel\", NAMEOF('bestelbon'[inkoopartikel]), 21, \"bestelbon\", 3),",
                "    (\"bestelbon_id\", NAMEOF('bestelbon'[bestelbonnummer]), 22, \"bestelbon\", 3),",
                "    (\"lev_bankrekening\", NAMEOF('bestelbon'[lev_bankrekening]), 23, \"bestelbon\", 3),",
                "    (\"lev_land\", NAMEOF('bestelbon'[lev_land]), 24, \"bestelbon\", 3),",
                "    (\"lev_naam\", NAMEOF('bestelbon'[lev_naam]), 20, \"bestelbon\", 3),",
                "    (\"lev_postcode\", NAMEOF('bestelbon'[lev_postcode]), 26, \"bestelbon\", 3),",
                "    (\"lev_stad\", NAMEOF('bestelbon'[lev_stad]), 27, \"bestelbon\", 3),",
                "    (\"lev_straat\", NAMEOF('bestelbon'[lev_straat]), 28, \"bestelbon\", 3),",
                "    (\"leverancier_id\", NAMEOF('bestelbon'[leverancier_id]), 29, \"bestelbon\", 3),",
                "    (\"positie_bestel\", NAMEOF('bestelbon'[bestelbon_positie]), 30, \"bestelbon\", 3),",
                "",
                "    (\"artikel\", NAMEOF('object'[artikel]), 50, \"artikel (PO)\", 4),",
                "    (\"productiehuis\", NAMEOF('object'[productiehuis]), 51, \"artikel (PO)\", 4),",
                "    (\"categorie\", NAMEOF('object'[categorie]), 52, \"artikel (PO)\", 4),",
                "    (\"kanaal\", NAMEOF('object'[kanaal]), 53, \"artikel (PO)\", 4),",
                "    (\"productiereeks_fin_rapport\", NAMEOF('object'[productiereeks_fin_rapport]), 54, \"artikel (PO)\", 4),",
                "    (\"subgenre\", NAMEOF('object'[subgenre]), 55, \"artikel (PO)\", 4),",
                "    (\"klant\", NAMEOF('object'[klant]), 56, \"artikel (PO)\", 4),",
                "    (\"IPRO_EPRO\", NAMEOF('object'[IPRO_EPRO]), 57, \"artikel (PO)\", 4),",
                "    (\"budgetbeheer_STD\", NAMEOF('object'[budgetbeheer_STD]), 58, \"artikel (PO)\", 4),",
                "    (\"budgetbeheer_PLP\", NAMEOF('object'[budgetbeheer_PLP]), 59, \"artikel (PO)\", 4),",
                "    (\"raamovereenkomst\", NAMEOF('object'[raamovereenkomst]), 60, \"artikel (PO)\", 4),",
                "    (\"netproducent\", NAMEOF('object'[netproducent]), 61, \"artikel (PO)\", 4)",
                "}"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "7e515449fcd346319885a3cb8f3efd1d"
          },
          {
            "name": "TabularEditor_TableGroup",
            "value": "field paramaters"
          }
        ]
      },
      {
        "name": "field copy for drill",
        "lineageTag": "31632bcd-ee30-4f97-b25f-ce9d980c12a3",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "selectie",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[Value1]",
            "sortByColumn": "selectiesort",
            "lineageTag": "62622b24-ffba-4beb-989e-e4351d52545c",
            "summarizeBy": "none",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "Parameter Fields"
                }
              ]
            },
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Parameter Fields",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[Value2]",
            "sortByColumn": "selectiesort",
            "lineageTag": "8bc4e411-0336-4f4a-94c3-a7e4c4648bbf",
            "summarizeBy": "none",
            "extendedProperties": [
              {
                "type": "json",
                "name": "ParameterMetadata",
                "value": {
                  "version": 3,
                  "kind": 2
                }
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "selectiesort",
            "dataType": "int64",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[Value3]",
            "formatString": "0",
            "lineageTag": "f265f857-ab6f-497b-8077-0204df8abb37",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "dimensie",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[Value4]",
            "sortByColumn": "dimselect",
            "lineageTag": "5284083e-aee1-4912-8445-f9f812b5f2b3",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "dimselect",
            "dataType": "int64",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[Value5]",
            "formatString": "0",
            "lineageTag": "33401503-71ca-4418-898c-19e0f58981b2",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "field copy for drill-a2aa47fb-350f-450b-bb0c-7b4667986fb6",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "{",
                "    (\" \", NAMEOF('Key Measures'[Column]), 100, \"geen selectie\", -1),",
                "",
                "    (\"yyyy-mm\", NAMEOF('date'[yyyy-mm]), -3, \"tijd\", 0),",
                "    (\"maand\", NAMEOF('date'[Month]), -2, \"tijd\", 0),",
                "    (\"jaar\", NAMEOF('date'[Year]), -1, \"tijd\", 0),",
                "",
                "    (\"directie\", NAMEOF('object'[Directie]), 7, \"object\", 1),",
                "    (\"directie_lvl2\", NAMEOF('object'[Level3]), 2, \"object\", 1),",
                "    (\"directie_lvl3\", NAMEOF('object'[Level4]), 3, \"object\", 1),",
                "    (\"directie_lvl4\", NAMEOF('object'[Level5]), 4, \"object\", 1),",
                "    (\"object+omschrijving\", NAMEOF('object'[object+omschrijving]), 6, \"object\", 1),",
                "    (\"objecttype\", NAMEOF('object'[objecttype]), 1, \"object\", 1),",
                "",
                "    (\"soort+omschrijving\", NAMEOF('dim resultatenrekening'[soort+beschrijving]), 8, \"soort\", 2),",
                "    (\"ledger niveau 1\", NAMEOF('dim resultatenrekening'[Level2]), 9, \"soort\", 2),",
                "    (\"ledger niveau 2\", NAMEOF('dim resultatenrekening'[Level3]), 10, \"soort\", 2),",
                "    (\"ledger niveau 3\", NAMEOF('dim resultatenrekening'[Level4]), 11, \"soort\", 2),",
                "    (\"ledger niveau 4\", NAMEOF('dim resultatenrekening'[Level5]), 13, \"soort\", 2),",
                "    (\"ledger niveau 5\", NAMEOF('dim resultatenrekening'[Level6]), 14, \"soort\", 2),",
                "    (\"ledger niveau 6\", NAMEOF('dim resultatenrekening'[Level7]), 15, \"soort\", 2),",
                "",
                "    (\"bestel_tekst\", NAMEOF('bestelbon'[bestel_tekst]), 25, \"bestelbon\", 3),",
                "    (\"inkoopartikel\", NAMEOF('bestelbon'[inkoopartikel]), 21, \"bestelbon\", 3),",
                "    (\"bestelbon_id\", NAMEOF('bestelbon'[bestelbonnummer]), 22, \"bestelbon\", 3),",
                "    (\"lev_bankrekening\", NAMEOF('bestelbon'[lev_bankrekening]), 23, \"bestelbon\", 3),",
                "    (\"lev_land\", NAMEOF('bestelbon'[lev_land]), 24, \"bestelbon\", 3),",
                "    (\"lev_naam\", NAMEOF('bestelbon'[lev_naam]), 20, \"bestelbon\", 3),",
                "    (\"lev_postcode\", NAMEOF('bestelbon'[lev_postcode]), 26, \"bestelbon\", 3),",
                "    (\"lev_stad\", NAMEOF('bestelbon'[lev_stad]), 27, \"bestelbon\", 3),",
                "    (\"lev_straat\", NAMEOF('bestelbon'[lev_straat]), 28, \"bestelbon\", 3),",
                "    (\"leverancier_id\", NAMEOF('bestelbon'[leverancier_id]), 29, \"bestelbon\", 3),",
                "    (\"positie_bestel\", NAMEOF('bestelbon'[bestelbon_positie]), 30, \"bestelbon\", 3),",
                "",
                "    (\"artikel\", NAMEOF('object'[artikel]), 50, \"artikel (PO)\", 4),",
                "    (\"productiehuis\", NAMEOF('object'[productiehuis]), 51, \"artikel (PO)\", 4),",
                "    (\"categorie\", NAMEOF('object'[categorie]), 52, \"artikel (PO)\", 4),",
                "    (\"kanaal\", NAMEOF('object'[kanaal]), 53, \"artikel (PO)\", 4),",
                "    (\"productiereeks_fin_rapport\", NAMEOF('object'[productiereeks_fin_rapport]), 54, \"artikel (PO)\", 4),",
                "    (\"subgenre\", NAMEOF('object'[subgenre]), 55, \"artikel (PO)\", 4),",
                "    (\"klant\", NAMEOF('object'[klant]), 56, \"artikel (PO)\", 4),",
                "    (\"IPRO_EPRO\", NAMEOF('object'[IPRO_EPRO]), 57, \"artikel (PO)\", 4),",
                "    (\"budgetbeheer_STD\", NAMEOF('object'[budgetbeheer_STD]), 58, \"artikel (PO)\", 4),",
                "    (\"budgetbeheer_PLP\", NAMEOF('object'[budgetbeheer_PLP]), 59, \"artikel (PO)\", 4),",
                "    (\"raamovereenkomst\", NAMEOF('object'[raamovereenkomst]), 60, \"artikel (PO)\", 4),",
                "    (\"netproducent\", NAMEOF('object'[netproducent]), 61, \"artikel (PO)\", 4)",
                "}"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "b229b597ee6c4e0985ecaf58e09b0583"
          },
          {
            "name": "TabularEditor_TableGroup",
            "value": "field paramaters"
          }
        ]
      },
      {
        "name": "soort",
        "lineageTag": "f191daa3-7b38-4952-ab70-59b64e4199da",
        "columns": [
          {
            "name": "link5",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "link5",
            "lineageTag": "ef382ae5-fe3d-4d1f-a61e-aba60b18bc31",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "is_id",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "is_id",
            "lineageTag": "23746953-dc40-4ad9-81f3-d9c3022be9ec",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "nodename",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "nodename",
            "lineageTag": "031fdc19-1ca8-4903-9164-26531bd22d84",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "childnode_id",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "childnode_id",
            "formatString": "0",
            "lineageTag": "dd89413e-c1db-48b7-bd75-588a98422568",
            "summarizeBy": "sum",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "parentnode_id",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "parentnode_id",
            "formatString": "0",
            "lineageTag": "ab896771-4faf-4d8e-bc60-889b7b24d549",
            "summarizeBy": "sum",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "firstchildnode_id",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "firstchildnode_id",
            "formatString": "0",
            "lineageTag": "7693ce42-c0f3-431d-88e2-7fa5ce7fd540",
            "summarizeBy": "sum",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "nextnode_id",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "nextnode_id",
            "formatString": "0",
            "lineageTag": "4e195a3c-aedb-4a45-86e9-8bab8a259798",
            "summarizeBy": "sum",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "soort_id",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "soort_id",
            "lineageTag": "f4dd2b39-75c0-4d9e-8ef7-c00129c0d2dc",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "soort_id_tag",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "soort_id_tag",
            "lineageTag": "7fcef158-cd7a-496b-a099-1a8d49a9a395",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "beschrijving soort_id",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "beschrijving soort_id",
            "lineageTag": "aea666a1-9a42-45b6-b23e-cbe5b81044cc",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "import_date",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "import_date",
            "formatString": "Short Date",
            "lineageTag": "f2e28fb1-c3f0-4cc7-ab36-878872d26d46",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ]
          },
          {
            "name": "l2",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "l2",
            "lineageTag": "19b06c7e-1d4a-48a2-ab39-098f54212f94",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "soort_id_zonderalgkv",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "soort_id_zonderalgkv",
            "lineageTag": "fe244253-cbb2-4bcd-925f-8ee261ff5cef",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "af_pe_ytd",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "af_pe_ytd",
            "lineageTag": "3dba800c-36a6-4681-b5f6-c542649adab4",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "path",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "PATH(soort[childnode_id], soort[parentnode_id])",
            "lineageTag": "ba3d9146-402c-466c-80fa-6e72eddb2cf6",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "depth",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "PATHLENGTH( soort[path] )",
            "formatString": "0",
            "lineageTag": "78834dec-574b-4c49-ae49-a530f7e73d24",
            "summarizeBy": "sum",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Level2",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": [
              "",
              "VAR LevelNumber = 2",
              "VAR LevelKey = VALUE(PATHITEM ( soort[path], LevelNumber ))",
              "VAR LevelName = ",
              "-- LOOKUPVALUE ( dim_soort_sap[soort_id_zonderalgkv], dim_soort_sap[childnode_id], LevelKey ) & \" \" & ",
              "LOOKUPVALUE ( soort[beschrijving soort_id], soort[childnode_id], LevelKey ) ",
              "RETURN",
              "    LevelName"
            ],
            "lineageTag": "25336b00-fc9c-46c6-8002-d225ea206e9d",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Level3",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": [
              "",
              "VAR LevelNumber = 3",
              "VAR LevelKey = VALUE(PATHITEM ( soort[path], LevelNumber ))",
              "VAR LevelName = ",
              "-- LOOKUPVALUE ( dim_soort_sap[soort_id_zonderalgkv], dim_soort_sap[childnode_id], LevelKey ) & \" \" & ",
              "LOOKUPVALUE ( soort[beschrijving soort_id], soort[childnode_id], LevelKey ) ",
              "RETURN",
              "    LevelName"
            ],
            "lineageTag": "29b6d75f-6022-4a04-9f67-0539b25a540e",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Level4",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": [
              "",
              "VAR LevelNumber = 4",
              "VAR LevelKey = VALUE(PATHITEM ( soort[path], LevelNumber ))",
              "VAR LevelName = ",
              "-- LOOKUPVALUE ( dim_soort_sap[soort_id_zonderalgkv], dim_soort_sap[childnode_id], LevelKey ) & \" \" & ",
              "LOOKUPVALUE ( soort[beschrijving soort_id], soort[childnode_id], LevelKey ) ",
              "RETURN",
              "    LevelName"
            ],
            "lineageTag": "852f1f13-fb6b-4066-9e76-d4e2b8ac7719",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Level5",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": [
              "",
              "VAR LevelNumber = 5",
              "VAR LevelKey = VALUE(PATHITEM ( soort[path], LevelNumber ))",
              "VAR LevelName = ",
              "LOOKUPVALUE ( soort[soort_id_zonderalgkv], soort[childnode_id], LevelKey ) ",
              "& \" \" & ",
              "LOOKUPVALUE ( soort[beschrijving soort_id], soort[childnode_id], LevelKey ) ",
              "RETURN",
              "    LevelName"
            ],
            "lineageTag": "318b0c43-98d8-4313-b447-2a7dfb2af7d6",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Level6",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": [
              "",
              "VAR LevelNumber = 6",
              "VAR LevelKey = VALUE(PATHITEM ( soort[path], LevelNumber ))",
              "VAR LevelName = ",
              "LOOKUPVALUE ( soort[soort_id_zonderalgkv], soort[childnode_id], LevelKey ) ",
              "& \" \" & ",
              "LOOKUPVALUE ( soort[beschrijving soort_id], soort[childnode_id], LevelKey ) ",
              "RETURN",
              "    LevelName"
            ],
            "lineageTag": "14e88f51-3b74-41c4-91ab-58c2a6b02b2f",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Level7",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": [
              "",
              "VAR LevelNumber = 7",
              "VAR LevelKey = VALUE(PATHITEM ( soort[path], LevelNumber ))",
              "VAR LevelName = ",
              "LOOKUPVALUE ( soort[soort_id_zonderalgkv], soort[childnode_id], LevelKey ) ",
              "& \" \" & ",
              "LOOKUPVALUE ( soort[beschrijving soort_id], soort[childnode_id], LevelKey ) ",
              "RETURN",
              "    LevelName"
            ],
            "lineageTag": "e9e4e96a-8f65-486b-84a2-15e9ff36113a",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Count uniq",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": [
              "",
              "VAR b_id = 'soort'[soort_id]",
              "VAR calc =",
              "CALCULATE(",
              "    COUNT('soort'[soort_id]),",
              "    REMOVEFILTERS(),",
              "    'soort'[soort_id]= b_id",
              "    )",
              "RETURN",
              "    calc"
            ],
            "formatString": "0",
            "lineageTag": "6a8c642f-a8cc-4343-bf6c-59a81b3b76ec",
            "summarizeBy": "sum",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Count uniq2",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": [
              "",
              "VAR b_id = 'soort'[soort_id]",
              "VAR subn = 'soort'[Level2]",
              "VAR calc =",
              "CALCULATE(",
              "    COUNT('soort'[soort_id]),",
              "    REMOVEFILTERS(),",
              "    'soort'[soort_id]= b_id,",
              "    'soort'[Level2]= subn",
              "    )",
              "RETURN",
              "    calc"
            ],
            "formatString": "0",
            "lineageTag": "500f4403-00d9-43f8-8753-980987f87d0d",
            "summarizeBy": "sum",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "soort-e53ec68a-8d01-487b-881f-2cd2aca36263",
            "mode": "import",
            "queryGroup": "Datalake",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = AmazonAthena.Databases(\"Simba Athena\", null),",
                "    AwsDataCatalog_Database = Source{[Name=\"AwsDataCatalog\",Kind=\"Database\"]}[Data],",
                "    analytics_nonprod_athena_Schema = AwsDataCatalog_Database{[Name=\"analytics_nonprod_athena\",Kind=\"Schema\"]}[Data],",
                "    prep_opdata_fin_sap_pijlerstructuur_soort_Table = analytics_nonprod_athena_Schema{[Name=\"prep_opdata_fin_sap_pijlerstructuur_soort\",Kind=\"Table\"]}[Data],",
                "    #\"Replaced Value\" = Table.ReplaceValue(prep_opdata_fin_sap_pijlerstructuur_soort_Table,0,null,Replacer.ReplaceValue,{\"parentnode_id\"})",
                "in",
                "    #\"Replaced Value\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "ShowRow_soort",
            "expression": [
              "",
              "[BrowseDepth_soort] <= [RowDepth_soort]",
              ""
            ],
            "isHidden": true,
            "lineageTag": "defaf4f1-fa30-478a-9d21-1a84c02059ce",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ]
          },
          {
            "name": "BrowseDepth_soort",
            "expression": [
              "",
              "--ISINSCOPE ( 'soort ledgerstructuur'[Ledger] )",
              "+ ISINSCOPE ( soort[Level2] )",
              "+ ISINSCOPE ( soort[Level3] )",
              "+ ISINSCOPE ( soort[Level4] )",
              "+ ISINSCOPE ( soort[Level5])",
              "+ ISINSCOPE ( soort[Level6] )",
              "+ ISINSCOPE ( soort[Level7] )+1"
            ],
            "isHidden": true,
            "lineageTag": "f7bbbe7d-d2c1-4141-ac9e-a6632f5754f8",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ]
          },
          {
            "name": "RowDepth_soort",
            "expression": "MAX ( 'soort'[depth] )",
            "isHidden": true,
            "lineageTag": "d3996ee1-f720-4447-9940-82edeb684a03",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ]
          },
          {
            "name": "actuals pnl",
            "expression": [
              "",
              "VAR _calc =",
              "    CALCULATE(",
              "        SUM( 'fct besteed'[actual] ),",
              "        TREATAS( ",
              "            VALUES('soort'[soort_id]),",
              "            'fct besteed'[soort_id]",
              "        )",
              "    )",
              "VAR _hideblank = ",
              "    IF([ShowRow_soort], _calc)",
              "RETURN",
              "    _hideblank"
            ],
            "isHidden": true,
            "lineageTag": "a358102c-41f8-427c-887e-3b7b309001ef",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ]
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "TabularEditor_TableGroup",
            "value": "dimension"
          }
        ]
      },
      {
        "name": "dim resultatenrekening",
        "lineageTag": "143a8a95-1342-46df-a149-aa7b4e6a9b57",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "link5",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "soort[link5]",
            "lineageTag": "9daccbba-bdda-4313-9772-3e9f3eec21ef",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "is_id",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "soort[is_id]",
            "lineageTag": "a1bffea2-96da-48e7-9c08-6bcfb94e68dc",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "nodename",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "soort[nodename]",
            "lineageTag": "0676685b-4254-4d76-9255-8b2f7b199816",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "childnode_id",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "soort[childnode_id]",
            "formatString": "0",
            "lineageTag": "5ba4c355-938c-4fa7-b71c-9ece8b00da69",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "parentnode_id",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "soort[parentnode_id]",
            "formatString": "0",
            "lineageTag": "ca0d82a1-83b6-452e-92d8-a118692dfa8f",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "firstchildnode_id",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "soort[firstchildnode_id]",
            "formatString": "0",
            "lineageTag": "4b1990f2-8315-4329-936f-cc377f5e9581",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "nextnode_id",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "soort[nextnode_id]",
            "formatString": "0",
            "lineageTag": "ecd23829-5f97-4d56-8b56-991dec8eebc4",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "soort_id",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "soort[soort_id]",
            "lineageTag": "cf343865-1c0e-43a8-afd0-3ebdc5af3b51",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "soort_id_tag",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "soort[soort_id_tag]",
            "lineageTag": "c7e6da03-03cd-4e45-af02-70c9f8d4f3ba",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "beschrijving soort_id",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "soort[beschrijving soort_id]",
            "lineageTag": "64201d62-53ba-4a09-b14e-fa945235ac22",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "import_date",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "soort[import_date]",
            "formatString": "General Date",
            "lineageTag": "6e913d79-16d7-461f-8c98-a5f8effb0e7d",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "l2",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "soort[l2]",
            "lineageTag": "5c063a55-3bba-44ba-9ba0-dad13ac8a246",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "soort_id_zonderalgkv",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "soort[soort_id_zonderalgkv]",
            "lineageTag": "75c9eb06-f3b4-4b40-9d03-708786bd2e00",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "af_pe_ytd",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "soort[af_pe_ytd]",
            "lineageTag": "78da0ad7-0e0c-4c8e-a3ad-c64d79dee049",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "path",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "soort[path]",
            "displayFolder": "hierachy creation",
            "lineageTag": "b5387c38-a0e5-4033-9d3c-bf34072a0075",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "depth",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "soort[depth]",
            "formatString": "0",
            "displayFolder": "hierachy creation",
            "lineageTag": "d2655cc7-6c82-4e04-8f17-f69c0d00a0c7",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Level2",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "soort[Level2]",
            "displayFolder": "hierachy creation",
            "lineageTag": "0114fc8b-d30f-4336-8e28-4a450d4fa49d",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Level3",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "soort[Level3]",
            "displayFolder": "hierachy creation",
            "lineageTag": "1d228199-80b6-4b1b-b7ad-8697172c78df",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Level4",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "soort[Level4]",
            "displayFolder": "hierachy creation",
            "lineageTag": "0bcf1356-d680-41bc-9691-4535e69a6e2a",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Level5",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "soort[Level5]",
            "displayFolder": "hierachy creation",
            "lineageTag": "7b53f105-ac47-4572-8f0d-92032f1a03b6",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Level6",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "soort[Level6]",
            "displayFolder": "hierachy creation",
            "lineageTag": "93e4674e-40be-4eae-98ce-928e08d3c6b2",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Level7",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "soort[Level7]",
            "displayFolder": "hierachy creation",
            "lineageTag": "04bee892-02a7-4d3b-bf94-ab06c89028bf",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Count uniq",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "soort[Count uniq]",
            "formatString": "0",
            "lineageTag": "73caf8aa-3f5d-4f92-8380-9c16ef3f42e2",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Count uniq2",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "soort[Count uniq2]",
            "formatString": "0",
            "lineageTag": "493ea9e3-d95d-400c-873a-7e6802497f1d",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "soort+beschrijving",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "'dim resultatenrekening'[soort_id] & \" - \" & 'dim resultatenrekening'[beschrijving soort_id]",
            "lineageTag": "362cf4f1-2e51-4275-aa60-4c61de720fd7",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "dim resultatenrekening-a320b105-326d-402b-b6cf-d747ecccae3b",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR _filter = FILTER(soort, soort[Level2]=\"Resultatenrekening\")",
                "RETURN",
                "    _filter"
              ]
            }
          }
        ],
        "hierarchies": [
          {
            "name": "soort hierarchy",
            "lineageTag": "aaaa0b22-f0d2-426a-849f-5bbe284fd846",
            "levels": [
              {
                "name": "Level2",
                "ordinal": 0,
                "column": "Level2",
                "lineageTag": "d6a0e938-18f6-46aa-a49f-0c998ad74f72"
              },
              {
                "name": "Level3",
                "ordinal": 1,
                "column": "Level3",
                "lineageTag": "e5c42755-aa5b-49bb-a78f-d96bb03f8f2d"
              },
              {
                "name": "Level4",
                "ordinal": 2,
                "column": "Level4",
                "lineageTag": "fad2d3e6-5594-44b8-a191-89d8e9647479"
              },
              {
                "name": "Level5",
                "ordinal": 3,
                "column": "Level5",
                "lineageTag": "819a1772-6c28-4e93-b1ff-a20c9ac7597a"
              },
              {
                "name": "Level6",
                "ordinal": 4,
                "column": "Level6",
                "lineageTag": "1a4c8ec3-10dc-4056-9633-e4e1758ffa3c"
              },
              {
                "name": "Level7",
                "ordinal": 5,
                "column": "Level7",
                "lineageTag": "6199d133-9e98-4899-b147-535f4d89f436"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "1c26e86e54474d1889e9fcdaa1df1bae"
          },
          {
            "name": "TabularEditor_TableGroup",
            "value": "dimension"
          }
        ]
      },
      {
        "name": "dim pnl",
        "lineageTag": "aec04879-9d02-42f9-b13d-0e03f3baee30",
        "columns": [
          {
            "name": "nr line item",
            "dataType": "string",
            "sourceColumn": "nr line item",
            "lineageTag": "85e2fe50-98cf-41d7-826d-2abfb24c104e",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "P&L niv 1",
            "dataType": "string",
            "sourceColumn": "P&L niv 1",
            "sortByColumn": "P&L niv 1 - sort",
            "lineageTag": "854becfe-e6e0-4119-93ec-ed52a85cf557",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "P&L niv 12",
            "dataType": "string",
            "sourceColumn": "P&L niv 12",
            "lineageTag": "70dbcb7c-5502-4a51-82ee-41b14e43e900",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "P&L niv 3",
            "dataType": "string",
            "sourceColumn": "P&L niv 3",
            "lineageTag": "3bec69b4-8257-49fe-950f-f0159e24e18e",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Extra info niet in systeem",
            "dataType": "string",
            "sourceColumn": "Extra info niet in systeem",
            "lineageTag": "2f14ddad-44a3-4a28-ba86-928db4d9a476",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "P&L niv 1 - sort",
            "dataType": "string",
            "sourceColumn": "P&L niv 1 - sort",
            "lineageTag": "7e1d1b9e-b258-4a5b-a17e-1b2814f69a02",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "sleutel=gelijk?",
            "dataType": "boolean",
            "sourceColumn": "sleutel=gelijk?",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "3c843c70-b14e-4c30-85e1-4e36f43f46c1",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "sleutel_voor2023",
            "dataType": "string",
            "sourceColumn": "sleutel_voor2023",
            "lineageTag": "3bbff1ba-ed59-4125-9e62-4389f8ae5843",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "sleutel_na2023",
            "dataType": "string",
            "sourceColumn": "sleutel_na2023",
            "lineageTag": "7def4724-43b0-49f3-a876-4116c409fc5e",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "opbrengstenplaats",
            "dataType": "string",
            "sourceColumn": "opbrengstenplaats",
            "lineageTag": "1f15497e-604f-493a-a672-a458a1b7dd75",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "opbrengstensoort",
            "dataType": "string",
            "sourceColumn": "opbrengstensoort",
            "lineageTag": "96e0691c-e578-4e06-9854-a2bb7bff7db0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "zonder ALG/KV",
            "dataType": "string",
            "sourceColumn": "zonder ALG/KV",
            "lineageTag": "1c13efa6-8e05-4493-9b60-1abbabc619e3",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "opbr soort kort",
            "dataType": "string",
            "sourceColumn": "opbr soort kort",
            "lineageTag": "782c0b0f-1105-4831-b29a-cab34dcdd90c",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "opbrengstenplaats omschrijving",
            "dataType": "string",
            "sourceColumn": "opbrengstenplaats omschrijving",
            "lineageTag": "e1c1f6e2-49ce-4c5d-891f-2f8a5db2e798",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "opbrengstensoort omschrijving",
            "dataType": "string",
            "sourceColumn": "opbrengstensoort omschrijving",
            "lineageTag": "47448099-5687-4a63-8b0f-35d7d913ecf3",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "P&L niv 3.1",
            "dataType": "string",
            "sourceColumn": "P&L niv 3.1",
            "lineageTag": "bdff4e54-bfec-4116-b56b-e2671dc0b818",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "P&L niv 1.1",
            "dataType": "string",
            "sourceColumn": "P&L niv 1.1",
            "lineageTag": "36d1e1bb-b98b-45dd-95ed-cef7bc447fa7",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "P&L niv 2",
            "dataType": "string",
            "sourceColumn": "P&L niv 2",
            "lineageTag": "c202e8b7-0706-47e9-ac4d-167167fa3a00",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "P&I nov 3",
            "dataType": "string",
            "sourceColumn": "P&I nov 3",
            "lineageTag": "214a4ee0-1ab6-4ffa-9df7-f0a17e3d4397",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "dim pnl-71ff5b61-3b25-4cd1-8ec6-f2c8b7242bf2",
            "mode": "import",
            "queryGroup": "Sharepoint\\Sharepoint PNL",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Table.NestedJoin(pnl_lineitem, {\"nr line item\"}, pnl_conv, {\"P&L niv 3\"}, \"pnl_conv\", JoinKind.LeftOuter),",
                "    #\"Expanded pnl_conv\" = Table.ExpandTableColumn(Source, \"pnl_conv\", {\"sleutel=gelijk?\", \"sleutel_voor2023\", \"sleutel_na2023\", \"opbrengstenplaats\", \"opbrengstensoort\", \"zonder ALG/KV\", \"opbr soort kort\", \"opbrengstenplaats omschrijving\", \"opbrengstensoort omschrijving\", \"P&L niv 3\", \"P&L niv 1\", \"P&L niv 2\", \"P&I nov 3\"}, {\"sleutel=gelijk?\", \"sleutel_voor2023\", \"sleutel_na2023\", \"opbrengstenplaats\", \"opbrengstensoort\", \"zonder ALG/KV\", \"opbr soort kort\", \"opbrengstenplaats omschrijving\", \"opbrengstensoort omschrijving\", \"P&L niv 3.1\", \"P&L niv 1.1\", \"P&L niv 2\", \"P&I nov 3\"}),",
                "    #\"Sorted Rows\" = Table.Sort(#\"Expanded pnl_conv\",{{\"P&L niv 1\", Order.Ascending}})",
                "in",
                "    #\"Sorted Rows\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "TabularEditor_TableGroup",
            "value": "dimension"
          }
        ]
      },
      {
        "name": "ytdfilter",
        "lineageTag": "75637f32-6ec0-4707-b23d-fcf1149951f6",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "filterytd",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "fct besteed[filterytd]",
            "lineageTag": "72784405-958b-419d-bbb2-1ede79b8a608",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "ytdfilter-8c282b4d-3b85-4249-a250-0bd47190d523",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": "values( 'fct besteed'[filterytd] )"
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "1fa8a0d46313465095794746352ee320"
          },
          {
            "name": "TabularEditor_TableGroup",
            "value": "dimension"
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "633e0d73-d12d-436e-a051-d596119c51d2",
        "toCardinality": "many",
        "fromTable": "fct budget",
        "fromColumn": "compkey_versie",
        "toTable": "budget versie",
        "toColumn": "compkey_versie"
      },
      {
        "name": "1be3dd0d-d8e1-4846-82b8-a1ae3c4af162",
        "fromTable": "fct budget",
        "fromColumn": "object_id",
        "toTable": "object",
        "toColumn": "object_id"
      },
      {
        "name": "29d20af0-6154-499f-84d1-1d4f7005b24a",
        "fromTable": "opmerkingen",
        "fromColumn": "object_id",
        "toTable": "object",
        "toColumn": "object_id"
      },
      {
        "name": "658d2fb6-8d21-4fda-83ff-94368591a67a",
        "fromTable": "fct besteed",
        "fromColumn": "object_id",
        "toTable": "object",
        "toColumn": "object_id"
      },
      {
        "name": "59408183-8eb8-495e-a1a8-b714fc465a6c",
        "fromTable": "fct besteed",
        "fromColumn": "bestelbon_id",
        "toTable": "bestelbon",
        "toColumn": "bestelbon"
      },
      {
        "name": "39ba0cec-c6d7-4ca1-a2e8-9f02f3474bfe",
        "fromTable": "fct besteed",
        "fromColumn": "soort_id",
        "toTable": "dim resultatenrekening",
        "toColumn": "soort_id"
      },
      {
        "name": "5c9d875d-7f90-4498-8f33-f58b3241f1f6",
        "fromTable": "fct budget",
        "fromColumn": "soort/artiplek_id",
        "toTable": "dim resultatenrekening",
        "toColumn": "soort_id"
      },
      {
        "name": "8680ff99-c708-4691-ae46-638591467312",
        "fromTable": "opbrengsten_structuur",
        "fromColumn": "Soort_id",
        "toTable": "dim resultatenrekening",
        "toColumn": "soort_id"
      },
      {
        "name": "b3627ee7-4f3f-4322-a21d-e253e9e967db",
        "fromTable": "precalc table AB",
        "fromColumn": "object_id",
        "toTable": "object",
        "toColumn": "object_id"
      },
      {
        "name": "df23285d-81d7-44d0-a06b-bd490a04837d",
        "fromTable": "precalc table AB",
        "fromColumn": "par1_12",
        "toTable": "par1_12",
        "toColumn": "Parameter"
      },
      {
        "name": "9625948c-a256-4b3e-a01b-a4be136ced92",
        "fromTable": "fct budget",
        "fromColumn": "yyyymm",
        "toTable": "date",
        "toColumn": "yyyy-mm"
      },
      {
        "name": "2dbd908a-c950-4d72-aeee-72082c2f9655",
        "fromTable": "opmerkingen",
        "fromColumn": "yyyymm",
        "toTable": "date",
        "toColumn": "yyyy-mm",
        "isActive": false
      },
      {
        "name": "8d205f1a-3a35-4492-9139-582550721780",
        "fromTable": "fct besteed",
        "fromColumn": "yyyymm",
        "toTable": "date",
        "toColumn": "yyyy-mm"
      },
      {
        "name": "f4a65035-c048-4862-89d2-aab3fb6c0ad5",
        "fromTable": "fct prognose opbrengsten",
        "fromColumn": "YYYY-M",
        "toTable": "date",
        "toColumn": "yyyy-mm"
      },
      {
        "name": "990712d0-a660-4fe4-9c1c-bc433afd9a7f",
        "fromTable": "precalc table AB",
        "fromColumn": "yyyymm",
        "toTable": "date",
        "toColumn": "yyyy-mm"
      },
      {
        "name": "076fc735-08f8-431a-b439-0bf49db6a9cf",
        "fromTable": "fct budget",
        "fromColumn": "filterytd",
        "toTable": "ytdfilter",
        "toColumn": "filterytd"
      },
      {
        "name": "33d08c5c-0b81-4610-b431-0a9447d3f30e",
        "fromTable": "fct besteed",
        "fromColumn": "filterytd",
        "toTable": "ytdfilter",
        "toColumn": "filterytd"
      }
    ],
    "cultures": [
      {
        "name": "nl-BE",
        "linguisticMetadata": {}
      }
    ],
    "perspectives": [
      {
        "name": "layer_specific",
        "tables": [
          {
            "name": "opmerkingen",
            "columns": [
              {
                "name": "object_id"
              },
              {
                "name": "datum"
              },
              {
                "name": "opmerking"
              },
              {
                "name": "gebruiker"
              },
              {
                "name": "yyyymm"
              }
            ],
            "measures": [
              {
                "name": "#opm."
              }
            ]
          },
          {
            "name": "Tab now",
            "columns": [
              {
                "name": "Datum"
              }
            ]
          },
          {
            "name": "field copy for drill",
            "columns": [
              {
                "name": "selectie"
              },
              {
                "name": "Parameter Fields"
              },
              {
                "name": "selectiesort"
              },
              {
                "name": "dimensie"
              },
              {
                "name": "dimselect"
              }
            ]
          },
          {
            "name": "field row",
            "columns": [
              {
                "name": "Rows selected"
              },
              {
                "name": "field row Fields"
              },
              {
                "name": "field row Order"
              },
              {
                "name": "dimensie"
              },
              {
                "name": "dimsort"
              }
            ]
          },
          {
            "name": "field measure drill",
            "columns": [
              {
                "name": "field measure drill"
              },
              {
                "name": "field measure drill Fields"
              },
              {
                "name": "field measure drill Order"
              }
            ]
          },
          {
            "name": "field object",
            "columns": [
              {
                "name": "field object"
              },
              {
                "name": "field object Fields"
              },
              {
                "name": "field object Order"
              },
              {
                "name": "weergave directiestructuur"
              }
            ]
          },
          {
            "name": "tab obligo",
            "columns": [
              {
                "name": "Value"
              },
              {
                "name": "Metric"
              },
              {
                "name": "Categorie metric"
              },
              {
                "name": "sort cat"
              },
              {
                "name": "Categorie short metric"
              },
              {
                "name": "sort short"
              },
              {
                "name": "sort metric"
              }
            ],
            "measures": [
              {
                "name": "switch obligo"
              },
              {
                "name": "switch obligo %"
              },
              {
                "name": "Value selected"
              }
            ]
          },
          {
            "name": "dim pnl",
            "columns": [
              {
                "name": "nr line item"
              },
              {
                "name": "P&L niv 1"
              },
              {
                "name": "P&L niv 12"
              },
              {
                "name": "P&L niv 3"
              },
              {
                "name": "Extra info niet in systeem"
              },
              {
                "name": "P&L niv 1 - sort"
              },
              {
                "name": "sleutel=gelijk?"
              },
              {
                "name": "sleutel_voor2023"
              },
              {
                "name": "sleutel_na2023"
              },
              {
                "name": "opbrengstenplaats"
              },
              {
                "name": "opbrengstensoort"
              },
              {
                "name": "zonder ALG/KV"
              },
              {
                "name": "opbr soort kort"
              },
              {
                "name": "opbrengstenplaats omschrijving"
              },
              {
                "name": "opbrengstensoort omschrijving"
              },
              {
                "name": "P&L niv 3.1"
              },
              {
                "name": "P&L niv 1.1"
              },
              {
                "name": "P&L niv 2"
              },
              {
                "name": "P&I nov 3"
              }
            ]
          },
          {
            "name": "importdate",
            "columns": [
              {
                "name": "import_date"
              },
              {
                "name": "yyyymm_ytd"
              },
              {
                "name": "yyyymm_ytd_min1"
              },
              {
                "name": "current_year"
              },
              {
                "name": "closed_year"
              },
              {
                "name": "closed_pyear"
              }
            ]
          },
          {
            "name": "BvA KPI",
            "columns": [
              {
                "name": "BvA KPI >"
              }
            ],
            "measures": [
              {
                "name": "BvA KPI value"
              }
            ]
          },
          {
            "name": "BvA% KPI",
            "columns": [
              {
                "name": "BvA% KPI >"
              }
            ],
            "measures": [
              {
                "name": "BvA% KPI Value"
              }
            ]
          },
          {
            "name": "switch_ytd",
            "columns": [
              {
                "name": "Filter YTD"
              },
              {
                "name": "value"
              },
              {
                "name": "Keuze"
              },
              {
                "name": "Keuze zonder obligo"
              }
            ],
            "measures": [
              {
                "name": "keuze header"
              },
              {
                "name": "keuze header 2 zonder :"
              },
              {
                "name": "switchytd"
              }
            ]
          },
          {
            "name": "switch_KPI",
            "columns": [
              {
                "name": "KPI"
              },
              {
                "name": "Value"
              }
            ],
            "measures": [
              {
                "name": "KPI if"
              },
              {
                "name": "KPI abs"
              },
              {
                "name": "KPI both"
              },
              {
                "name": "KPI rel"
              },
              {
                "name": "kpi test"
              }
            ]
          }
        ]
      },
      {
        "name": "layer_semantic",
        "tables": [
          {
            "name": "Key Measures",
            "columns": [
              {
                "name": "Column"
              }
            ],
            "measures": [
              {
                "name": "Besteed"
              },
              {
                "name": "Besteed YTD"
              },
              {
                "name": "Besteed PY"
              },
              {
                "name": "|"
              },
              {
                "name": "Besteed ALLyear"
              },
              {
                "name": "B rest maxyear"
              },
              {
                "name": "Budget basic"
              },
              {
                "name": "D MTD blank"
              },
              {
                "name": "blank_column"
              },
              {
                "name": "Besteed ABS"
              },
              {
                "name": "0"
              },
              {
                "name": "B YTD reset"
              },
              {
                "name": "B YTD og"
              },
              {
                "name": "B allyear"
              },
              {
                "name": "B YTD last"
              },
              {
                "name": "0nu"
              },
              {
                "name": "yearselected"
              },
              {
                "name": "versieselected"
              },
              {
                "name": "objecttypeselected"
              },
              {
                "name": "max datum report"
              },
              {
                "name": "closing period ytd"
              },
              {
                "name": "closed period CF"
              },
              {
                "name": "bar charts CF"
              },
              {
                "name": "B versie max"
              },
              {
                "name": "B #records"
              },
              {
                "name": "#transacties"
              },
              {
                "name": "D YTD blank"
              },
              {
                "name": "Header"
              },
              {
                "name": "KPI uitleg"
              },
              {
                "name": "max transaction yyyymm"
              },
              {
                "name": "budget_hierarchy"
              },
              {
                "name": "max transaction today"
              },
              {
                "name": "Actuals basic"
              },
              {
                "name": "Header main"
              },
              {
                "name": "Besteed YTD doorlopend"
              },
              {
                "name": "CF selectie 1m"
              },
              {
                "name": "A YTD kp"
              },
              {
                "name": "A YTD op"
              },
              {
                "name": "A YTD po"
              },
              {
                "name": "B YTG"
              },
              {
                "name": "A left to spend parameter"
              },
              {
                "name": "Budget"
              },
              {
                "name": "Budget dynamisch YTD"
              },
              {
                "name": "Budget dynamisch last"
              },
              {
                "name": "obligo"
              },
              {
                "name": "laatste update"
              },
              {
                "name": "gew. budget"
              },
              {
                "name": "werkelijk"
              },
              {
                "name": "B allyear ss"
              },
              {
                "name": "B MTD"
              },
              {
                "name": "B YTD"
              },
              {
                "name": "B YTD ss"
              },
              {
                "name": "D MTD y"
              },
              {
                "name": "D YTD y"
              },
              {
                "name": "Besteed YTG ss"
              },
              {
                "name": "Budget+eindejaarscorrectie"
              },
              {
                "name": "Besteed YTD noblank"
              },
              {
                "name": "Besteed YTD ss"
              },
              {
                "name": "D YTD ss"
              },
              {
                "name": "D% YTD ss"
              },
              {
                "name": "B MTD 0"
              },
              {
                "name": "B YTD blank"
              },
              {
                "name": "test herverdeling budget"
              },
              {
                "name": "D YTD ss all"
              },
              {
                "name": "%obligo cf"
              },
              {
                "name": "%obligo"
              },
              {
                "name": "Actuals"
              },
              {
                "name": "B YTD ss all"
              },
              {
                "name": "D MTD blank 0"
              },
              {
                "name": "D YTD blank 0"
              },
              {
                "name": "Y as schaal"
              },
              {
                "name": "test schaal"
              },
              {
                "name": "obligo YTD"
              },
              {
                "name": "Actuals YTD"
              },
              {
                "name": "blank obligo graph"
              },
              {
                "name": "D YTD ss all ytd graph"
              },
              {
                "name": "D% YTD ss yearb"
              },
              {
                "name": "D MTD blank og"
              },
              {
                "name": "D YTD blank og"
              },
              {
                "name": "D YTD ss all og"
              },
              {
                "name": "obligo basic"
              },
              {
                "name": "max month current year (2022-12)"
              },
              {
                "name": "ytdfilter"
              },
              {
                "name": "max transaction yyyymmdd"
              },
              {
                "name": "days since refresh"
              },
              {
                "name": "Budget basic x"
              },
              {
                "name": "budget basic ytd"
              },
              {
                "name": "D YTD basis"
              },
              {
                "name": "D YTD basis A<B"
              },
              {
                "name": "D YTD basis A>B"
              },
              {
                "name": "B versie max numeric"
              },
              {
                "name": "B YTD ss scope"
              },
              {
                "name": "D YTD ss scope"
              },
              {
                "name": "D% YTD ss scope"
              },
              {
                "name": "versie precalc"
              },
              {
                "name": "budget 2022 v000"
              },
              {
                "name": "budget 2023 v000"
              },
              {
                "name": "delta budget v000"
              },
              {
                "name": "D"
              },
              {
                "name": "a"
              },
              {
                "name": "a if"
              },
              {
                "name": "a na23"
              },
              {
                "name": "a voor23"
              },
              {
                "name": "b"
              },
              {
                "name": "b if"
              },
              {
                "name": "b na23"
              },
              {
                "name": "b voor23"
              },
              {
                "name": "fixed column width"
              },
              {
                "name": "ifl timeperiod"
              },
              {
                "name": "switch x"
              },
              {
                "name": "switch_measures"
              }
            ]
          },
          {
            "name": "date",
            "columns": [
              {
                "name": "Year"
              },
              {
                "name": "Month"
              },
              {
                "name": "yeartext"
              },
              {
                "name": "Year Month Number"
              },
              {
                "name": "ytd?"
              },
              {
                "name": "Year Month Key"
              },
              {
                "name": "Year Quarter"
              },
              {
                "name": "Year Quarter Number"
              },
              {
                "name": "Quarter"
              },
              {
                "name": "Year Month"
              },
              {
                "name": "yyyy-mm"
              },
              {
                "name": "Month Number"
              },
              {
                "name": "Month In Quarter Number"
              },
              {
                "name": "Fiscal Year"
              },
              {
                "name": "Fiscal Year Number"
              },
              {
                "name": "Fiscal Year Quarter"
              },
              {
                "name": "Fiscal Year Quarter Number"
              },
              {
                "name": "Fiscal Quarter"
              },
              {
                "name": "Fiscal Month"
              },
              {
                "name": "Fiscal Month Number"
              },
              {
                "name": "Fiscal Month In Quarter Number"
              },
              {
                "name": "maandindex"
              },
              {
                "name": "jaarindex"
              },
              {
                "name": "now?"
              },
              {
                "name": "perdiode"
              },
              {
                "name": "periode code"
              }
            ],
            "hierarchies": [
              {
                "name": "year Hierarchy"
              }
            ],
            "measures": [
              {
                "name": "MaxDate"
              },
              {
                "name": "yeartoday"
              },
              {
                "name": "MaxYear"
              },
              {
                "name": "MaxYYYYMM"
              },
              {
                "name": "ytdfiltermeasure"
              }
            ]
          },
          {
            "name": "bestelbon",
            "columns": [
              {
                "name": "bestel_tekst"
              },
              {
                "name": "inkoopartikel"
              },
              {
                "name": "leverancier_id"
              },
              {
                "name": "lev_land"
              },
              {
                "name": "lev_naam"
              },
              {
                "name": "lev_stad"
              },
              {
                "name": "lev_postcode"
              },
              {
                "name": "lev_straat"
              },
              {
                "name": "lev_bankrekening"
              },
              {
                "name": "bestelbonnummer"
              },
              {
                "name": "bestelbon_positie"
              },
              {
                "name": "bestelbon"
              },
              {
                "name": "ingevoerd_door"
              }
            ]
          },
          {
            "name": "fct budget",
            "columns": [
              {
                "name": "soort_id"
              },
              {
                "name": "artiplek_id"
              },
              {
                "name": "versie"
              },
              {
                "name": "yyyymm"
              },
              {
                "name": "afkorting"
              },
              {
                "name": "ratioflag"
              },
              {
                "name": "compkey_versie"
              },
              {
                "name": "budget"
              },
              {
                "name": "objecttype"
              },
              {
                "name": "object_id"
              },
              {
                "name": "jaarbudget"
              },
              {
                "name": "soort/artiplek_id"
              },
              {
                "name": "soort_id_zonderalgkv"
              },
              {
                "name": "af_pe_ytd"
              },
              {
                "name": "filterytd"
              },
              {
                "name": "ratio"
              },
              {
                "name": "sleutelpnl switch"
              }
            ]
          },
          {
            "name": "field column",
            "columns": [
              {
                "name": "Columns selected"
              },
              {
                "name": "Parameter Fields"
              },
              {
                "name": "Parameter Order"
              },
              {
                "name": "Categorie"
              },
              {
                "name": "Categorie_sort"
              }
            ]
          },
          {
            "name": "budget versie",
            "columns": [
              {
                "name": "versie"
              },
              {
                "name": "objecttype"
              },
              {
                "name": "compkey_versie"
              }
            ]
          },
          {
            "name": "object",
            "columns": [
              {
                "name": "path"
              },
              {
                "name": "depth"
              },
              {
                "name": "Level1"
              },
              {
                "name": "Directie"
              },
              {
                "name": "Level3"
              },
              {
                "name": "Level4"
              },
              {
                "name": "Level5"
              },
              {
                "name": "Level6"
              },
              {
                "name": "objecttype"
              },
              {
                "name": "object+omschrijving"
              },
              {
                "name": "object_id"
              },
              {
                "name": "object_description"
              },
              {
                "name": "object_parent"
              },
              {
                "name": "1"
              },
              {
                "name": "2"
              },
              {
                "name": "3"
              },
              {
                "name": "4"
              },
              {
                "name": "5"
              },
              {
                "name": "6"
              },
              {
                "name": "1sort"
              },
              {
                "name": "2sort"
              },
              {
                "name": "3sort"
              },
              {
                "name": "4sort"
              },
              {
                "name": "5sort"
              },
              {
                "name": "6sort"
              },
              {
                "name": "object_id_nc"
              },
              {
                "name": "object_parent_nc"
              },
              {
                "name": "index_nc"
              },
              {
                "name": "artikel"
              },
              {
                "name": "productiehuis"
              },
              {
                "name": "categorie"
              },
              {
                "name": "kanaal"
              },
              {
                "name": "productiereeks_fin_rapport"
              },
              {
                "name": "subgenre"
              },
              {
                "name": "klant"
              },
              {
                "name": "ipro_epro"
              },
              {
                "name": "budgetbeheer_std"
              },
              {
                "name": "budgetbeheer_plp"
              },
              {
                "name": "raamovereenkomst"
              },
              {
                "name": "netproducent"
              },
              {
                "name": "beschrijving_artikel_uppercase"
              }
            ],
            "hierarchies": [
              {
                "name": "Object Hierarchy"
              },
              {
                "name": "Object Hierarchy basic"
              },
              {
                "name": "Object Hierarchy no code"
              }
            ],
            "measures": [
              {
                "name": "RowDepth"
              },
              {
                "name": "BrowseDepth"
              },
              {
                "name": "path min"
              },
              {
                "name": "BrowseDepthNoCode"
              },
              {
                "name": "3 count"
              }
            ]
          },
          {
            "name": "par1_12",
            "columns": [
              {
                "name": "Parameter"
              },
              {
                "name": "budget is gelijk aan actuals tot maand"
              },
              {
                "name": "adaptief budget tot maand"
              }
            ],
            "measures": [
              {
                "name": "Parameter Value"
              },
              {
                "name": "Vanaf wanneer adaptief?"
              }
            ]
          },
          {
            "name": "fct besteed",
            "columns": [
              {
                "name": "object_id"
              },
              {
                "name": "objecttype"
              },
              {
                "name": "boekdatum"
              },
              {
                "name": "yyyymm"
              },
              {
                "name": "artikel_id"
              },
              {
                "name": "soort_id"
              },
              {
                "name": "omschrijving"
              },
              {
                "name": "actual"
              },
              {
                "name": "obligo"
              },
              {
                "name": "bestelbon_id"
              },
              {
                "name": "termijnpositie"
              },
              {
                "name": "import_date"
              },
              {
                "name": "a_o"
              },
              {
                "name": "rn"
              },
              {
                "name": "soort_id_zonderalgkv"
              },
              {
                "name": "af_pe_ytd"
              },
              {
                "name": "filterytd"
              },
              {
                "name": "sleutelpnl switch"
              }
            ],
            "measures": [
              {
                "name": "actuals total"
              },
              {
                "name": "obligo total"
              },
              {
                "name": "besteed total"
              }
            ]
          },
          {
            "name": "opbrengsten_structuur",
            "columns": [
              {
                "name": "Pijlers"
              },
              {
                "name": "Soort+beschrijving"
              },
              {
                "name": "Begrenzing"
              },
              {
                "name": "Beschrijving begrenzing"
              },
              {
                "name": "Soort_id"
              },
              {
                "name": "plafond"
              },
              {
                "name": "Categorie pijler"
              }
            ],
            "measures": [
              {
                "name": "opbrengsten"
              },
              {
                "name": "OP PY"
              },
              {
                "name": "OP PY % total"
              },
              {
                "name": "OP PY total"
              },
              {
                "name": "budget eerst"
              },
              {
                "name": "prognose "
              },
              {
                "name": "check"
              },
              {
                "name": "scope_object"
              },
              {
                "name": "delta bva"
              },
              {
                "name": "plafond max"
              },
              {
                "name": "plafond max multiplied"
              },
              {
                "name": "budget laatst"
              },
              {
                "name": "headar pvp"
              }
            ]
          },
          {
            "name": "weergave_getal",
            "columns": [
              {
                "name": "Weergave getal"
              },
              {
                "name": "Ordinal"
              }
            ],
            "measures": [
              {
                "name": "txt weergave getal"
              }
            ]
          },
          {
            "name": "YTDMTD",
            "columns": [
              {
                "name": "MTD/YTD"
              },
              {
                "name": "Ordinal"
              }
            ]
          },
          {
            "name": "fct prognose opbrengsten",
            "columns": [
              {
                "name": "Rekening"
              },
              {
                "name": "prognose jaarbasis"
              },
              {
                "name": "YYYY-M"
              },
              {
                "name": "maandbasis verdeling %"
              },
              {
                "name": "prognose maandbasis"
              }
            ]
          },
          {
            "name": "precalc table AB",
            "columns": [
              {
                "name": "object_id"
              },
              {
                "name": "yyyymm"
              },
              {
                "name": "year"
              },
              {
                "name": "par1_12"
              },
              {
                "name": "versie"
              },
              {
                "name": "a"
              },
              {
                "name": "b_og"
              },
              {
                "name": "b_dyn"
              },
              {
                "name": "objecttype"
              },
              {
                "name": "versie_og"
              },
              {
                "name": "compkey_versie"
              }
            ]
          },
          {
            "name": "soort",
            "columns": [
              {
                "name": "link5"
              },
              {
                "name": "is_id"
              },
              {
                "name": "nodename"
              },
              {
                "name": "childnode_id"
              },
              {
                "name": "parentnode_id"
              },
              {
                "name": "firstchildnode_id"
              },
              {
                "name": "nextnode_id"
              },
              {
                "name": "soort_id"
              },
              {
                "name": "soort_id_tag"
              },
              {
                "name": "beschrijving soort_id"
              },
              {
                "name": "import_date"
              },
              {
                "name": "l2"
              },
              {
                "name": "soort_id_zonderalgkv"
              },
              {
                "name": "af_pe_ytd"
              },
              {
                "name": "path"
              },
              {
                "name": "depth"
              },
              {
                "name": "Level2"
              },
              {
                "name": "Level3"
              },
              {
                "name": "Level4"
              },
              {
                "name": "Level5"
              },
              {
                "name": "Level6"
              },
              {
                "name": "Level7"
              },
              {
                "name": "Count uniq"
              },
              {
                "name": "Count uniq2"
              }
            ],
            "measures": [
              {
                "name": "ShowRow_soort"
              },
              {
                "name": "BrowseDepth_soort"
              },
              {
                "name": "RowDepth_soort"
              },
              {
                "name": "actuals pnl"
              }
            ]
          },
          {
            "name": "dim resultatenrekening",
            "columns": [
              {
                "name": "link5"
              },
              {
                "name": "is_id"
              },
              {
                "name": "nodename"
              },
              {
                "name": "childnode_id"
              },
              {
                "name": "parentnode_id"
              },
              {
                "name": "firstchildnode_id"
              },
              {
                "name": "nextnode_id"
              },
              {
                "name": "soort_id"
              },
              {
                "name": "soort_id_tag"
              },
              {
                "name": "beschrijving soort_id"
              },
              {
                "name": "import_date"
              },
              {
                "name": "l2"
              },
              {
                "name": "soort_id_zonderalgkv"
              },
              {
                "name": "af_pe_ytd"
              },
              {
                "name": "path"
              },
              {
                "name": "depth"
              },
              {
                "name": "Level2"
              },
              {
                "name": "Level3"
              },
              {
                "name": "Level4"
              },
              {
                "name": "Level5"
              },
              {
                "name": "Level6"
              },
              {
                "name": "Level7"
              },
              {
                "name": "Count uniq"
              },
              {
                "name": "Count uniq2"
              },
              {
                "name": "soort+beschrijving"
              }
            ],
            "hierarchies": [
              {
                "name": "soort hierarchy"
              }
            ]
          },
          {
            "name": "ytdfilter",
            "columns": [
              {
                "name": "filterytd"
              }
            ]
          }
        ]
      },
      {
        "name": "!PNL",
        "tables": [
          {
            "name": "Key Measures",
            "columns": [
              {
                "name": "Column"
              }
            ],
            "measures": [
              {
                "name": "a"
              },
              {
                "name": "a if"
              },
              {
                "name": "a na23"
              },
              {
                "name": "a voor23"
              },
              {
                "name": "b"
              },
              {
                "name": "b if"
              },
              {
                "name": "b na23"
              },
              {
                "name": "b voor23"
              },
              {
                "name": "fixed column width"
              },
              {
                "name": "ifl timeperiod"
              },
              {
                "name": "switch x"
              },
              {
                "name": "switch_measures"
              },
              {
                "name": "|"
              },
              {
                "name": "blank_column"
              },
              {
                "name": "0"
              },
              {
                "name": "0nu"
              },
              {
                "name": "yearselected"
              },
              {
                "name": "versieselected"
              },
              {
                "name": "objecttypeselected"
              },
              {
                "name": "max datum report"
              },
              {
                "name": "closing period ytd"
              },
              {
                "name": "closed period CF"
              },
              {
                "name": "bar charts CF"
              },
              {
                "name": "Header"
              },
              {
                "name": "KPI uitleg"
              },
              {
                "name": "max transaction yyyymm"
              },
              {
                "name": "max transaction today"
              },
              {
                "name": "Header main"
              },
              {
                "name": "CF selectie 1m"
              },
              {
                "name": "A YTD kp"
              },
              {
                "name": "A YTD op"
              },
              {
                "name": "A YTD po"
              },
              {
                "name": "laatste update"
              },
              {
                "name": "test herverdeling budget"
              },
              {
                "name": "Y as schaal"
              },
              {
                "name": "test schaal"
              },
              {
                "name": "max month current year (2022-12)"
              },
              {
                "name": "ytdfilter"
              },
              {
                "name": "max transaction yyyymmdd"
              },
              {
                "name": "days since refresh"
              },
              {
                "name": "versie precalc"
              }
            ]
          },
          {
            "name": "date",
            "columns": [
              {
                "name": "Year"
              },
              {
                "name": "Month"
              },
              {
                "name": "yeartext"
              },
              {
                "name": "Year Month Number"
              },
              {
                "name": "ytd?"
              },
              {
                "name": "Year Month Key"
              },
              {
                "name": "Year Quarter"
              },
              {
                "name": "Year Quarter Number"
              },
              {
                "name": "Quarter"
              },
              {
                "name": "Year Month"
              },
              {
                "name": "yyyy-mm"
              },
              {
                "name": "Month Number"
              },
              {
                "name": "Month In Quarter Number"
              },
              {
                "name": "Fiscal Year"
              },
              {
                "name": "Fiscal Year Number"
              },
              {
                "name": "Fiscal Year Quarter"
              },
              {
                "name": "Fiscal Year Quarter Number"
              },
              {
                "name": "Fiscal Quarter"
              },
              {
                "name": "Fiscal Month"
              },
              {
                "name": "Fiscal Month Number"
              },
              {
                "name": "Fiscal Month In Quarter Number"
              },
              {
                "name": "maandindex"
              },
              {
                "name": "jaarindex"
              },
              {
                "name": "now?"
              },
              {
                "name": "perdiode"
              },
              {
                "name": "periode code"
              }
            ],
            "hierarchies": [
              {
                "name": "year Hierarchy"
              }
            ],
            "measures": [
              {
                "name": "MaxDate"
              },
              {
                "name": "yeartoday"
              },
              {
                "name": "MaxYear"
              },
              {
                "name": "MaxYYYYMM"
              },
              {
                "name": "ytdfiltermeasure"
              }
            ]
          },
          {
            "name": "fct budget",
            "columns": [
              {
                "name": "soort_id"
              },
              {
                "name": "artiplek_id"
              },
              {
                "name": "versie"
              },
              {
                "name": "yyyymm"
              },
              {
                "name": "afkorting"
              },
              {
                "name": "ratioflag"
              },
              {
                "name": "compkey_versie"
              },
              {
                "name": "budget"
              },
              {
                "name": "objecttype"
              },
              {
                "name": "object_id"
              },
              {
                "name": "jaarbudget"
              },
              {
                "name": "soort/artiplek_id"
              },
              {
                "name": "soort_id_zonderalgkv"
              },
              {
                "name": "af_pe_ytd"
              },
              {
                "name": "filterytd"
              },
              {
                "name": "ratio"
              },
              {
                "name": "sleutelpnl switch"
              }
            ]
          },
          {
            "name": "budget versie",
            "columns": [
              {
                "name": "versie"
              },
              {
                "name": "objecttype"
              },
              {
                "name": "compkey_versie"
              }
            ]
          },
          {
            "name": "fct besteed",
            "columns": [
              {
                "name": "object_id"
              },
              {
                "name": "objecttype"
              },
              {
                "name": "boekdatum"
              },
              {
                "name": "yyyymm"
              },
              {
                "name": "artikel_id"
              },
              {
                "name": "soort_id"
              },
              {
                "name": "omschrijving"
              },
              {
                "name": "actual"
              },
              {
                "name": "obligo"
              },
              {
                "name": "bestelbon_id"
              },
              {
                "name": "termijnpositie"
              },
              {
                "name": "import_date"
              },
              {
                "name": "a_o"
              },
              {
                "name": "rn"
              },
              {
                "name": "soort_id_zonderalgkv"
              },
              {
                "name": "af_pe_ytd"
              },
              {
                "name": "filterytd"
              },
              {
                "name": "sleutelpnl switch"
              }
            ],
            "measures": [
              {
                "name": "actuals total"
              },
              {
                "name": "obligo total"
              },
              {
                "name": "besteed total"
              }
            ]
          },
          {
            "name": "dim pnl",
            "columns": [
              {
                "name": "nr line item"
              },
              {
                "name": "P&L niv 1"
              },
              {
                "name": "P&L niv 12"
              },
              {
                "name": "P&L niv 3"
              },
              {
                "name": "Extra info niet in systeem"
              },
              {
                "name": "P&L niv 1 - sort"
              },
              {
                "name": "sleutel=gelijk?"
              },
              {
                "name": "sleutel_voor2023"
              },
              {
                "name": "sleutel_na2023"
              },
              {
                "name": "opbrengstenplaats"
              },
              {
                "name": "opbrengstensoort"
              },
              {
                "name": "zonder ALG/KV"
              },
              {
                "name": "opbr soort kort"
              },
              {
                "name": "opbrengstenplaats omschrijving"
              },
              {
                "name": "opbrengstensoort omschrijving"
              },
              {
                "name": "P&L niv 3.1"
              },
              {
                "name": "P&L niv 1.1"
              },
              {
                "name": "P&L niv 2"
              },
              {
                "name": "P&I nov 3"
              }
            ]
          },
          {
            "name": "dim resultatenrekening",
            "columns": [
              {
                "name": "link5"
              },
              {
                "name": "is_id"
              },
              {
                "name": "nodename"
              },
              {
                "name": "childnode_id"
              },
              {
                "name": "parentnode_id"
              },
              {
                "name": "firstchildnode_id"
              },
              {
                "name": "nextnode_id"
              },
              {
                "name": "soort_id"
              },
              {
                "name": "soort_id_tag"
              },
              {
                "name": "beschrijving soort_id"
              },
              {
                "name": "import_date"
              },
              {
                "name": "l2"
              },
              {
                "name": "soort_id_zonderalgkv"
              },
              {
                "name": "af_pe_ytd"
              },
              {
                "name": "path"
              },
              {
                "name": "depth"
              },
              {
                "name": "Level2"
              },
              {
                "name": "Level3"
              },
              {
                "name": "Level4"
              },
              {
                "name": "Level5"
              },
              {
                "name": "Level6"
              },
              {
                "name": "Level7"
              },
              {
                "name": "Count uniq"
              },
              {
                "name": "Count uniq2"
              },
              {
                "name": "soort+beschrijving"
              }
            ],
            "hierarchies": [
              {
                "name": "soort hierarchy"
              }
            ]
          },
          {
            "name": "ytdfilter",
            "columns": [
              {
                "name": "filterytd"
              }
            ]
          }
        ]
      },
      {
        "name": "!YTD",
        "tables": [
          {
            "name": "Key Measures",
            "columns": [
              {
                "name": "Column"
              }
            ],
            "measures": [
              {
                "name": "Besteed"
              },
              {
                "name": "Besteed YTD"
              },
              {
                "name": "Besteed PY"
              },
              {
                "name": "Besteed ALLyear"
              },
              {
                "name": "B rest maxyear"
              },
              {
                "name": "B YTD og"
              },
              {
                "name": "B allyear"
              },
              {
                "name": "B YTD last"
              },
              {
                "name": "B versie max"
              },
              {
                "name": "B #records"
              },
              {
                "name": "budget_hierarchy"
              },
              {
                "name": "B YTG"
              },
              {
                "name": "A left to spend parameter"
              },
              {
                "name": "Budget dynamisch YTD"
              },
              {
                "name": "Budget dynamisch last"
              },
              {
                "name": "B allyear ss"
              },
              {
                "name": "B MTD"
              },
              {
                "name": "B YTD"
              },
              {
                "name": "B YTD ss"
              },
              {
                "name": "Budget+eindejaarscorrectie"
              },
              {
                "name": "B MTD 0"
              },
              {
                "name": "B YTD blank"
              },
              {
                "name": "B YTD ss all"
              },
              {
                "name": "Budget basic"
              },
              {
                "name": "Budget"
              },
              {
                "name": "Budget basic x"
              },
              {
                "name": "budget basic ytd"
              },
              {
                "name": "D MTD blank"
              },
              {
                "name": "Besteed ABS"
              },
              {
                "name": "B YTD reset"
              },
              {
                "name": "#transacties"
              },
              {
                "name": "D YTD blank"
              },
              {
                "name": "Actuals basic"
              },
              {
                "name": "Besteed YTD doorlopend"
              },
              {
                "name": "obligo"
              },
              {
                "name": "gew. budget"
              },
              {
                "name": "werkelijk"
              },
              {
                "name": "D MTD y"
              },
              {
                "name": "D YTD y"
              },
              {
                "name": "Besteed YTG ss"
              },
              {
                "name": "Besteed YTD noblank"
              },
              {
                "name": "Besteed YTD ss"
              },
              {
                "name": "D YTD ss"
              },
              {
                "name": "D% YTD ss"
              },
              {
                "name": "D YTD ss all"
              },
              {
                "name": "%obligo cf"
              },
              {
                "name": "%obligo"
              },
              {
                "name": "Actuals"
              },
              {
                "name": "D MTD blank 0"
              },
              {
                "name": "D YTD blank 0"
              },
              {
                "name": "obligo YTD"
              },
              {
                "name": "Actuals YTD"
              },
              {
                "name": "blank obligo graph"
              },
              {
                "name": "D YTD ss all ytd graph"
              },
              {
                "name": "D% YTD ss yearb"
              },
              {
                "name": "D MTD blank og"
              },
              {
                "name": "D YTD blank og"
              },
              {
                "name": "D YTD ss all og"
              },
              {
                "name": "obligo basic"
              },
              {
                "name": "D YTD basis"
              },
              {
                "name": "D YTD basis A<B"
              },
              {
                "name": "D YTD basis A>B"
              },
              {
                "name": "B versie max numeric"
              },
              {
                "name": "B YTD ss scope"
              },
              {
                "name": "D YTD ss scope"
              },
              {
                "name": "D% YTD ss scope"
              },
              {
                "name": "budget 2022 v000"
              },
              {
                "name": "budget 2023 v000"
              },
              {
                "name": "delta budget v000"
              },
              {
                "name": "D"
              },
              {
                "name": "|"
              },
              {
                "name": "blank_column"
              },
              {
                "name": "0"
              },
              {
                "name": "0nu"
              },
              {
                "name": "yearselected"
              },
              {
                "name": "versieselected"
              },
              {
                "name": "objecttypeselected"
              },
              {
                "name": "max datum report"
              },
              {
                "name": "closing period ytd"
              },
              {
                "name": "closed period CF"
              },
              {
                "name": "bar charts CF"
              },
              {
                "name": "Header"
              },
              {
                "name": "KPI uitleg"
              },
              {
                "name": "max transaction yyyymm"
              },
              {
                "name": "max transaction today"
              },
              {
                "name": "Header main"
              },
              {
                "name": "CF selectie 1m"
              },
              {
                "name": "A YTD kp"
              },
              {
                "name": "A YTD op"
              },
              {
                "name": "A YTD po"
              },
              {
                "name": "laatste update"
              },
              {
                "name": "test herverdeling budget"
              },
              {
                "name": "Y as schaal"
              },
              {
                "name": "test schaal"
              },
              {
                "name": "max month current year (2022-12)"
              },
              {
                "name": "ytdfilter"
              },
              {
                "name": "max transaction yyyymmdd"
              },
              {
                "name": "days since refresh"
              },
              {
                "name": "versie precalc"
              }
            ]
          },
          {
            "name": "date",
            "columns": [
              {
                "name": "Year"
              },
              {
                "name": "Month"
              },
              {
                "name": "yeartext"
              },
              {
                "name": "Year Month Number"
              },
              {
                "name": "ytd?"
              },
              {
                "name": "Year Month Key"
              },
              {
                "name": "Year Quarter"
              },
              {
                "name": "Year Quarter Number"
              },
              {
                "name": "Quarter"
              },
              {
                "name": "Year Month"
              },
              {
                "name": "yyyy-mm"
              },
              {
                "name": "Month Number"
              },
              {
                "name": "Month In Quarter Number"
              },
              {
                "name": "Fiscal Year"
              },
              {
                "name": "Fiscal Year Number"
              },
              {
                "name": "Fiscal Year Quarter"
              },
              {
                "name": "Fiscal Year Quarter Number"
              },
              {
                "name": "Fiscal Quarter"
              },
              {
                "name": "Fiscal Month"
              },
              {
                "name": "Fiscal Month Number"
              },
              {
                "name": "Fiscal Month In Quarter Number"
              },
              {
                "name": "maandindex"
              },
              {
                "name": "jaarindex"
              },
              {
                "name": "now?"
              },
              {
                "name": "perdiode"
              },
              {
                "name": "periode code"
              }
            ],
            "hierarchies": [
              {
                "name": "year Hierarchy"
              }
            ],
            "measures": [
              {
                "name": "MaxDate"
              },
              {
                "name": "yeartoday"
              },
              {
                "name": "MaxYear"
              },
              {
                "name": "MaxYYYYMM"
              },
              {
                "name": "ytdfiltermeasure"
              }
            ]
          },
          {
            "name": "bestelbon",
            "columns": [
              {
                "name": "bestel_tekst"
              },
              {
                "name": "inkoopartikel"
              },
              {
                "name": "leverancier_id"
              },
              {
                "name": "lev_land"
              },
              {
                "name": "lev_naam"
              },
              {
                "name": "lev_stad"
              },
              {
                "name": "lev_postcode"
              },
              {
                "name": "lev_straat"
              },
              {
                "name": "lev_bankrekening"
              },
              {
                "name": "bestelbonnummer"
              },
              {
                "name": "bestelbon_positie"
              },
              {
                "name": "bestelbon"
              },
              {
                "name": "ingevoerd_door"
              }
            ]
          },
          {
            "name": "fct budget",
            "columns": [
              {
                "name": "soort_id"
              },
              {
                "name": "artiplek_id"
              },
              {
                "name": "versie"
              },
              {
                "name": "yyyymm"
              },
              {
                "name": "afkorting"
              },
              {
                "name": "ratioflag"
              },
              {
                "name": "compkey_versie"
              },
              {
                "name": "budget"
              },
              {
                "name": "objecttype"
              },
              {
                "name": "object_id"
              },
              {
                "name": "jaarbudget"
              },
              {
                "name": "soort/artiplek_id"
              },
              {
                "name": "soort_id_zonderalgkv"
              },
              {
                "name": "af_pe_ytd"
              },
              {
                "name": "filterytd"
              },
              {
                "name": "ratio"
              },
              {
                "name": "sleutelpnl switch"
              }
            ]
          },
          {
            "name": "field column",
            "columns": [
              {
                "name": "Columns selected"
              },
              {
                "name": "Parameter Fields"
              },
              {
                "name": "Parameter Order"
              },
              {
                "name": "Categorie"
              },
              {
                "name": "Categorie_sort"
              }
            ]
          },
          {
            "name": "budget versie",
            "columns": [
              {
                "name": "versie"
              },
              {
                "name": "objecttype"
              },
              {
                "name": "compkey_versie"
              }
            ]
          },
          {
            "name": "object",
            "columns": [
              {
                "name": "path"
              },
              {
                "name": "depth"
              },
              {
                "name": "Level1"
              },
              {
                "name": "Directie"
              },
              {
                "name": "Level3"
              },
              {
                "name": "Level4"
              },
              {
                "name": "Level5"
              },
              {
                "name": "Level6"
              },
              {
                "name": "objecttype"
              },
              {
                "name": "object+omschrijving"
              },
              {
                "name": "object_id"
              },
              {
                "name": "object_description"
              },
              {
                "name": "object_parent"
              },
              {
                "name": "1"
              },
              {
                "name": "2"
              },
              {
                "name": "3"
              },
              {
                "name": "4"
              },
              {
                "name": "5"
              },
              {
                "name": "6"
              },
              {
                "name": "1sort"
              },
              {
                "name": "2sort"
              },
              {
                "name": "3sort"
              },
              {
                "name": "4sort"
              },
              {
                "name": "5sort"
              },
              {
                "name": "6sort"
              },
              {
                "name": "object_id_nc"
              },
              {
                "name": "object_parent_nc"
              },
              {
                "name": "index_nc"
              },
              {
                "name": "artikel"
              },
              {
                "name": "productiehuis"
              },
              {
                "name": "categorie"
              },
              {
                "name": "kanaal"
              },
              {
                "name": "productiereeks_fin_rapport"
              },
              {
                "name": "subgenre"
              },
              {
                "name": "klant"
              },
              {
                "name": "ipro_epro"
              },
              {
                "name": "budgetbeheer_std"
              },
              {
                "name": "budgetbeheer_plp"
              },
              {
                "name": "raamovereenkomst"
              },
              {
                "name": "netproducent"
              },
              {
                "name": "beschrijving_artikel_uppercase"
              }
            ],
            "hierarchies": [
              {
                "name": "Object Hierarchy"
              },
              {
                "name": "Object Hierarchy basic"
              },
              {
                "name": "Object Hierarchy no code"
              }
            ],
            "measures": [
              {
                "name": "RowDepth"
              },
              {
                "name": "BrowseDepth"
              },
              {
                "name": "path min"
              },
              {
                "name": "BrowseDepthNoCode"
              },
              {
                "name": "3 count"
              }
            ]
          },
          {
            "name": "fct besteed",
            "columns": [
              {
                "name": "object_id"
              },
              {
                "name": "objecttype"
              },
              {
                "name": "boekdatum"
              },
              {
                "name": "yyyymm"
              },
              {
                "name": "artikel_id"
              },
              {
                "name": "soort_id"
              },
              {
                "name": "omschrijving"
              },
              {
                "name": "actual"
              },
              {
                "name": "obligo"
              },
              {
                "name": "bestelbon_id"
              },
              {
                "name": "termijnpositie"
              },
              {
                "name": "import_date"
              },
              {
                "name": "a_o"
              },
              {
                "name": "rn"
              },
              {
                "name": "soort_id_zonderalgkv"
              },
              {
                "name": "af_pe_ytd"
              },
              {
                "name": "filterytd"
              },
              {
                "name": "sleutelpnl switch"
              }
            ],
            "measures": [
              {
                "name": "actuals total"
              },
              {
                "name": "obligo total"
              },
              {
                "name": "besteed total"
              }
            ]
          },
          {
            "name": "precalc table AB",
            "columns": [
              {
                "name": "object_id"
              },
              {
                "name": "yyyymm"
              },
              {
                "name": "year"
              },
              {
                "name": "par1_12"
              },
              {
                "name": "versie"
              },
              {
                "name": "a"
              },
              {
                "name": "b_og"
              },
              {
                "name": "b_dyn"
              },
              {
                "name": "objecttype"
              },
              {
                "name": "versie_og"
              },
              {
                "name": "compkey_versie"
              }
            ]
          },
          {
            "name": "soort",
            "columns": [
              {
                "name": "link5"
              },
              {
                "name": "is_id"
              },
              {
                "name": "nodename"
              },
              {
                "name": "childnode_id"
              },
              {
                "name": "parentnode_id"
              },
              {
                "name": "firstchildnode_id"
              },
              {
                "name": "nextnode_id"
              },
              {
                "name": "soort_id"
              },
              {
                "name": "soort_id_tag"
              },
              {
                "name": "beschrijving soort_id"
              },
              {
                "name": "import_date"
              },
              {
                "name": "l2"
              },
              {
                "name": "soort_id_zonderalgkv"
              },
              {
                "name": "af_pe_ytd"
              },
              {
                "name": "path"
              },
              {
                "name": "depth"
              },
              {
                "name": "Level2"
              },
              {
                "name": "Level3"
              },
              {
                "name": "Level4"
              },
              {
                "name": "Level5"
              },
              {
                "name": "Level6"
              },
              {
                "name": "Level7"
              },
              {
                "name": "Count uniq"
              },
              {
                "name": "Count uniq2"
              }
            ],
            "measures": [
              {
                "name": "ShowRow_soort"
              },
              {
                "name": "BrowseDepth_soort"
              },
              {
                "name": "RowDepth_soort"
              },
              {
                "name": "actuals pnl"
              }
            ]
          },
          {
            "name": "ytdfilter",
            "columns": [
              {
                "name": "filterytd"
              }
            ]
          }
        ]
      },
      {
        "name": "!opbrengten",
        "tables": [
          {
            "name": "Key Measures",
            "columns": [
              {
                "name": "Column"
              }
            ],
            "measures": [
              {
                "name": "Besteed"
              },
              {
                "name": "Besteed YTD"
              },
              {
                "name": "Besteed PY"
              },
              {
                "name": "|"
              },
              {
                "name": "Besteed ALLyear"
              },
              {
                "name": "B rest maxyear"
              },
              {
                "name": "Budget basic"
              },
              {
                "name": "D MTD blank"
              },
              {
                "name": "blank_column"
              },
              {
                "name": "Besteed ABS"
              },
              {
                "name": "0"
              },
              {
                "name": "B YTD reset"
              },
              {
                "name": "B YTD og"
              },
              {
                "name": "B allyear"
              },
              {
                "name": "B YTD last"
              },
              {
                "name": "0nu"
              },
              {
                "name": "yearselected"
              },
              {
                "name": "versieselected"
              },
              {
                "name": "objecttypeselected"
              },
              {
                "name": "max datum report"
              },
              {
                "name": "closing period ytd"
              },
              {
                "name": "closed period CF"
              },
              {
                "name": "bar charts CF"
              },
              {
                "name": "B versie max"
              },
              {
                "name": "B #records"
              },
              {
                "name": "#transacties"
              },
              {
                "name": "D YTD blank"
              },
              {
                "name": "Header"
              },
              {
                "name": "KPI uitleg"
              },
              {
                "name": "max transaction yyyymm"
              },
              {
                "name": "budget_hierarchy"
              },
              {
                "name": "max transaction today"
              },
              {
                "name": "Actuals basic"
              },
              {
                "name": "Header main"
              },
              {
                "name": "Besteed YTD doorlopend"
              },
              {
                "name": "CF selectie 1m"
              },
              {
                "name": "A YTD kp"
              },
              {
                "name": "A YTD op"
              },
              {
                "name": "A YTD po"
              },
              {
                "name": "B YTG"
              },
              {
                "name": "A left to spend parameter"
              },
              {
                "name": "Budget"
              },
              {
                "name": "Budget dynamisch YTD"
              },
              {
                "name": "Budget dynamisch last"
              },
              {
                "name": "obligo"
              },
              {
                "name": "laatste update"
              },
              {
                "name": "gew. budget"
              },
              {
                "name": "werkelijk"
              },
              {
                "name": "B allyear ss"
              },
              {
                "name": "B MTD"
              },
              {
                "name": "B YTD"
              },
              {
                "name": "B YTD ss"
              },
              {
                "name": "D MTD y"
              },
              {
                "name": "D YTD y"
              },
              {
                "name": "Besteed YTG ss"
              },
              {
                "name": "Budget+eindejaarscorrectie"
              },
              {
                "name": "Besteed YTD noblank"
              },
              {
                "name": "Besteed YTD ss"
              },
              {
                "name": "D YTD ss"
              },
              {
                "name": "D% YTD ss"
              },
              {
                "name": "B MTD 0"
              },
              {
                "name": "B YTD blank"
              },
              {
                "name": "test herverdeling budget"
              },
              {
                "name": "D YTD ss all"
              },
              {
                "name": "%obligo cf"
              },
              {
                "name": "%obligo"
              },
              {
                "name": "Actuals"
              },
              {
                "name": "B YTD ss all"
              },
              {
                "name": "D MTD blank 0"
              },
              {
                "name": "D YTD blank 0"
              },
              {
                "name": "Y as schaal"
              },
              {
                "name": "test schaal"
              },
              {
                "name": "obligo YTD"
              },
              {
                "name": "Actuals YTD"
              },
              {
                "name": "blank obligo graph"
              },
              {
                "name": "D YTD ss all ytd graph"
              },
              {
                "name": "D% YTD ss yearb"
              },
              {
                "name": "D MTD blank og"
              },
              {
                "name": "D YTD blank og"
              },
              {
                "name": "D YTD ss all og"
              },
              {
                "name": "obligo basic"
              },
              {
                "name": "max month current year (2022-12)"
              },
              {
                "name": "ytdfilter"
              },
              {
                "name": "max transaction yyyymmdd"
              },
              {
                "name": "days since refresh"
              },
              {
                "name": "Budget basic x"
              },
              {
                "name": "budget basic ytd"
              },
              {
                "name": "D YTD basis"
              },
              {
                "name": "D YTD basis A<B"
              },
              {
                "name": "D YTD basis A>B"
              },
              {
                "name": "B versie max numeric"
              },
              {
                "name": "B YTD ss scope"
              },
              {
                "name": "D YTD ss scope"
              },
              {
                "name": "D% YTD ss scope"
              },
              {
                "name": "versie precalc"
              },
              {
                "name": "budget 2022 v000"
              },
              {
                "name": "budget 2023 v000"
              },
              {
                "name": "delta budget v000"
              },
              {
                "name": "D"
              },
              {
                "name": "a"
              },
              {
                "name": "a if"
              },
              {
                "name": "a na23"
              },
              {
                "name": "a voor23"
              },
              {
                "name": "b"
              },
              {
                "name": "b if"
              },
              {
                "name": "b na23"
              },
              {
                "name": "b voor23"
              },
              {
                "name": "fixed column width"
              },
              {
                "name": "ifl timeperiod"
              },
              {
                "name": "switch x"
              },
              {
                "name": "switch_measures"
              }
            ]
          },
          {
            "name": "date",
            "columns": [
              {
                "name": "Year"
              },
              {
                "name": "Month"
              },
              {
                "name": "yeartext"
              },
              {
                "name": "Year Month Number"
              },
              {
                "name": "ytd?"
              },
              {
                "name": "Year Month Key"
              },
              {
                "name": "Year Quarter"
              },
              {
                "name": "Year Quarter Number"
              },
              {
                "name": "Quarter"
              },
              {
                "name": "Year Month"
              },
              {
                "name": "yyyy-mm"
              },
              {
                "name": "Month Number"
              },
              {
                "name": "Month In Quarter Number"
              },
              {
                "name": "Fiscal Year"
              },
              {
                "name": "Fiscal Year Number"
              },
              {
                "name": "Fiscal Year Quarter"
              },
              {
                "name": "Fiscal Year Quarter Number"
              },
              {
                "name": "Fiscal Quarter"
              },
              {
                "name": "Fiscal Month"
              },
              {
                "name": "Fiscal Month Number"
              },
              {
                "name": "Fiscal Month In Quarter Number"
              },
              {
                "name": "maandindex"
              },
              {
                "name": "jaarindex"
              },
              {
                "name": "now?"
              },
              {
                "name": "perdiode"
              },
              {
                "name": "periode code"
              }
            ],
            "hierarchies": [
              {
                "name": "year Hierarchy"
              }
            ],
            "measures": [
              {
                "name": "MaxDate"
              },
              {
                "name": "yeartoday"
              },
              {
                "name": "MaxYear"
              },
              {
                "name": "MaxYYYYMM"
              },
              {
                "name": "ytdfiltermeasure"
              }
            ]
          },
          {
            "name": "fct budget",
            "columns": [
              {
                "name": "soort_id"
              },
              {
                "name": "artiplek_id"
              },
              {
                "name": "versie"
              },
              {
                "name": "yyyymm"
              },
              {
                "name": "afkorting"
              },
              {
                "name": "ratioflag"
              },
              {
                "name": "compkey_versie"
              },
              {
                "name": "budget"
              },
              {
                "name": "objecttype"
              },
              {
                "name": "object_id"
              },
              {
                "name": "jaarbudget"
              },
              {
                "name": "soort/artiplek_id"
              },
              {
                "name": "soort_id_zonderalgkv"
              },
              {
                "name": "af_pe_ytd"
              },
              {
                "name": "filterytd"
              },
              {
                "name": "ratio"
              },
              {
                "name": "sleutelpnl switch"
              }
            ]
          },
          {
            "name": "budget versie",
            "columns": [
              {
                "name": "versie"
              },
              {
                "name": "objecttype"
              },
              {
                "name": "compkey_versie"
              }
            ]
          },
          {
            "name": "fct besteed",
            "columns": [
              {
                "name": "object_id"
              },
              {
                "name": "objecttype"
              },
              {
                "name": "boekdatum"
              },
              {
                "name": "yyyymm"
              },
              {
                "name": "artikel_id"
              },
              {
                "name": "soort_id"
              },
              {
                "name": "omschrijving"
              },
              {
                "name": "actual"
              },
              {
                "name": "obligo"
              },
              {
                "name": "bestelbon_id"
              },
              {
                "name": "termijnpositie"
              },
              {
                "name": "import_date"
              },
              {
                "name": "a_o"
              },
              {
                "name": "rn"
              },
              {
                "name": "soort_id_zonderalgkv"
              },
              {
                "name": "af_pe_ytd"
              },
              {
                "name": "filterytd"
              },
              {
                "name": "sleutelpnl switch"
              }
            ],
            "measures": [
              {
                "name": "actuals total"
              },
              {
                "name": "obligo total"
              },
              {
                "name": "besteed total"
              }
            ]
          },
          {
            "name": "opbrengsten_structuur",
            "columns": [
              {
                "name": "Pijlers"
              },
              {
                "name": "Soort+beschrijving"
              },
              {
                "name": "Begrenzing"
              },
              {
                "name": "Beschrijving begrenzing"
              },
              {
                "name": "Soort_id"
              },
              {
                "name": "plafond"
              },
              {
                "name": "Categorie pijler"
              }
            ],
            "measures": [
              {
                "name": "opbrengsten"
              },
              {
                "name": "OP PY"
              },
              {
                "name": "OP PY % total"
              },
              {
                "name": "OP PY total"
              },
              {
                "name": "budget eerst"
              },
              {
                "name": "prognose "
              },
              {
                "name": "check"
              },
              {
                "name": "scope_object"
              },
              {
                "name": "delta bva"
              },
              {
                "name": "plafond max"
              },
              {
                "name": "plafond max multiplied"
              },
              {
                "name": "budget laatst"
              },
              {
                "name": "headar pvp"
              }
            ]
          },
          {
            "name": "fct prognose opbrengsten",
            "columns": [
              {
                "name": "Rekening"
              },
              {
                "name": "prognose jaarbasis"
              },
              {
                "name": "YYYY-M"
              },
              {
                "name": "maandbasis verdeling %"
              },
              {
                "name": "prognose maandbasis"
              }
            ]
          }
        ]
      },
      {
        "name": "$YTD",
        "tables": [
          {
            "name": "Key Measures",
            "measures": [
              {
                "name": "$actual"
              },
              {
                "name": "$obligo"
              },
              {
                "name": "$budget"
              }
            ]
          },
          {
            "name": "bestelbon",
            "columns": [
              {
                "name": "bestel_tekst"
              },
              {
                "name": "inkoopartikel"
              },
              {
                "name": "leverancier_id"
              },
              {
                "name": "lev_land"
              },
              {
                "name": "lev_naam"
              },
              {
                "name": "lev_stad"
              },
              {
                "name": "lev_postcode"
              },
              {
                "name": "lev_straat"
              },
              {
                "name": "lev_bankrekening"
              },
              {
                "name": "bestelbonnummer"
              },
              {
                "name": "bestelbon_positie"
              },
              {
                "name": "bestelbon"
              },
              {
                "name": "ingevoerd_door"
              }
            ]
          },
          {
            "name": "budget versie",
            "columns": [
              {
                "name": "versie"
              },
              {
                "name": "objecttype"
              },
              {
                "name": "compkey_versie"
              }
            ]
          },
          {
            "name": "object",
            "columns": [
              {
                "name": "Level1"
              },
              {
                "name": "Directie"
              },
              {
                "name": "Level3"
              },
              {
                "name": "Level4"
              },
              {
                "name": "Level5"
              },
              {
                "name": "Level6"
              },
              {
                "name": "artikel"
              },
              {
                "name": "productiehuis"
              },
              {
                "name": "categorie"
              },
              {
                "name": "kanaal"
              },
              {
                "name": "productiereeks_fin_rapport"
              },
              {
                "name": "subgenre"
              },
              {
                "name": "klant"
              },
              {
                "name": "ipro_epro"
              },
              {
                "name": "budgetbeheer_std"
              },
              {
                "name": "budgetbeheer_plp"
              },
              {
                "name": "raamovereenkomst"
              },
              {
                "name": "netproducent"
              },
              {
                "name": "beschrijving_artikel_uppercase"
              },
              {
                "name": "path"
              },
              {
                "name": "objecttype"
              },
              {
                "name": "object+omschrijving"
              },
              {
                "name": "object_id"
              },
              {
                "name": "object_description"
              },
              {
                "name": "object_parent"
              }
            ],
            "hierarchies": [
              {
                "name": "Object Hierarchy"
              },
              {
                "name": "Object Hierarchy basic"
              }
            ]
          },
          {
            "name": "date",
            "columns": [
              {
                "name": "Year"
              },
              {
                "name": "Month"
              },
              {
                "name": "yyyy-mm"
              }
            ]
          },
          {
            "name": "fct besteed",
            "columns": [
              {
                "name": "omschrijving"
              }
            ]
          },
          {
            "name": "soort",
            "columns": [
              {
                "name": "soort_id"
              }
            ]
          }
        ]
      }
    ],
    "expressions": [
      {
        "name": "actual_manual",
        "kind": "m",
        "expression": [
          "let",
          "    Source = SharePoint.Files(\"https://rto365.sharepoint.com/sites/FCO-14PowerBI2/\", [ApiVersion = 15]),",
          "    #\"Meenemen xlsx_https://rto365 sharepoint com/sites/FCO-14PowerBI2/Data Power BI/Financiële data/Opbrengstplaats/Meenemen/\" = Source{[Name=\"manual_actuals.xlsx\",#\"Folder Path\"=\"https://rto365.sharepoint.com/sites/FCO-14PowerBI2/Data Power BI/Financiële data/Feedback/\"]}[Content],",
          "    #\"Imported Excel Workbook\" = Excel.Workbook(#\"Meenemen xlsx_https://rto365 sharepoint com/sites/FCO-14PowerBI2/Data Power BI/Financiële data/Opbrengstplaats/Meenemen/\"),",
          "    Tabel1_Table = #\"Imported Excel Workbook\"{[Item=\"ManualActuals\",Kind=\"Table\"]}[Data],",
          "    #\"Unpivoted Other Columns\" = Table.UnpivotOtherColumns(Tabel1_Table, {\"object_id\"}, \"Attribute\", \"Value\"),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Unpivoted Other Columns\",{{\"Value\", type number}}),",
          "    #\"Renamed Columns\" = Table.RenameColumns(#\"Changed Type\",{{\"Attribute\", \"yyyymm\"}, {\"Value\", \"actual\"}}),",
          "    #\"Added Custom\" = Table.AddColumn(#\"Renamed Columns\", \"a_o\", each \"A\"),",
          "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Added Custom\",{{\"a_o\", type text}}),",
          "    #\"Added Custom1\" = Table.AddColumn(#\"Changed Type1\", \"Filtersoort\", each \"YTD\")",
          "in",
          "    #\"Added Custom1\""
        ],
        "queryGroup": "Sharepoint\\Sharepoint YTD",
        "lineageTag": "ffaca60c-fe30-4b68-9c77-59d1a0f5cb30",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ]
      },
      {
        "name": "SourceAthena",
        "description": [
          "analytics_nonprod_athena",
          "analytics_prod"
        ],
        "kind": "m",
        "expression": "\"analytics_prod\" meta [IsParameterQuery=true, List={\"analytics_nonprod_athena\", \"analytics_prod\"}, DefaultValue=\"analytics_nonprod_athena\", Type=\"Text\", IsParameterQueryRequired=true]",
        "queryGroup": "Datalake",
        "lineageTag": "2790f2d5-2ea0-4f35-85da-e10db2baed13",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Text"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ]
      },
      {
        "name": "opbrengsten_plafond",
        "kind": "m",
        "expression": [
          "let",
          "    Source = SharePoint.Files(\"https://rto365.sharepoint.com/sites/FCO-14PowerBI2/\", [ApiVersion = 15]),",
          "    #\"Sorted Rows\" = Table.Sort(Source,{{\"Name\", Order.Ascending}}),",
          "    #\"structuur_opbrengsten xlsx_https://rto365 sharepoint com/sites/FCO-14PowerBI2/Data Power BI/Financiële data/Feedback/\" = #\"Sorted Rows\"{[Name=\"structuur_opbrengsten.xlsx\",#\"Folder Path\"=\"https://rto365.sharepoint.com/sites/FCO-14PowerBI2/Data Power BI/Financiële data/Feedback/\"]}[Content],",
          "    ImportedExcelWorkbook = Excel.Workbook(#\"structuur_opbrengsten xlsx_https://rto365 sharepoint com/sites/FCO-14PowerBI2/Data Power BI/Financiële data/Feedback/\"),",
          "    tabel = ImportedExcelWorkbook{[Item=\"plafond\",Kind=\"Table\"]}[Data]",
          "in",
          "    tabel"
        ],
        "queryGroup": "Sharepoint\\Sharepoint Opbrengsten",
        "lineageTag": "1fb56c59-ca67-48ad-bd15-d467ac42be1c",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "pnl_lineitem",
        "kind": "m",
        "expression": [
          "let",
          "    Source = SharePoint.Files(\"https://rto365.sharepoint.com/sites/FCO-14PowerBI2/\", [ApiVersion = 15]),",
          "    #\"Evolutie inkomsten 2019 - 2023_PL vorm_EDV xlsx_https://rto365 sharepoint com/sites/FCO-14PowerBI2/Data Power BI/Financiële data/P&L Opbrengsten/\" = Source{[Name=\"Evolutie inkomsten 2019 - 2023_PL vorm_EDV.xlsx\",#\"Folder Path\"=\"https://rto365.sharepoint.com/sites/FCO-14PowerBI2/Data Power BI/Financiële data/P&L Opbrengsten/\"]}[Content],",
          "    #\"Imported Excel Workbook\" = Excel.Workbook(#\"Evolutie inkomsten 2019 - 2023_PL vorm_EDV xlsx_https://rto365 sharepoint com/sites/FCO-14PowerBI2/Data Power BI/Financiële data/P&L Opbrengsten/\"),",
          "    Tabel5_Table = #\"Imported Excel Workbook\"{[Item=\"Tabel5\",Kind=\"Table\"]}[Data],",
          "    #\"Sorted Rows\" = Table.Sort(Tabel5_Table,{{\"nr line item\", Order.Ascending}}),",
          "    #\"Removed Duplicates\" = Table.Distinct(#\"Sorted Rows\", {\"nr line item\"}),",
          "    #\"Duplicated Column\" = Table.DuplicateColumn(#\"Removed Duplicates\", \"P&L niv 1\", \"P&L niv 1 - Copy\"),",
          "    #\"Extracted Text Before Delimiter\" = Table.TransformColumns(#\"Duplicated Column\", {{\"P&L niv 1 - Copy\", each Text.BeforeDelimiter(_, \". \"), type text}}),",
          "    #\"Replaced Errors\" = Table.ReplaceErrorValues(#\"Extracted Text Before Delimiter\", {{\"P&L niv 1 - Copy\", 100}}),",
          "    #\"Replaced Value\" = Table.ReplaceValue(#\"Replaced Errors\",\"10\",\"99\",Replacer.ReplaceText,{\"P&L niv 1 - Copy\"}),",
          "    #\"Sorted Rows1\" = Table.Sort(#\"Replaced Value\",{{\"P&L niv 1 - Copy\", Order.Ascending}}),",
          "    #\"Renamed Columns\" = Table.RenameColumns(#\"Sorted Rows1\",{{\"P&L niv 1 - Copy\", \"P&L niv 1 - sort\"}}),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\",{{\"nr line item\", type text}, {\"P&L niv 1\", type text}, {\"P&L niv 12\", type text}, {\"P&L niv 3\", type text}, {\"Extra info niet in systeem\", type text}})",
          "in",
          "    #\"Changed Type\""
        ],
        "queryGroup": "Sharepoint\\Sharepoint PNL",
        "lineageTag": "b4fb7623-3766-4d7d-93c4-89821f254c2e",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "pnl_conv2022",
        "kind": "m",
        "expression": [
          "let",
          "    Source = SharePoint.Files(\"https://rto365.sharepoint.com/sites/FCO-14PowerBI2/\", [ApiVersion = 15]),",
          "    #\"Evolutie inkomsten 2019 - 2023_PL vorm_EDV xlsx_https://rto365 sharepoint com/sites/FCO-14PowerBI2/Data Power BI/Financiële data/P&L Opbrengsten/\" = Source{[Name=\"Evolutie inkomsten 2019 - 2023_PL vorm_EDV.xlsx\",#\"Folder Path\"=\"https://rto365.sharepoint.com/sites/FCO-14PowerBI2/Data Power BI/Financiële data/P&L Opbrengsten/\"]}[Content],",
          "    #\"Imported Excel Workbook\" = Excel.Workbook(#\"Evolutie inkomsten 2019 - 2023_PL vorm_EDV xlsx_https://rto365 sharepoint com/sites/FCO-14PowerBI2/Data Power BI/Financiële data/P&L Opbrengsten/\"),",
          "    #\"Conversietabel verleden_Sheet\" = #\"Imported Excel Workbook\"{[Item=\"Conversietabel verleden\",Kind=\"Sheet\"]}[Data],",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Conversietabel verleden_Sheet\",{{\"Column1\", type text}, {\"Column2\", type text}, {\"Column3\", type text}}),",
          "    #\"Replaced Errors\" = Table.ReplaceErrorValues(#\"Changed Type\", {{\"Column3\", \"fout\"}}),",
          "    #\"Lowercased Text\" = Table.TransformColumns(#\"Replaced Errors\",{{\"Column3\", Text.Lower, type text}}),",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Lowercased Text\", [PromoteAllScalars=true])",
          "in",
          "    #\"Promoted Headers\""
        ],
        "queryGroup": "Sharepoint\\Sharepoint PNL",
        "lineageTag": "5a46c1d2-53be-4c7b-ad5c-652494a30221",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "pnl_conv2023",
        "kind": "m",
        "expression": [
          "let",
          "    Source = SharePoint.Files(\"https://rto365.sharepoint.com/sites/FCO-14PowerBI2/\", [ApiVersion = 15]),",
          "    #\"Evolutie inkomsten 2019 - 2023_PL vorm_EDV xlsx_https://rto365 sharepoint com/sites/FCO-14PowerBI2/Data Power BI/Financiële data/P&L Opbrengsten/\" = Source{[Name=\"Evolutie inkomsten 2019 - 2023_PL vorm_EDV.xlsx\",#\"Folder Path\"=\"https://rto365.sharepoint.com/sites/FCO-14PowerBI2/Data Power BI/Financiële data/P&L Opbrengsten/\"]}[Content],",
          "    #\"Imported Excel Workbook\" = Excel.Workbook(#\"Evolutie inkomsten 2019 - 2023_PL vorm_EDV xlsx_https://rto365 sharepoint com/sites/FCO-14PowerBI2/Data Power BI/Financiële data/P&L Opbrengsten/\"),",
          "    #\"Conversietabel vanaf 2023_Sheet\" = #\"Imported Excel Workbook\"{[Item=\"Conversietabel vanaf 2023\",Kind=\"Sheet\"]}[Data],",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Conversietabel vanaf 2023_Sheet\", [PromoteAllScalars=true]),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"P&L niv 3\", type text}}),",
          "    #\"Lowercased Text\" = Table.TransformColumns(#\"Changed Type\",{{\"P&L niv 3\", Text.Lower, type text}}),",
          "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Lowercased Text\",{{\"opbr soort kort\", type text}})",
          "in",
          "    #\"Changed Type1\""
        ],
        "queryGroup": "Sharepoint\\Sharepoint PNL",
        "lineageTag": "43597a98-f04f-4faa-af2b-542ad6dab8d4",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "pnl_conv",
        "kind": "m",
        "expression": [
          "let",
          "    Source = Table.NestedJoin(pnl_conv2023, {\"sleutel\"}, pnl_conv2022, {\"Geconverteerde sleutel voor rapportering\"}, \"pnl_conv2022\", JoinKind.LeftOuter),",
          "    #\"Expanded pnl_conv2022\" = Table.ExpandTableColumn(Source, \"pnl_conv2022\", {\"Sleutel geboekt voor 2023\"}, {\"Sleutel geboekt voor 2023\"}),",
          "    #\"Added Conditional Column\" = Table.AddColumn(#\"Expanded pnl_conv2022\", \"sleutel=gelijk?\", each if [sleutel] = [Sleutel geboekt voor 2023] then true else false),",
          "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Added Conditional Column\",{\"sleutel=gelijk?\", \"Sleutel geboekt voor 2023\", \"sleutel\", \"opbrengstenplaats\", \"opbrengstensoort\", \"zonder ALG/KV\", \"opbr soort kort\", \"opbrengstenplaats omschrijving\", \"opbrengstensoort omschrijving\", \"P&L niv 3\", \"P&L niv 1\", \"P&L niv 2\", \"P&I nov 3\"}),",
          "    #\"Renamed Columns\" = Table.RenameColumns(#\"Reordered Columns\",{{\"sleutel\", \"sleutel_na2023\"}, {\"Sleutel geboekt voor 2023\", \"sleutel_voor2023\"}}),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\",{{\"sleutel=gelijk?\", type logical}})",
          "in",
          "    #\"Changed Type\""
        ],
        "queryGroup": "Sharepoint\\Sharepoint PNL",
        "lineageTag": "f10e1dbd-c2e9-4ef4-922c-b7dd9a9d0811",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      }
    ],
    "queryGroups": [
      {
        "folder": "Datalake",
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "3"
          }
        ]
      },
      {
        "folder": "Sharepoint\\Sharepoint YTD",
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "1"
          }
        ]
      },
      {
        "folder": "Sharepoint\\Sharepoint Opbrengsten",
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "2"
          }
        ]
      },
      {
        "folder": "Sharepoint\\Sharepoint PNL",
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ]
      },
      {
        "folder": "Sharepoint",
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "5"
          }
        ]
      }
    ],
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"SourceAthena\",\"fct besteed\",\"fct budget\",\"precalc table AB\",\"soort\",\"bestelbon\",\"importdate\",\"budget versie\",\"object\",\"actual_manual\",\"opmerkingen\",\"opbrengsten_structuur\",\"fct prognose opbrengsten\",\"opbrengsten_plafond\",\"pnl_lineitem\",\"pnl_conv2022\",\"pnl_conv2023\",\"pnl_conv\",\"dim pnl\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.116.622.0 (23.04)"
      },
      {
        "name": "TabularEditor_SerializeOptions",
        "value": "{\"IgnoreInferredObjects\":true,\"IgnoreInferredProperties\":true,\"IgnoreTimestamps\":true,\"SplitMultilineStrings\":true,\"PrefixFilenames\":false,\"LocalTranslations\":false,\"LocalPerspectives\":false,\"LocalRelationships\":false,\"Levels\":[\"Data Sources\",\"Perspectives\",\"Relationships\",\"Roles\",\"Shared Expressions\",\"Tables\",\"Tables/Calculation Items\",\"Tables/Columns\",\"Tables/Hierarchies\",\"Tables/Measures\",\"Tables/Partitions\",\"Translations\"],\"AlsoSaveAsBim\":true}"
      }
    ]
  }
}